// AUTO-GENERATED by scripts/gen-lesson-registry.ts — DO NOT EDIT.
// Regenerate with: pnpm gen:registry
import type { ComponentType } from "react";
import type { LessonSlug } from "./slugs";
import type { Locale } from "./types";

export type LessonModuleLoader = () => Promise<{ default: ComponentType }>;

export const LESSON_REGISTRY: Partial<
  Record<LessonSlug, Partial<Record<Locale, LessonModuleLoader>>>
> = {

};
