import { pick, type Locale, type Localized} from "@/content/types";

// Preset sources carry `// @key` markers instead of prose so one shader body
// serves both locales — the code can never drift between languages, only the
// comment text does. Keys are global (helpers like fbm are shared by several
// presets); tests/unit/playground-presets.test.ts fails on a missing key.
export const PRESET_COMMENTS: Localized<Record<string, string>> = {
  vi: {
    polarBackdrop: "Nền mờ theo bán kính, để khung hình không bao giờ chỉ có một màu",
    sdfNormalGradient: "Normal là gradient của hàm khoảng cách — sai phân sáu mẫu quanh điểm",
    lambertTerm: "N·L: bề mặt càng quay về phía đèn càng sáng",
    blinnPhong: "Chóp specular theo vector nửa đường giữa đèn và mắt",
    softShadowRatio: "Bóng mềm miễn phí: giữ tỉ số nhỏ nhất giữa khoảng cách tới vật cản và quãng đã đi",
    shadowSharpness: "Rê chuột ngang để đổi độ sắc của bóng",
    aoSampleAlong: "Đi vài bước dọc normal: bước nào bị chặn sớm hơn dự tính là chỗ bị che khuất",
    fogHeightFalloff: "Mật độ giảm theo độ cao, nên đỉnh nhô khỏi lớp mù còn chân vẫn chìm",
    fogBeerLambert: "Beer-Lambert: sương che theo hàm mũ của quãng đường, không tuyến tính",
    cloudDensityFbm: "Ba lớp noise cộng lại, cắt ngưỡng rồi kẹp trong một lớp phẳng",
    cloudMarchFixedStep: "Bước đều thay vì sphere tracing: mây không có bề mặt để mà đo khoảng cách tới",
    cloudLightSample: "Lấy thêm một mẫu về phía mặt trời để biết điểm này bị mây phía trên che bao nhiêu",
    mandelZoom: "Phóng theo hàm mũ về một điểm trên biên tập Mandelbrot",
    mandelSquare: "z = z² + c viết bằng số phức: phần thực và phần ảo tách ra",
    mandelSmooth: "Số vòng lặp mượt hoá — nếu không sẽ ra các vành màu bậc thang",
    juliaConstant: "Julia dùng c cố định cho cả ảnh; ở đây c chính là vị trí chuột",
    juliaIterate: "Cùng công thức z² + c với Mandelbrot, chỉ khác chỗ nào cố định",
    juliaInside: "Điểm không thoát ra sau MAX vòng thì coi như nằm trong tập",
    mandelPalette: "Lấy căn số vòng lặp trước khi tô: dải màu giãn đều ở vùng ngoài",
    juliaSmooth: "Cùng phép mượt hoá của Mandelbrot — thiếu nó thì vùng ngoài bệt một màu",
    bulbPower: "Số mũ 8 là quy ước phổ biến nhất; đổi nó là đổi hẳn hình dạng",
    bulbToPolar: "Chuyển sang toạ độ cầu để nâng luỹ thừa cho một điểm 3D",
    bulbRaisePower: "Nâng bán kính lên luỹ thừa và nhân góc lên — bản 3D của z²",
    bulbDistanceEstimate: "Ước lượng khoảng cách: fractal không có công thức khoảng cách đúng, chỉ có cận dưới an toàn",
    bulbGlow: "Cộng dồn ánh sáng mờ theo tia: tia lướt sát bề mặt sáng lên thành quầng",
    toneAxes: "Trục ngang là giá trị HDR 0..4, trục dọc là kết quả 0..1",
    toneOneLine: "Vạch xám là mốc 1.0 — chỗ màn hình hết chỗ để sáng thêm",
    crtBars: "Dải màu tự dựng làm ảnh nguồn — không có texture nào ở đây cả",
    srgbNaive: "Trộn thẳng trên giá trị sRGB — cách hầu hết code vẫn làm",
    srgbCorrect: "Giải mã về linear, trộn ở đó, rồi mã hoá ngược lại",
    srgbSplit: "Nửa trên trộn sai, nửa dưới trộn đúng — chỉ khác nhau ở khúc giữa",
    acesFit: "Xấp xỉ ACES của Krzysztof Narkowicz, đủ dùng cho thời gian thực",
    toneClip: "Kẹp cứng: mọi thứ trên 1.0 bẹt thành một mảng trắng",
    toneReinhard: "Reinhard: chia cho chính nó cộng 1, không bao giờ chạm 1.0",
    bayerMatrix: "Ma trận Bayer 4x4 — thứ tự này khiến mắt đọc ra sắc độ chứ không ra nhiễu",
    bayerLevels: "Chỉ 4 mức sáng cho cả dải",
    bayerThreshold: "Ngưỡng đổi theo vị trí pixel, nên hai pixel cạnh nhau làm tròn khác chiều",
    bandingMouse: "Rê chuột ngang để đổi số bit từ 2 lên 8",
    bandingRamp: "Dải màu mượt làm mẫu — vùng chuyển từ từ là chỗ banding lộ trước",
    bandingQuantise: "Làm tròn xuống mức gần nhất: đó là toàn bộ nguyên nhân của banding",
    crtCurve: "Phình toạ độ ra theo bình phương khoảng cách để giả độ cong mặt kính",
    crtOffscreen: "Ngoài rìa kính thì không có ảnh, trả về màu vỏ máy",
    crtScanline: "Vạch quét chạy dọc theo thời gian",
    crtMask: "Mặt nạ ba pixel con R-G-B, đúng cách CRT thật tạo màu",
    caRadial: "Lệch tăng dần theo khoảng cách tới tâm — ống kính thật cũng vậy",
    caThreeSamples: "Lấy mẫu ba lần ở ba chỗ khác nhau, mỗi lần lấy một kênh",
    vignetteFalloff: "Tối dần về bốn góc, đo trong không gian đã sửa tỉ lệ khung hình",
    grainAnimated: "Hạt đổi theo từng bước 24fps — đứng yên thì mắt đọc ra vết bẩn, không ra phim",
    halftoneRotate: "Xoay lưới 30 độ: lưới thẳng trục sẽ đập vào mắt thành hoa văn moiré",
    halftoneDotSize: "Vùng càng sáng chấm càng nhỏ — sắc độ nằm ở kích thước chấm, không ở màu mực",
    polarPair: "Đổi (x, y) thành (bán kính, góc) — hai số, cùng một điểm",
    polarFold: "Gấp góc về một múi rồi lấy trị tuyệt đối: đó là toàn bộ kaleidoscope",
    polarBackToXy: "Về lại xy để vẽ, sau khi đã méo góc",
    easePlotBand: "Vẽ đường cong bằng một dải mỏng quanh giá trị hàm",
    easeSmoothstep: "smoothstep viết tay: đạo hàm bằng 0 ở cả hai đầu nên không giật",
    easeSameEndpoints: "Hai đầu sáng lên: mọi đường cong đều đi qua đúng hai điểm đó",
    truchetFlip: "Lật ô theo hash: chỉ hai hướng, mà ra được mê cung vô tận",
    truchetTwoArcs: "Hai cung tròn ở hai góc đối — nối liền được vì chúng chạm đúng giữa cạnh ô",
    rdChannels: "Hai chất khuếch tán, cất trong hai kênh: A ở đỏ, B ở lục",
    rdCoarse: "Lấy mẫu thưa hơn một texel để hoa văn to lên, dễ nhìn hơn",
    rdSeedEverywhere: "Gieo B khắp mặt phẳng: chờ một đốm lan ra thì quá lâu",
    rdEquations: "Gray-Scott: A bị B ăn, f bơm A vào, k rút B ra",
    rdMousePoke: "Rê chuột để bơm thêm B và xem hoa văn mọc lại từ đó",
    lifeCellGrid: "Một ô 6x6 pixel, không thì ô chỉ bằng một pixel và không nhìn ra gì",
    lifeStateChannel: "Đọc trạng thái từ kênh lục: nó chỉ nhận đúng 0 hoặc 1",
    lifeSeedDensity: "Khoảng 38% ô sống lúc đầu",
    lifeRule: "Luật B3/S23: sinh khi có đúng 3 hàng xóm, sống tiếp khi có 2 hoặc 3",
    lifeReseed: "Rắc thêm vài ô sống để bàn cờ không chết cứng thành tĩnh vật",
    trailSeedRings: "Gieo bằng vân tròn để có sẵn hình trước khi ai chạm chuột",
    trailAdvect: "Lấy mẫu lệch đi một chút mỗi frame: cả bức tranh trôi theo dòng",
    trailDecay: "Nhân 0.985 mỗi frame — vệt cũ mờ dần thay vì đọng lại mãi",
    waveSeedDrops: "Gieo sẵn một giọt và một gợn sóng",
    waveTwoTimeSteps: "Phương trình sóng cần hai mốc thời gian: kênh đỏ là hiện tại, lục là frame trước",
    waveDecode: "Bốn hàng xóm được lưu ở dạng 0..1, giải mã về -1..1 trước khi cộng",
    waveEquation: "Trung bình hàng xóm trừ đi mốc trước — đó là toàn bộ phương trình sóng",
    waveDamping: "Không có suy giảm thì sóng dội mãi và mặt nước thành nhiễu",
    waveDrip: "Nhỏ giọt ngẫu nhiên theo thời gian, cộng thêm giọt tại con trỏ",
    cosinePalette: "Bảng màu cosine: a + b * cos(2pi * (c*t + d))",
    mouseHalo: "Quầng sáng bám theo con trỏ (uMouse chuẩn hoá 0..1)",
    fourBands: "Bốn dải ngang, mỗi dải vẽ một hàm nhào nặn khác nhau",
    claySmin: "Hoà hai hình như đất sét thay vì cắt góc cứng",
    isolines: "vân đồng mức",
    whichCell: "ô nào",
    posInCell: "vị trí trong ô",
    aspectSpace: "Đo khoảng cách trong không gian đã sửa tỉ lệ khung hình",
    rippleDecay: "Sóng lan ra, tắt dần theo khoảng cách",
    fadeCurve: "fade: bỏ đi thì lộ hình kim cương ở mắt lưới",
    scanNeighbours: "Quét 3x3 ô lân cận: chỉ xét ô của mình sẽ đứt gãy ở biên",
    f2f1Border: "F2 - F1 cho ra viền tế bào",
    quilezWarp: "Kỹ thuật Quilez: dùng noise làm méo chính toạ độ đưa vào noise",
    curlDivFree: "Curl 2D: xoay gradient 90 độ nên phân kỳ luôn bằng 0",
    walkUpstream: "đi ngược dòng vài bước",
    plasmaSum: "Demoscene: cộng vài sóng sin lệch pha rồi map qua bảng màu",
    sceneIsFunction: "Cảnh là một hàm khoảng cách, không có tam giác nào",
    sphereTracing: "Sphere tracing: mỗi bước đi đúng khoảng cách an toàn",
    weldShapes: "hàn hai khối lại như đất sét",
    repeatSpace: "Lặp toạ độ truy vấn: một object, vô hạn bản sao, bộ nhớ O(1)",
    cautiousStep: "bước dè hơn vì mod nói dối gần biên ô",
  },
  en: {
    polarBackdrop: "A faint radial backdrop, so the frame is never a single colour",
    sdfNormalGradient: "The normal is the gradient of the distance function — six samples around the point",
    lambertTerm: "N·L: the more a surface faces the light, the brighter it is",
    blinnPhong: "A specular highlight from the halfway vector between light and eye",
    softShadowRatio: "Soft shadows for free: keep the smallest ratio of clearance to distance travelled",
    shadowSharpness: "Move the pointer sideways to change how sharp the shadow is",
    aoSampleAlong: "Step along the normal: a step blocked sooner than expected is a point that is occluded",
    fogHeightFalloff: "Density falls off with height, so peaks break out of the haze while their bases stay buried",
    fogBeerLambert: "Beer-Lambert: fog hides things exponentially with distance, never linearly",
    cloudDensityFbm: "Three octaves of noise, thresholded and confined to a flat slab",
    cloudMarchFixedStep: "Fixed steps instead of sphere tracing: a cloud has no surface to measure a distance to",
    cloudLightSample: "One extra sample toward the sun tells you how much cloud is overhead",
    mandelZoom: "Zoom exponentially into one point on the boundary of the Mandelbrot set",
    mandelSquare: "z = z² + c in complex numbers, with the real and imaginary parts written out",
    mandelSmooth: "Smoothed iteration count — without it the colours come out in stepped rings",
    juliaConstant: "A Julia set uses one fixed c for the whole image; here c is the pointer",
    juliaIterate: "The same z² + c as Mandelbrot; only which part is held fixed differs",
    juliaInside: "A point that has not escaped after MAX steps counts as inside the set",
    mandelPalette: "Take the root of the iteration count before colouring: the bands spread evenly outside",
    juliaSmooth: "The same smoothing as Mandelbrot — without it the outside flattens to one colour",
    bulbPower: "Power 8 is the usual choice; changing it changes the shape entirely",
    bulbToPolar: "Go to spherical coordinates to raise a 3D point to a power at all",
    bulbRaisePower: "Raise the radius and multiply the angles — the 3D version of squaring",
    bulbDistanceEstimate: "A distance estimate: a fractal has no exact distance, only a safe lower bound",
    bulbGlow: "Accumulate faint light along the ray, so grazing rays build up a halo",
    toneAxes: "The x axis is HDR input 0 to 4, the y axis is the result 0 to 1",
    toneOneLine: "The grey line marks 1.0, where a display runs out of room",
    crtBars: "Colour bars built here as the source image; there is no texture in play",
    srgbNaive: "Mixing straight on sRGB values — what most code does",
    srgbCorrect: "Decode to linear, mix there, then encode back",
    srgbSplit: "Top half mixed wrong, bottom half right — they differ only in the middle",
    acesFit: "Krzysztof Narkowicz's ACES fit, close enough for real time",
    toneClip: "Hard clip: everything above 1.0 flattens into one white slab",
    toneReinhard: "Reinhard: divide by itself plus one, so it never quite reaches 1.0",
    bayerMatrix: "The 4x4 Bayer matrix — this ordering is what the eye reads as shade, not noise",
    bayerLevels: "Only four shades across the whole ramp",
    bayerThreshold: "The threshold shifts with pixel position, so neighbours round opposite ways",
    bandingMouse: "Move the pointer sideways to take the bit depth from 2 up to 8",
    bandingRamp: "A smooth gradient to work on — slow transitions are where banding shows first",
    bandingQuantise: "Round down to the nearest level: that is the whole cause of banding",
    crtCurve: "Push coordinates outward by distance squared to fake the curve of the glass",
    crtOffscreen: "Past the edge of the glass there is no picture, only the case",
    crtScanline: "A scan line travelling down over time",
    crtMask: "An R-G-B subpixel mask, which is how a real CRT made colour at all",
    caRadial: "The offset grows with distance from centre, exactly as a real lens does",
    caThreeSamples: "Sample three times at three places, taking one channel from each",
    vignetteFalloff: "Darken toward the corners, measured in aspect-corrected space",
    grainAnimated: "Grain steps at 24fps — hold it still and the eye reads dirt, not film",
    halftoneRotate: "Rotate the grid 30 degrees: axis-aligned dots read as moire instead",
    halftoneDotSize: "Brighter areas get smaller dots — the shade lives in dot size, not ink colour",
    polarPair: "Turn (x, y) into (radius, angle) — two numbers, same point",
    polarFold: "Fold the angle into one wedge and take the absolute value: that is the whole kaleidoscope",
    polarBackToXy: "Back to xy for drawing, now that the angle has been bent",
    easePlotBand: "Draw a curve as a thin band around the function value",
    easeSmoothstep: "smoothstep by hand: zero slope at both ends, so nothing jerks",
    easeSameEndpoints: "Both ends light up: every curve here passes through those same two points",
    truchetFlip: "Flip the tile on a hash: two orientations, and an endless maze falls out",
    truchetTwoArcs: "Two arcs in opposite corners — they connect because both meet the cell edge at its midpoint",
    rdChannels: "Two diffusing chemicals kept in two channels: A in red, B in green",
    rdCoarse: "Sampling wider than one texel to grow the pattern to a readable size",
    rdSeedEverywhere: "Seed B across the whole plane: waiting for one blob to spread takes too long",
    rdEquations: "Gray-Scott: B eats A, f feeds A in, k drains B away",
    rdMousePoke: "Drag the pointer to inject more B and watch the pattern regrow from it",
    lifeCellGrid: "One cell per 6x6 pixels, or a cell is a single pixel and reads as noise",
    lifeStateChannel: "Read state from green: it only ever holds exactly 0 or 1",
    lifeSeedDensity: "About 38% of cells start alive",
    lifeRule: "B3/S23: born on exactly 3 neighbours, survives on 2 or 3",
    lifeReseed: "Sprinkle in live cells so the board cannot settle into a still life",
    trailSeedRings: "Seeded with rings so there is something to see before anyone touches the mouse",
    trailAdvect: "Sample slightly offset each frame and the whole picture drifts along a flow",
    trailDecay: "Times 0.985 per frame — old strokes fade instead of piling up forever",
    waveSeedDrops: "Seeded with one drop and one ring",
    waveTwoTimeSteps: "The wave equation needs two moments in time: red is now, green is the frame before",
    waveDecode: "The four neighbours are stored as 0..1; decode to -1..1 before summing",
    waveEquation: "Neighbour average minus the earlier moment — that is the whole wave equation",
    waveDamping: "Without damping the waves reflect forever and the surface turns to noise",
    waveDrip: "Random drips over time, plus one at the pointer",
    cosinePalette: "Cosine palette: a + b * cos(2pi * (c*t + d))",
    mouseHalo: "Halo that follows the cursor (uMouse is normalised 0..1)",
    fourBands: "Four horizontal bands, one shaping function each",
    claySmin: "Blend the two shapes like clay instead of a hard corner",
    isolines: "distance isolines",
    whichCell: "which cell",
    posInCell: "position inside the cell",
    aspectSpace: "Measure distance in aspect-corrected space",
    rippleDecay: "Wave spreads outward, damped by distance",
    fadeCurve: "fade: drop it and the grid diamonds show up",
    scanNeighbours: "Scan the 3x3 neighbourhood: own cell only breaks at borders",
    f2f1Border: "F2 - F1 gives the cell border",
    quilezWarp: "Quilez trick: use noise to distort the coordinates fed to noise",
    curlDivFree: "2D curl: rotating the gradient 90 degrees makes divergence zero",
    walkUpstream: "walk a few steps upstream",
    plasmaSum: "Demoscene: sum a few phase-shifted sines, then map to a palette",
    sceneIsFunction: "The scene is a distance function — no triangles at all",
    sphereTracing: "Sphere tracing: every step is the largest safe distance",
    weldShapes: "weld the two masses together like clay",
    repeatSpace: "Repeat the query point: one object, endless copies, O(1) memory",
    cautiousStep: "shorter steps because mod lies near the cell border",
  },
};

const MARKER = /\/\/\s*@(\w+)/g;

/** Swap `// @key` markers for the locale's comment text. */
export function localizeSource(source: string, locale: Locale): string {
  const dict = pick(PRESET_COMMENTS, locale);
  return source.replace(MARKER, (_m, key: string) => `// ${dict[key] ?? key}`);
}

/** Every marker used by any preset source — drives the completeness test. */
export function markersIn(source: string): string[] {
  return [...source.matchAll(MARKER)].map((m) => m[1] ?? "");
}
