import fs from "node:fs";
import path from "node:path";
import GithubSlugger from "github-slugger";
import { LESSON_SLUGS } from "../content/slugs";

// Emits typed maps from the content/lessons filesystem (decision D2):
//   LESSON_REGISTRY     slug×locale → dynamic import of theory MDX
//   REFERENCES_REGISTRY slug        → dynamic import of references.ts
//   TOC_REGISTRY        slug×locale → TocItem[] parsed from MDX headings
// TOC lives here (not a remark plugin) because Turbopack requires MDX plugins
// in serializable string form — injecting an `export const toc` via estree is
// far heavier than parsing headings in this generator.

const LESSONS_DIR = path.join(process.cwd(), "content", "lessons");
const OUT = path.join(process.cwd(), "content", "lesson-registry.generated.ts");
const LOCALES = ["vi", "en"] as const;

interface TocItem {
  id: string;
  text: string;
  depth: 2 | 3 | 4;
}

function extractToc(mdxSource: string): TocItem[] {
  // Strip fenced code blocks so `## comments` inside fences don't match
  const withoutFences = mdxSource.replace(/^```[\s\S]*?^```/gm, "");
  const slugger = new GithubSlugger();
  const items: TocItem[] = [];
  for (const line of withoutFences.split("\n")) {
    const m = /^(#{2,4})\s+(.+?)\s*$/.exec(line);
    if (!m || !m[1] || !m[2]) continue;
    // Strip inline markdown the way rendered text content would appear
    const text = m[2]
      .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
      .replace(/[`*_]/g, "")
      .trim();
    items.push({
      id: slugger.slug(text),
      text,
      depth: m[1].length as 2 | 3 | 4,
    });
  }
  return items;
}

const slugSet = new Set<string>(LESSON_SLUGS);
const theoryEntries: string[] = [];
const referenceEntries: string[] = [];
const tocEntries: string[] = [];
const demoEntries: string[] = [];
const exerciseEntries: string[] = [];
const warnings: string[] = [];

if (fs.existsSync(LESSONS_DIR)) {
  for (const trackDir of fs.readdirSync(LESSONS_DIR).sort()) {
    const trackPath = path.join(LESSONS_DIR, trackDir);
    if (!fs.statSync(trackPath).isDirectory() || trackDir.startsWith("_")) {
      continue;
    }
    for (const lessonDir of fs.readdirSync(trackPath).sort()) {
      const lessonPath = path.join(trackPath, lessonDir);
      if (!fs.statSync(lessonPath).isDirectory()) continue;
      if (!slugSet.has(lessonDir)) {
        warnings.push(`skipped ${trackDir}/${lessonDir}: not in LESSON_SLUGS`);
        continue;
      }

      const locales = LOCALES.filter((l) =>
        fs.existsSync(path.join(lessonPath, `theory.${l}.mdx`)),
      );
      if (locales.length > 0) {
        const fields = locales
          .map(
            (l) =>
              `    ${l}: () => import("./lessons/${trackDir}/${lessonDir}/theory.${l}.mdx"),`,
          )
          .join("\n");
        theoryEntries.push(`  "${lessonDir}": {\n${fields}\n  },`);

        const tocFields = locales
          .map((l) => {
            const src = fs.readFileSync(
              path.join(lessonPath, `theory.${l}.mdx`),
              "utf8",
            );
            return `    ${l}: ${JSON.stringify(extractToc(src))},`;
          })
          .join("\n");
        tocEntries.push(`  "${lessonDir}": {\n${tocFields}\n  },`);
      }

      if (fs.existsSync(path.join(lessonPath, "references.ts"))) {
        referenceEntries.push(
          `  "${lessonDir}": () => import("./lessons/${trackDir}/${lessonDir}/references"),`,
        );
      }

      if (fs.existsSync(path.join(lessonPath, "demo.tsx"))) {
        demoEntries.push(
          `  "${lessonDir}": () => import("./lessons/${trackDir}/${lessonDir}/demo"),`,
        );
      }

      if (fs.existsSync(path.join(lessonPath, "exercises.ts"))) {
        exerciseEntries.push(
          `  "${lessonDir}": () => import("./lessons/${trackDir}/${lessonDir}/exercises"),`,
        );
      }
    }
  }
}

const body = `// AUTO-GENERATED by scripts/gen-lesson-registry.ts — DO NOT EDIT.
// Regenerate with: pnpm gen:registry
import type { ComponentType } from "react";
import type { LessonSlug } from "./slugs";
import type { Citation, Exercise, Locale } from "./types";

export type LessonModuleLoader = () => Promise<{ default: ComponentType }>;
export type ReferencesLoader = () => Promise<{ references: Citation[] }>;

export interface TocItem {
  id: string;
  text: string;
  depth: 2 | 3 | 4;
}

export const LESSON_REGISTRY: Partial<
  Record<LessonSlug, Partial<Record<Locale, LessonModuleLoader>>>
> = {
${theoryEntries.join("\n")}
};

export const REFERENCES_REGISTRY: Partial<
  Record<LessonSlug, ReferencesLoader>
> = {
${referenceEntries.join("\n")}
};

export const TOC_REGISTRY: Partial<
  Record<LessonSlug, Partial<Record<Locale, TocItem[]>>>
> = {
${tocEntries.join("\n")}
};

export const DEMO_REGISTRY: Partial<Record<LessonSlug, LessonModuleLoader>> = {
${demoEntries.join("\n")}
};

export type ExercisesLoader = () => Promise<{ exercises: Exercise[] }>;

export const EXERCISES_REGISTRY: Partial<
  Record<LessonSlug, ExercisesLoader>
> = {
${exerciseEntries.join("\n")}
};
`;

fs.writeFileSync(OUT, body, "utf8");
console.log(
  `lesson registry: ${theoryEntries.length} theory, ${referenceEntries.length} references, ${demoEntries.length} demos, ${exerciseEntries.length} exercises`,
);
for (const w of warnings) console.warn(`  ${w}`);
