import fs from "node:fs";
import path from "node:path";
import { LESSON_SLUGS } from "../content/slugs";

// Emits a typed slug×locale → dynamic-import map (decision D2).
// Only lessons whose MDX files exist on disk get an entry — grows with phases 7/9.

const LESSONS_DIR = path.join(process.cwd(), "content", "lessons");
const OUT = path.join(process.cwd(), "content", "lesson-registry.generated.ts");
const LOCALES = ["vi", "en"] as const;

const slugSet = new Set<string>(LESSON_SLUGS);
const entries: string[] = [];
const warnings: string[] = [];

if (fs.existsSync(LESSONS_DIR)) {
  for (const trackDir of fs.readdirSync(LESSONS_DIR).sort()) {
    const trackPath = path.join(LESSONS_DIR, trackDir);
    if (!fs.statSync(trackPath).isDirectory() || trackDir.startsWith("_")) {
      continue;
    }
    for (const lessonDir of fs.readdirSync(trackPath).sort()) {
      const lessonPath = path.join(trackPath, lessonDir);
      if (!fs.statSync(lessonPath).isDirectory()) continue;
      if (!slugSet.has(lessonDir)) {
        warnings.push(`skipped ${trackDir}/${lessonDir}: not in LESSON_SLUGS`);
        continue;
      }
      const locales = LOCALES.filter((l) =>
        fs.existsSync(path.join(lessonPath, `theory.${l}.mdx`)),
      );
      if (locales.length === 0) continue;
      const fields = locales
        .map(
          (l) =>
            `    ${l}: () => import("./lessons/${trackDir}/${lessonDir}/theory.${l}.mdx"),`,
        )
        .join("\n");
      entries.push(`  "${lessonDir}": {\n${fields}\n  },`);
    }
  }
}

const body = `// AUTO-GENERATED by scripts/gen-lesson-registry.ts — DO NOT EDIT.
// Regenerate with: pnpm gen:registry
import type { ComponentType } from "react";
import type { LessonSlug } from "./slugs";
import type { Locale } from "./types";

export type LessonModuleLoader = () => Promise<{ default: ComponentType }>;

export const LESSON_REGISTRY: Partial<
  Record<LessonSlug, Partial<Record<Locale, LessonModuleLoader>>>
> = {
${entries.join("\n")}
};
`;

fs.writeFileSync(OUT, body, "utf8");
console.log(`lesson registry: ${entries.length} entries written to ${OUT}`);
for (const w of warnings) console.warn(`  ${w}`);
