import fs from "node:fs";
import path from "node:path";
import {
  centerline,
  outlinePath,
  suckers,
  type TentacleSpec,
  type Vec,
} from "../video/src/mascot/tentacles";

// Bakes the video mascot's procedural tentacles into static SVG paths for the
// site. Trig output never reaches markup at render time, where server and
// client floats can differ and break hydration.
// Run: pnpm tsx scripts/gen-inko-poses.ts

const POSES = ["idle", "wave", "cheer", "think", "surprised", "sleep"] as const;
type Pose = (typeof POSES)[number];

// Same rig as video/src/mascot/Inko.tsx.
const FRONT_X = [-62, -22, 22, 62];
const BACK_X = [-84, -44, 44, 84];

function spec(x: number, front: boolean, i: number): TentacleSpec {
  const side = Math.sign(x);
  return {
    base: { x, y: front ? 40 : 30 },
    angle: Math.PI / 2 - (x / 70) * (front ? 0.55 : 0.95),
    length: front ? 150 : 128,
    curl: -side * (Math.abs(x) > 40 ? 1.7 : 0.9),
    phase: i * 1.37 + (front ? 0 : 0.6),
    width: front ? [32, 9] : [26, 8],
  };
}

const RIG = [
  ...BACK_X.map((x, i) => spec(x, false, i + 4)),
  ...FRONT_X.map((x, i) => spec(x, true, i)),
];

// Targets keyed by tentacle (0–3 back, 4–7 front), Inko-local.
function targets(pose: Pose): (Vec | undefined)[] {
  const t: (Vec | undefined)[] = Array(8).fill(undefined);
  if (pose === "wave") t[7] = { x: 150, y: -130 };
  if (pose === "cheer") {
    t[4] = { x: -150, y: -120 };
    t[7] = { x: 150, y: -120 };
  }
  if (pose === "think") t[4] = { x: -118, y: -52 };
  if (pose === "surprised") {
    [205, 225, 315, 335, 190, 245, 295, 350].forEach((deg, i) => {
      const a = (deg * Math.PI) / 180;
      t[i] = { x: Math.cos(a) * 200, y: Math.sin(a) * 170 + 110 };
    });
  }
  return t;
}

const snap = (n: number) => Math.round(n * 100) / 100;
// One decimal is invisible at any on-screen size and keeps the module small.
const trim = (d: string) =>
  d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10)).replace(/\s+/g, " ");

const out: Record<string, { back: string[]; front: string[]; suckers: number[][] }> = {};
let minX = -100;
let maxX = 100;
let minY = -110;
let maxY = 100;

for (const pose of POSES) {
  const aims = targets(pose);
  const amp = pose === "surprised" ? 0.12 : pose === "sleep" ? 0.08 : 0.28;
  const back: string[] = [];
  const front: string[] = [];
  const dots: number[][] = [];
  RIG.forEach((s, i) => {
    const pts = centerline(s, { time: 0.6, amp, target: aims[i], reach: aims[i] ? 1 : 0 });
    for (const p of pts) {
      minX = Math.min(minX, p.x - 18);
      maxX = Math.max(maxX, p.x + 18);
      minY = Math.min(minY, p.y - 18);
      maxY = Math.max(maxY, p.y + 18);
    }
    const d = trim(outlinePath(s, pts));
    if (i < 4) back.push(d);
    else {
      front.push(d);
      for (const c of suckers(s, pts)) dots.push([snap(c.x), snap(c.y), snap(c.r)]);
    }
  });
  out[pose] = { back, front, suckers: dots };
}

const viewBox = [minX, minY, maxX - minX, maxY - minY].map((n) => Math.round(n)).join(" ");
const file = path.join(process.cwd(), "components", "mascot", "inko-poses.generated.ts");
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(
  file,
  `// Generated by scripts/gen-inko-poses.ts — do not edit.\n\n` +
    `export const INKO_VIEWBOX = ${JSON.stringify(viewBox)};\n\n` +
    `export const INKO_POSES = ${JSON.stringify(out, null, 2)} as const;\n`,
);
console.log(`wrote ${path.relative(process.cwd(), file)} (viewBox ${viewBox})`);
