import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "math",
  order: 0,
  title: {
    vi: "Nền tảng Toán học cho đồ hoạ",
    en: "Math Foundations for Graphics",
  },
  summary: {
    vi: "Vector, ma trận, phép xoay, nội suy và không gian màu — toàn bộ ngôn ngữ toán mà mọi track sau đều nói.",
    en: "Vectors, matrices, rotation, interpolation and color spaces — the mathematical language every later track speaks.",
  },
  moduleIds: [
    "math-01-spaces-and-vectors",
    "math-02-matrices-and-transforms",
    "math-03-rotation-interpolation-color",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "math-01-spaces-and-vectors",
    trackId: "math",
    order: 1,
    title: { vi: "Không gian & Vector", en: "Spaces & Vectors" },
    lessonSlugs: [
      "cartesian-and-uv-space",
      "vector-basics",
      "dot-and-cross-products",
      "checkpoint-vector-clock",
    ],
  },
  {
    id: "math-02-matrices-and-transforms",
    trackId: "math",
    order: 2,
    title: { vi: "Ma trận & Transform", en: "Matrices & Transforms" },
    lessonSlugs: [
      "matrix-basics",
      "homogeneous-coordinates-4x4",
      "model-view-projection",
      "checkpoint-wireframe-cube",
    ],
  },
  {
    id: "math-03-rotation-interpolation-color",
    trackId: "math",
    order: 3,
    title: {
      vi: "Xoay, Nội suy & Màu",
      en: "Rotation, Interpolation & Color",
    },
    lessonSlugs: [
      "euler-angles-and-gimbal-lock",
      "quaternions",
      "trigonometry-for-animation",
      "interpolation-and-easing",
      "srgb-linear-and-gamma",
      "checkpoint-orbit-animation",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "cartesian-and-uv-space",
    trackId: "math",
    moduleId: "math-01-spaces-and-vectors",
    order: 1,
    title: {
      vi: "Toạ độ Descartes & UV space",
      en: "Cartesian Coordinates & UV Space",
    },
    summary: {
      vi: "Hệ toạ độ 2D/3D, quy ước trục, và vì sao UV chạy từ 0 đến 1 lại là nền của mọi texture và shader.",
      en: "2D/3D coordinate systems, axis conventions, and why the 0-to-1 UV range underpins every texture and shader.",
    },
    difficulty: 1,
    estimatedMinutes: 25,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: [],
    objectives: {
      vi: [
        "Đọc và vẽ được điểm trong hệ toạ độ 2D/3D, phân biệt quy ước trục Y-up/Z-up",
        "Giải thích UV space là gì và ánh xạ pixel ↔ UV bằng công thức",
        "Chuẩn hoá toạ độ màn hình về [0,1] và [-1,1]",
      ],
      en: [
        "Read and plot points in 2D/3D coordinates, distinguish Y-up/Z-up conventions",
        "Explain UV space and map pixel ↔ UV with an explicit formula",
        "Normalize screen coordinates into [0,1] and [-1,1]",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "vector-basics",
    trackId: "math",
    moduleId: "math-01-spaces-and-vectors",
    order: 2,
    title: { vi: "Vector cơ bản", en: "Vector Basics" },
    summary: {
      vi: "Cộng, trừ, nhân vô hướng và độ dài vector — hiểu bằng hình học trước, công thức sau.",
      en: "Addition, subtraction, scaling and length — understood geometrically first, algebraically second.",
    },
    difficulty: 1,
    estimatedMinutes: 30,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["cartesian-and-uv-space"],
    objectives: {
      vi: [
        "Thực hiện cộng/trừ/scale vector và chỉ ra ý nghĩa hình học của từng phép",
        "Tính độ dài vector và giải thích vì sao cần normalize",
        "Dùng vector biểu diễn vị trí, hướng và vận tốc",
      ],
      en: [
        "Perform vector add/subtract/scale and state each operation's geometric meaning",
        "Compute vector length and explain why normalization matters",
        "Use vectors to represent position, direction and velocity",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "dot-and-cross-products",
    trackId: "math",
    moduleId: "math-01-spaces-and-vectors",
    order: 3,
    title: { vi: "Dot, Cross & Normalize", en: "Dot, Cross & Normalize" },
    summary: {
      vi: "Hai phép nhân vector quan trọng nhất đồ hoạ: dot đo góc và chiếu, cross tạo pháp tuyến — kèm ý nghĩa hình học thật sự.",
      en: "The two vector products graphics lives on: dot measures angles and projections, cross builds normals — with their real geometric meaning.",
    },
    difficulty: 2,
    estimatedMinutes: 40,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["vector-basics"],
    objectives: {
      vi: [
        "Tính dot product và suy ra góc, phép chiếu, mặt hướng về đâu",
        "Tính cross product và dựng vector pháp tuyến cho một tam giác",
        "Nhận diện các pattern dot/cross xuất hiện trong lighting và culling",
      ],
      en: [
        "Compute dot products to derive angles, projections and facing direction",
        "Compute cross products and build a triangle's normal vector",
        "Recognize dot/cross patterns as they appear in lighting and culling",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-vector-clock",
    trackId: "math",
    moduleId: "math-01-spaces-and-vectors",
    order: 4,
    title: { vi: "Mini-build: Đồng hồ vector", en: "Mini-build: Vector Clock" },
    summary: {
      vi: "Vẽ một chiếc đồng hồ kim chạy thật trên canvas 2D chỉ bằng toán vector — không thư viện.",
      en: "Draw a working analog clock on a 2D canvas using nothing but vector math — no libraries.",
    },
    difficulty: 2,
    estimatedMinutes: 45,
    tags: ["math", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["dot-and-cross-products"],
    objectives: {
      vi: [
        "Tổng hợp toạ độ, vector và normalize vào một sản phẩm chạy được",
        "Tự đối chiếu kết quả với checklist thay vì xem đáp án ngay",
      ],
      en: [
        "Synthesize coordinates, vectors and normalization into a working artifact",
        "Self-verify against the checklist before reaching for the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "matrix-basics",
    trackId: "math",
    moduleId: "math-02-matrices-and-transforms",
    order: 5,
    title: { vi: "Ma trận 2x2 & 3x3", en: "Matrices 2x2 & 3x3" },
    summary: {
      vi: "Ma trận là máy biến đổi không gian: scale, rotate, shear — nhìn thấy được từng cột của ma trận làm gì.",
      en: "Matrices as space-transforming machines: scale, rotate, shear — seeing what each column actually does.",
    },
    difficulty: 2,
    estimatedMinutes: 40,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-vector-clock"],
    objectives: {
      vi: [
        "Nhân ma trận với vector và đọc ma trận theo cột (basis vectors)",
        "Dựng ma trận scale/rotate 2D từ đầu",
        "Giải thích vì sao thứ tự nhân ma trận quan trọng",
      ],
      en: [
        "Multiply matrices with vectors and read a matrix by its columns (basis vectors)",
        "Build 2D scale/rotate matrices from scratch",
        "Explain why matrix multiplication order matters",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "homogeneous-coordinates-4x4",
    trackId: "math",
    moduleId: "math-02-matrices-and-transforms",
    order: 6,
    title: {
      vi: "Toạ độ đồng nhất & ma trận 4x4",
      en: "Homogeneous Coordinates & 4x4 Matrices",
    },
    summary: {
      vi: "Vì sao đồ hoạ 3D dùng vector 4 chiều: gộp translation vào phép nhân ma trận và phân biệt điểm với hướng bằng w.",
      en: "Why 3D graphics uses 4D vectors: folding translation into matrix multiplication and separating points from directions with w.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["matrix-basics"],
    objectives: {
      vi: [
        "Giải thích vai trò của thành phần w và phép chia phối cảnh",
        "Dựng ma trận translate/rotate/scale 4x4 và compose chúng",
        "Phân biệt transform điểm và transform hướng (normal)",
      ],
      en: [
        "Explain the w component and the perspective divide",
        "Build and compose 4x4 translate/rotate/scale matrices",
        "Distinguish transforming points from transforming directions (normals)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "model-view-projection",
    trackId: "math",
    moduleId: "math-02-matrices-and-transforms",
    order: 7,
    title: { vi: "Model → View → Projection", en: "Model → View → Projection" },
    summary: {
      vi: "Chuỗi nhân ma trận đưa một đỉnh từ không gian model ra màn hình — pipeline mà mọi vertex shader đều chạy.",
      en: "The matrix chain that carries a vertex from model space to the screen — the pipeline every vertex shader runs.",
    },
    difficulty: 3,
    estimatedMinutes: 45,
    tags: ["math", "webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["homogeneous-coordinates-4x4"],
    objectives: {
      vi: [
        "Viết rõ chuỗi p_clip = P·V·M·p_model và vai trò từng ma trận",
        "Phân biệt world/view/clip/NDC/screen space",
        "Dựng ma trận lookAt và perspective ở mức công thức",
      ],
      en: [
        "Write out p_clip = P·V·M·p_model and each matrix's role",
        "Distinguish world/view/clip/NDC/screen space",
        "Construct lookAt and perspective matrices at the formula level",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-wireframe-cube",
    trackId: "math",
    moduleId: "math-02-matrices-and-transforms",
    order: 8,
    title: {
      vi: "Mini-build: Cube 3D tự chiếu",
      en: "Mini-build: Hand-projected 3D Cube",
    },
    summary: {
      vi: "Render một khối lập phương wireframe xoay trên canvas 2D bằng ma trận MVP tự viết — không WebGL, không thư viện.",
      en: "Render a spinning wireframe cube on a 2D canvas with your own MVP matrices — no WebGL, no libraries.",
    },
    difficulty: 3,
    estimatedMinutes: 60,
    tags: ["math", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["model-view-projection"],
    objectives: {
      vi: [
        "Tự tay thực hiện toàn bộ pipeline chiếu 3D → 2D",
        "Chứng minh hiểu MVP trước khi để WebGL làm hộ",
      ],
      en: [
        "Execute the full 3D → 2D projection pipeline by hand",
        "Prove the MVP chain is understood before WebGL does it for you",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "euler-angles-and-gimbal-lock",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 9,
    title: { vi: "Euler angles & gimbal lock", en: "Euler Angles & Gimbal Lock" },
    summary: {
      vi: "Xoay theo ba trục trực quan nhưng có bẫy: hiểu thứ tự trục và vì sao gimbal lock nuốt mất một bậc tự do.",
      en: "Three-axis rotation is intuitive but trapped: understand axis order and why gimbal lock eats a degree of freedom.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["math"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-wireframe-cube"],
    objectives: {
      vi: [
        "Áp dụng xoay Euler đúng thứ tự trục và dự đoán kết quả",
        "Tái tạo được tình huống gimbal lock và giải thích nguyên nhân",
        "Biết khi nào Euler là đủ và khi nào cần công cụ khác",
      ],
      en: [
        "Apply Euler rotations with correct axis order and predict the result",
        "Reproduce a gimbal lock situation and explain its cause",
        "Know when Euler is enough and when another tool is needed",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "quaternions",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 10,
    title: { vi: "Quaternion", en: "Quaternions" },
    summary: {
      vi: "Công cụ xoay không gimbal lock: dùng quaternion như hộp đen đúng cách, và mở hộp vừa đủ để không sợ nó.",
      en: "Rotation without gimbal lock: use quaternions correctly as a black box, and open the box just enough to stop fearing it.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["math"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["euler-angles-and-gimbal-lock"],
    objectives: {
      vi: [
        "Dựng quaternion từ trục + góc và áp dụng lên vector",
        "Giải thích vì sao slerp cho chuyển động xoay mượt",
        "Quyết định Euler vs quaternion cho từng tình huống thực tế",
      ],
      en: [
        "Build a quaternion from axis + angle and apply it to a vector",
        "Explain why slerp yields smooth rotational motion",
        "Decide Euler vs quaternion for concrete real-world cases",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "trigonometry-for-animation",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 11,
    title: {
      vi: "Lượng giác cho animation",
      en: "Trigonometry for Animation",
    },
    summary: {
      vi: "sin, cos và atan2 là ba hàm nuôi sống mọi chuyển động lặp: sóng, quỹ đạo tròn, xoay hướng theo chuột.",
      en: "sin, cos and atan2 power every cyclic motion: waves, circular orbits, pointing at the mouse.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["math", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["euler-angles-and-gimbal-lock"],
    objectives: {
      vi: [
        "Dùng sin/cos tạo dao động và chuyển động tròn có kiểm soát biên độ/tần số/pha",
        "Dùng atan2 tính góc hướng tới một điểm",
        "Kết hợp nhiều sóng sin để có chuyển động hữu cơ",
      ],
      en: [
        "Use sin/cos for oscillation and circular motion with amplitude/frequency/phase control",
        "Use atan2 to compute the angle toward a target",
        "Layer sine waves for organic-feeling motion",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "interpolation-and-easing",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 12,
    title: { vi: "Nội suy & easing", en: "Interpolation & Easing" },
    summary: {
      vi: "lerp, smoothstep và easing curve — cách mọi giá trị trong đồ hoạ đi từ A đến B một cách có chủ đích.",
      en: "lerp, smoothstep and easing curves — how every value in graphics travels from A to B on purpose.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["math", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["trigonometry-for-animation"],
    objectives: {
      vi: [
        "Viết lerp/inverse-lerp/remap và dùng chúng thành phản xạ",
        "Giải thích smoothstep bằng công thức và đồ thị",
        "Đọc-hiểu easing curve và chọn ease đúng cho từng chuyển động",
      ],
      en: [
        "Write lerp/inverse-lerp/remap until they are reflexes",
        "Explain smoothstep by formula and by graph",
        "Read easing curves and pick the right ease per motion",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "srgb-linear-and-gamma",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 13,
    title: { vi: "sRGB, linear & gamma", en: "sRGB, Linear & Gamma" },
    summary: {
      vi: "Vì sao màu cộng sai, sáng sai nếu trộn trong sRGB — và quy tắc vàng: tính toán trong linear, hiển thị qua gamma.",
      en: "Why colors add and light wrong when blended in sRGB — and the golden rule: compute in linear, display through gamma.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["math", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["interpolation-and-easing"],
    objectives: {
      vi: [
        "Phân biệt sRGB và linear, chuyển đổi qua lại bằng công thức",
        "Chỉ ra lỗi trộn màu/ánh sáng trong không gian sai",
        "Biết Three.js quản lý color space ở đâu (để dùng đúng từ Track 3)",
      ],
      en: [
        "Distinguish sRGB from linear and convert between them",
        "Spot blending/lighting bugs caused by the wrong color space",
        "Know where Three.js manages color spaces (used from Track 3 on)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-orbit-animation",
    trackId: "math",
    moduleId: "math-03-rotation-interpolation-color",
    order: 14,
    title: {
      vi: "Mini-build: Quỹ đạo & nhịp đập",
      en: "Mini-build: Orbits & Pulses",
    },
    summary: {
      vi: "Một cảnh canvas 2D: vật thể bay quỹ đạo, đường ngắm đuổi theo chuột bằng decay hàm mũ, màu nhấp nháy trộn trong linear — toàn bộ bằng toán của track này.",
      en: "A 2D canvas scene: bodies on orbits, an aim line chasing the mouse via exponential decay, colors pulsing in linear space — built entirely from this track's math.",
    },
    difficulty: 3,
    estimatedMinutes: 60,
    tags: ["math", "animation", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["srgb-linear-and-gamma"],
    objectives: {
      vi: [
        "Kết hợp lượng giác, nội suy và màu linear trong một cảnh động",
        "Hoàn thành track Toán với một sản phẩm nhìn được, chạy được",
      ],
      en: [
        "Combine trigonometry, interpolation and linear color in one animated scene",
        "Close the math track with something visible and running",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
