import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "webgl",
  order: 1,
  title: { vi: "WebGL Thuần", en: "Raw WebGL" },
  summary: {
    vi: "Nền móng không được bỏ qua: pipeline, buffer, shader và state machine của GPU — không thư viện nào che chắn.",
    en: "The non-skippable foundation: pipeline, buffers, shaders and the GPU state machine — with no library in the way.",
  },
  moduleIds: [
    "webgl-01-pipeline-and-context",
    "webgl-02-first-triangle",
    "webgl-03-gpu-state-and-memory",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "webgl-01-pipeline-and-context",
    trackId: "webgl",
    order: 1,
    title: { vi: "Pipeline & Context", en: "Pipeline & Context" },
    lessonSlugs: [
      "what-webgl-is-and-isnt",
      "rendering-pipeline-a-to-z",
      "canvas-context-and-dpr",
      "checkpoint-responsive-clear",
    ],
  },
  {
    id: "webgl-02-first-triangle",
    trackId: "webgl",
    order: 2,
    title: { vi: "Tam giác đầu tiên", en: "The First Triangle" },
    lessonSlugs: [
      "buffers-vbo-vao",
      "vertex-fragment-rasterization",
      "attributes-uniforms-varyings",
      "first-triangle-webgl2",
      "checkpoint-animated-quad",
    ],
  },
  {
    id: "webgl-03-gpu-state-and-memory",
    trackId: "webgl",
    order: 3,
    title: { vi: "GPU State & Memory", en: "GPU State & Memory" },
    lessonSlugs: [
      "textures-upload-and-sampling",
      "framebuffers-render-to-texture",
      "depth-buffer-and-z-fighting",
      "blending-and-alpha",
      "webgl-vs-webgpu-landscape",
      "checkpoint-render-to-texture-tint",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "what-webgl-is-and-isnt",
    trackId: "webgl",
    moduleId: "webgl-01-pipeline-and-context",
    order: 1,
    title: {
      vi: "WebGL là gì (và không là gì)",
      en: "What WebGL Is (and Isn't)",
    },
    summary: {
      vi: "WebGL là API rasterization cấp thấp bọc quanh OpenGL ES 2.0/3.0, chỉ vẽ tam giác và chạy shader — mọi khái niệm scene, ánh sáng, loader trong Three.js đều là lớp trừu tượng dựng thêm bên trên.",
      en: "WebGL is a low-level rasterization API wrapping OpenGL ES 2.0/3.0 that only draws triangles and runs shaders — every scene, light and loader concept in Three.js is an abstraction built on top of it.",
    },
    difficulty: 2,
    estimatedMinutes: 25,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-orbit-animation"],
    objectives: {
      vi: [
        "Vẽ được sơ đồ quan hệ WebGL → OpenGL ES → GPU driver và chỉ ra WebGL nằm ở lớp nào",
        "Liệt kê tối thiểu 5 thứ WebGL không cung cấp sẵn (scene graph, ánh sáng, loader model, vật lý, UI)",
        "Xác định tình huống nên viết WebGL thuần thay vì dùng Three.js",
      ],
      en: [
        "Diagram the WebGL → OpenGL ES → GPU driver relationship and place WebGL correctly in that stack",
        "List at least 5 things WebGL does not provide out of the box (scene graph, lighting, model loaders, physics, UI)",
        "Identify when raw WebGL is the right call instead of Three.js",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "rendering-pipeline-a-to-z",
    trackId: "webgl",
    moduleId: "webgl-01-pipeline-and-context",
    order: 2,
    title: {
      vi: "Rendering pipeline từ A đến Z",
      en: "The Rendering Pipeline, A to Z",
    },
    summary: {
      vi: "Theo dõi một vertex đi hết chặng đường: vertex specification → vertex shader → primitive assembly → clipping → rasterization → fragment shader → depth/stencil/blend → framebuffer — mỗi bước là một trạm cố định hoặc lập trình được.",
      en: "Trace a vertex through the full trip: vertex specification → vertex shader → primitive assembly → clipping → rasterization → fragment shader → depth/stencil/blend → framebuffer — each stage either fixed-function or programmable.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["what-webgl-is-and-isnt"],
    objectives: {
      vi: [
        "Vẽ sơ đồ pipeline đầy đủ và chỉ ra giai đoạn nào lập trình được (shader) và giai đoạn nào cố định",
        "Giải thích vì sao vertex shader chạy trước, fragment shader chạy sau, và dữ liệu được nội suy ra sao giữa hai giai đoạn",
        "Truy vết một lỗi hình ảnh cụ thể (ví dụ tam giác không hiện) về đúng giai đoạn pipeline gây ra nó",
      ],
      en: [
        "Diagram the full pipeline and mark which stages are programmable (shaders) versus fixed-function",
        "Explain why the vertex shader runs first, the fragment shader runs second, and how data is interpolated between them",
        "Trace a concrete rendering bug (e.g. a missing triangle) back to the exact pipeline stage responsible",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "canvas-context-and-dpr",
    trackId: "webgl",
    moduleId: "webgl-01-pipeline-and-context",
    order: 3,
    title: {
      vi: "Canvas, context & devicePixelRatio",
      en: "Canvas, Context & devicePixelRatio",
    },
    summary: {
      vi: "getContext('webgl2') chỉ là bước đầu: canvas có 2 kích thước độc lập (CSS size và drawing buffer size), và bỏ qua devicePixelRatio là nguyên nhân số 1 khiến hình ảnh bị mờ trên màn Retina.",
      en: "getContext('webgl2') is just step one: a canvas has two independent sizes (CSS size and drawing buffer size), and ignoring devicePixelRatio is the #1 cause of blurry rendering on Retina displays.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["rendering-pipeline-a-to-z"],
    objectives: {
      vi: [
        "Khởi tạo WebGL2 context đúng cách với các option quan trọng (antialias, alpha, powerPreference)",
        "Phân biệt canvas.width/height (drawing buffer) với canvas.style.width/height (CSS size) và đồng bộ chúng theo devicePixelRatio",
        "Viết hàm resize canvas chạy đúng khi kéo giãn cửa sổ hoặc đổi zoom trình duyệt",
      ],
      en: [
        "Initialize a WebGL2 context correctly with the options that matter (antialias, alpha, powerPreference)",
        "Distinguish canvas.width/height (drawing buffer) from canvas.style.width/height (CSS size) and sync them via devicePixelRatio",
        "Write a resize function that stays correct across window resizes and browser zoom changes",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-responsive-clear",
    trackId: "webgl",
    moduleId: "webgl-01-pipeline-and-context",
    order: 4,
    title: {
      vi: "Mini-build: Canvas full-screen tự resize",
      en: "Mini-build: Self-resizing Fullscreen Canvas",
    },
    summary: {
      vi: "Một canvas WebGL2 phủ kín màn hình, luôn nét ở mọi devicePixelRatio, đổi màu clear liên tục theo thời gian — nền tảng dùng lại cho mọi bài sau.",
      en: "A fullscreen WebGL2 canvas that stays crisp at any devicePixelRatio and cycles its clear color over time — the scaffold every later lesson reuses.",
    },
    difficulty: 2,
    estimatedMinutes: 45,
    tags: ["webgl", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["canvas-context-and-dpr"],
    objectives: {
      vi: [
        "Tổng hợp context setup và resize logic vào một component chạy được, không giật hình khi resize",
        "Tự đối chiếu kết quả với checklist DPR trước khi xem đáp án",
      ],
      en: [
        "Combine context setup and resize logic into a working component with no flicker on resize",
        "Self-verify against the DPR checklist before reaching for the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "buffers-vbo-vao",
    trackId: "webgl",
    moduleId: "webgl-02-first-triangle",
    order: 5,
    title: { vi: "Buffer: VBO & VAO", en: "Buffers: VBO & VAO" },
    summary: {
      vi: "Dữ liệu vertex phải sống trong bộ nhớ GPU trước khi shader đọc được: bufferData copy dữ liệu vào VBO, còn VAO ghi nhớ cách đọc dữ liệu đó — set 1 lần, bind lại là dùng được.",
      en: "Vertex data must live in GPU memory before a shader can read it: bufferData copies data into a VBO, while a VAO remembers how to read that data — set up once, then just bind and go.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-responsive-clear"],
    objectives: {
      vi: [
        "Tạo và nạp dữ liệu vào VBO bằng gl.bufferData với đúng usage hint (STATIC_DRAW/DYNAMIC_DRAW)",
        "Cấu hình VAO với vertexAttribPointer/enableVertexAttribArray và giải thích VAO lưu trạng thái gì",
        "Giải thích vì sao VAO giúp tránh lặp lại setup attribute mỗi frame",
      ],
      en: [
        "Create and upload data into a VBO with gl.bufferData using the correct usage hint (STATIC_DRAW/DYNAMIC_DRAW)",
        "Configure a VAO with vertexAttribPointer/enableVertexAttribArray and explain what state a VAO captures",
        "Explain why a VAO avoids re-running attribute setup every frame",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "vertex-fragment-rasterization",
    trackId: "webgl",
    moduleId: "webgl-02-first-triangle",
    order: 6,
    title: {
      vi: "Vertex shader, fragment shader & rasterization",
      en: "Vertex Shader, Fragment Shader & Rasterization",
    },
    summary: {
      vi: "Vertex shader trả về gl_Position trong clip space cho từng đỉnh; rasterizer biến tam giác thành fragment; fragment shader chạy độc lập cho mỗi fragment và trả về màu — hiểu rõ biên giới trách nhiệm giữa 3 giai đoạn này.",
      en: "The vertex shader returns gl_Position in clip space per vertex; the rasterizer turns triangles into fragments; the fragment shader runs independently per fragment and outputs a color — know exactly where each stage's responsibility begins and ends.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["webgl", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["buffers-vbo-vao"],
    objectives: {
      vi: [
        "Viết vertex shader tối giản xuất gl_Position đúng clip space",
        "Viết fragment shader tối giản xuất màu cố định qua gl_FragColor",
        "Giải thích rasterization quyết định fragment nào được tạo ra từ một tam giác như thế nào",
      ],
      en: [
        "Write a minimal vertex shader that outputs gl_Position correctly in clip space",
        "Write a minimal fragment shader that outputs a fixed color via gl_FragColor",
        "Explain how rasterization decides which fragments a triangle generates",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "attributes-uniforms-varyings",
    trackId: "webgl",
    moduleId: "webgl-02-first-triangle",
    order: 7,
    title: {
      vi: "Attribute, uniform & varying",
      en: "Attributes, Uniforms & Varyings",
    },
    summary: {
      vi: "Ba loại biến, ba vòng đời khác nhau: attribute đổi theo từng vertex, uniform cố định cho cả draw call, varying được nội suy tuyến tính từ vertex shader sang fragment shader.",
      en: "Three variable kinds, three different lifetimes: attributes vary per vertex, uniforms stay constant for a whole draw call, varyings get linearly interpolated from the vertex shader to the fragment shader.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["webgl", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["vertex-fragment-rasterization"],
    objectives: {
      vi: [
        "Phân biệt attribute/uniform/varying theo nơi khai báo, tần suất đổi giá trị và giai đoạn shader dùng",
        "Truyền uniform từ JavaScript vào shader bằng gl.uniform* và getUniformLocation",
        "Dùng varying để truyền màu hoặc UV từ vertex shader sang fragment shader và quan sát nội suy",
      ],
      en: [
        "Distinguish attribute/uniform/varying by declaration scope, update frequency and which shader stage uses them",
        "Pass a uniform from JavaScript into a shader using gl.uniform* and getUniformLocation",
        "Use a varying to pass color or UV from the vertex to the fragment shader and observe the interpolation",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "first-triangle-webgl2",
    trackId: "webgl",
    moduleId: "webgl-02-first-triangle",
    order: 8,
    title: {
      vi: "Tam giác đầu tiên bằng WebGL2 thuần",
      en: "Your First Triangle in Raw WebGL2",
    },
    summary: {
      vi: "Ghép toàn bộ mảnh ghép — context, shader compile/link, VBO/VAO, draw call — thành một tam giác thật sự lên màn hình, không qua bất kỳ thư viện nào.",
      en: "Wire every piece together — context, shader compile/link, VBO/VAO, draw call — into an actual triangle on screen, with zero libraries in between.",
    },
    difficulty: 2,
    estimatedMinutes: 40,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["attributes-uniforms-varyings"],
    objectives: {
      vi: [
        "Compile và link một shader program hoàn chỉnh, đọc đúng log lỗi khi compile/link thất bại",
        "Gọi gl.drawArrays với đúng mode và count để vẽ ra tam giác",
        "Tự debug khi màn hình chỉ có màu clear mà không thấy tam giác (checklist các nguyên nhân thường gặp)",
      ],
      en: [
        "Compile and link a full shader program, and correctly read compile/link error logs on failure",
        "Call gl.drawArrays with the right mode and count to draw the triangle",
        "Debug a blank canvas with only the clear color showing (checklist of the usual suspects)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-animated-quad",
    trackId: "webgl",
    moduleId: "webgl-02-first-triangle",
    order: 9,
    title: {
      vi: "Mini-build: Quad động 2 tam giác",
      en: "Mini-build: Animated Two-Triangle Quad",
    },
    summary: {
      vi: "Một quad dựng từ 2 tam giác, mỗi vertex một màu riêng, biến dạng theo thời gian nhờ uniform — chứng minh toàn bộ chuỗi buffer → attribute → uniform hoạt động cùng nhau.",
      en: "A quad built from 2 triangles, per-vertex color, deforming over time through a uniform — proof that the whole buffer → attribute → uniform chain works together.",
    },
    difficulty: 2,
    estimatedMinutes: 50,
    tags: ["webgl", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["first-triangle-webgl2"],
    objectives: {
      vi: [
        "Dựng geometry 2 tam giác từ 4 đỉnh không lặp dữ liệu thừa (index hoặc thứ tự đỉnh hợp lý)",
        "Điều khiển animation hoàn toàn qua uniform thời gian, không đụng lại buffer mỗi frame",
      ],
      en: [
        "Build 2-triangle geometry from 4 vertices without duplicating vertex data unnecessarily",
        "Drive the animation entirely through a time uniform, without touching the buffer every frame",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "textures-upload-and-sampling",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 10,
    title: {
      vi: "Texture: upload & sampling",
      en: "Textures: Upload & Sampling",
    },
    summary: {
      vi: "texImage2D đưa pixel vào GPU; texParameteri quyết định wrap mode và filter; mipmap giảm alias khi texture bị thu nhỏ — ba quyết định này ảnh hưởng trực tiếp đến chất lượng hình ảnh.",
      en: "texImage2D uploads pixels to the GPU; texParameteri decides wrap mode and filtering; mipmaps cut aliasing when a texture is minified — these three decisions directly shape visual quality.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-animated-quad"],
    objectives: {
      vi: [
        "Upload một ảnh lên GPU bằng texImage2D và bind đúng texture unit cho sampler",
        "Cấu hình wrap mode (REPEAT/CLAMP_TO_EDGE) và filter (NEAREST/LINEAR) và giải thích khác biệt hình ảnh",
        "Sinh mipmap và giải thích vì sao nó giảm alias khi texture nhỏ lại trên màn hình",
      ],
      en: [
        "Upload an image to the GPU via texImage2D and bind it to the correct texture unit for a sampler",
        "Configure wrap mode (REPEAT/CLAMP_TO_EDGE) and filtering (NEAREST/LINEAR) and explain the visual difference",
        "Generate mipmaps and explain why they reduce aliasing when a texture is minified on screen",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "framebuffers-render-to-texture",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 11,
    title: {
      vi: "Framebuffer & render-to-texture",
      en: "Framebuffers & Render-to-Texture",
    },
    summary: {
      vi: "Framebuffer object cho phép vẽ vào một texture thay vì màn hình — nền tảng của mọi post-processing, shadow map và render-to-texture pattern sau này.",
      en: "A framebuffer object lets you render into a texture instead of the screen — the foundation every post-processing effect, shadow map and render-to-texture pattern builds on.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["textures-upload-and-sampling"],
    objectives: {
      vi: [
        "Tạo FBO, gắn texture làm color attachment và kiểm tra framebuffer complete",
        "Render một scene vào FBO rồi dùng kết quả đó làm texture đầu vào cho pass tiếp theo",
        "Giải thích vì sao cần renderbuffer cho depth khi không cần đọc lại depth sau đó",
      ],
      en: [
        "Create an FBO, attach a texture as its color attachment, and check for framebuffer completeness",
        "Render a scene into an FBO and feed the result as an input texture to a later pass",
        "Explain when a renderbuffer is enough for depth versus needing a depth texture",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "depth-buffer-and-z-fighting",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 12,
    title: {
      vi: "Depth buffer & z-fighting",
      en: "Depth Buffer & Z-Fighting",
    },
    summary: {
      vi: "Depth buffer lưu độ sâu không tuyến tính (do phép chiếu phối cảnh) — hiểu đúng phân bố này giải thích vì sao z-fighting hay xảy ra ở xa và cách né nó bằng near/far hợp lý hoặc polygon offset.",
      en: "The depth buffer stores non-linear depth (a side effect of the perspective projection) — understanding that distribution explains why z-fighting shows up at a distance and how to avoid it with sane near/far planes or polygon offset.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["framebuffers-render-to-texture"],
    objectives: {
      vi: [
        "Bật/tắt gl.DEPTH_TEST và giải thích depth function (LESS, LEQUAL...) ảnh hưởng gì đến thứ tự vẽ",
        "Giải thích vì sao độ chính xác depth buffer giảm mạnh khi ra xa camera (do 1/z không tuyến tính)",
        "Tái tạo z-fighting có chủ đích rồi sửa bằng cách thu hẹp tỉ lệ far/near hoặc dùng polygon offset",
      ],
      en: [
        "Toggle gl.DEPTH_TEST and explain how the depth function (LESS, LEQUAL...) affects draw order",
        "Explain why depth buffer precision drops sharply with distance from the camera (non-linear 1/z)",
        "Deliberately reproduce z-fighting, then fix it by tightening the far/near ratio or using polygon offset",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "blending-and-alpha",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 13,
    title: { vi: "Blending & alpha", en: "Blending & Alpha" },
    summary: {
      vi: "Blending trộn màu fragment mới với màu đã có trong framebuffer theo công thức src*srcFactor + dst*dstFactor — sai thứ tự vẽ hay sai blend factor là nguồn lỗi trong suốt phổ biến nhất.",
      en: "Blending mixes an incoming fragment's color with what's already in the framebuffer using src*srcFactor + dst*dstFactor — wrong draw order or the wrong blend factors are the most common source of transparency bugs.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["webgl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["depth-buffer-and-z-fighting"],
    objectives: {
      vi: [
        "Bật gl.BLEND và cấu hình blendFunc cho alpha blending tiêu chuẩn (SRC_ALPHA, ONE_MINUS_SRC_ALPHA)",
        "Giải thích vì sao vật thể trong suốt phải vẽ sau vật thể đặc và sắp theo thứ tự xa-gần",
        "Nhận diện lỗi hình ảnh gây ra bởi bật depth write khi vẽ đối tượng trong suốt",
      ],
      en: [
        "Enable gl.BLEND and configure blendFunc for standard alpha blending (SRC_ALPHA, ONE_MINUS_SRC_ALPHA)",
        "Explain why transparent objects must be drawn after opaque ones, sorted back-to-front",
        "Spot the visual bug caused by leaving depth write on while drawing transparent objects",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "webgl-vs-webgpu-landscape",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 14,
    title: {
      vi: "WebGL1 vs WebGL2 vs WebGPU",
      en: "WebGL1 vs WebGL2 vs WebGPU",
    },
    summary: {
      vi: "WebGL2 thêm transform feedback, MRT và integer texture so với WebGL1; WebGPU thay đổi mô hình sang command buffer + compute shader tường minh — bối cảnh để biết học gì tiếp sau track này.",
      en: "WebGL2 adds transform feedback, MRT and integer textures over WebGL1; WebGPU shifts the model entirely to explicit command buffers and compute shaders — the context for what comes after this track.",
    },
    difficulty: 2,
    estimatedMinutes: 25,
    tags: ["webgl", "tooling"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["blending-and-alpha"],
    objectives: {
      vi: [
        "Liệt kê 3 khác biệt kỹ thuật chính giữa WebGL1 và WebGL2 đã dùng trong track này",
        "Giải thích khác biệt mô hình lập trình giữa WebGL (state machine) và WebGPU (command buffer tường minh)",
        "Đánh giá tình trạng hỗ trợ trình duyệt của WebGPU tại thời điểm học để quyết định có đầu tư ngay không",
      ],
      en: [
        "List 3 key technical differences between WebGL1 and WebGL2 already used in this track",
        "Explain the programming-model gap between WebGL's state machine and WebGPU's explicit command buffers",
        "Assess WebGPU's current browser support to decide whether to invest in it now",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-render-to-texture-tint",
    trackId: "webgl",
    moduleId: "webgl-03-gpu-state-and-memory",
    order: 15,
    title: {
      vi: "Mini-build: Render-to-texture & tint pass",
      en: "Mini-build: Render-to-Texture & Tint Pass",
    },
    summary: {
      vi: "Vẽ scene vào một FBO, sau đó dùng texture kết quả làm đầu vào cho pass thứ hai áp một tint màu toàn màn hình — post-processing đơn giản nhất, đóng track WebGL thuần.",
      en: "Render a scene into an FBO, then feed the resulting texture into a second pass that applies a full-screen color tint — the simplest post-processing pipeline, closing out the raw WebGL track.",
    },
    difficulty: 3,
    estimatedMinutes: 55,
    tags: ["webgl", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["blending-and-alpha"],
    objectives: {
      vi: [
        "Kết hợp FBO, texture sampling và blending vào một pipeline 2 pass hoàn chỉnh",
        "Hoàn thành track WebGL với hiểu biết đủ để đọc code Three.js dựng render target ở Track 3",
      ],
      en: [
        "Combine FBOs, texture sampling and blending into a complete 2-pass pipeline",
        "Close the WebGL track with enough grounding to read Three.js's render-target code in Track 3",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
