import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "threejs",
  order: 3,
  title: { vi: "Three.js Core", en: "Three.js Core" },
  summary: {
    vi: "Three.js thuần không React: scene graph, material, ánh sáng, loader và đọc source để hiểu thư viện làm gì hộ bạn.",
    en: "Vanilla Three.js, no React: scene graph, materials, lights, loaders — and reading the source to see what it does for you.",
  },
  moduleIds: [
    "threejs-01-scene-fundamentals",
    "threejs-02-light-texture-assets",
    "threejs-03-motion-and-interaction",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "threejs-01-scene-fundamentals",
    trackId: "threejs",
    order: 1,
    title: { vi: "Scene căn bản", en: "Scene Fundamentals" },
    lessonSlugs: [
      "scene-camera-renderer",
      "geometries-and-buffergeometry",
      "materials-from-basic-to-physical",
      "checkpoint-primitive-still-life",
    ],
  },
  {
    id: "threejs-02-light-texture-assets",
    trackId: "threejs",
    order: 2,
    title: {
      vi: "Ánh sáng, Texture & Asset",
      en: "Lights, Textures & Assets",
    },
    lessonSlugs: [
      "lights-and-shadow-maps",
      "textures-and-compression-ktx2",
      "loading-gltf-draco-meshopt",
      "checkpoint-gltf-viewer",
    ],
  },
  {
    id: "threejs-03-motion-and-interaction",
    trackId: "threejs",
    order: 3,
    title: { vi: "Chuyển động & Tương tác", en: "Motion & Interaction" },
    lessonSlugs: [
      "animation-mixer-and-clips",
      "raycasting-and-picking",
      "cameras-and-controls",
      "scene-graph-and-transforms",
      "reading-threejs-source",
      "checkpoint-interactive-showroom",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "scene-camera-renderer",
    trackId: "threejs",
    moduleId: "threejs-01-scene-fundamentals",
    order: 1,
    title: { vi: "Scene, Camera & Renderer", en: "Scene, Camera & Renderer" },
    summary: {
      vi: "Ba lớp bắt buộc của mọi ứng dụng Three.js: Scene chứa object, Camera định nghĩa view/projection, Renderer gọi WebGL vẽ ra canvas — hiểu đúng vòng lặp render() trước khi thêm bất cứ thứ gì khác.",
      en: "The three mandatory pieces of every Three.js app: a Scene holding objects, a Camera defining view/projection, and a Renderer that calls WebGL to draw the canvas — understand the render() loop before adding anything else.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-pattern-tile-poster"],
    objectives: {
      vi: [
        "Khởi tạo Scene, PerspectiveCamera và WebGLRenderer, và giải thích tham số fov/aspect/near/far ảnh hưởng gì",
        "Viết render loop bằng requestAnimationFrame và giải thích vì sao Three.js không tự động lặp",
        "Ánh xạ khái niệm Scene/Camera/Renderer về đúng giai đoạn pipeline WebGL đã học ở Track 1",
      ],
      en: [
        "Initialize a Scene, PerspectiveCamera and WebGLRenderer, and explain what fov/aspect/near/far each control",
        "Write a render loop with requestAnimationFrame and explain why Three.js doesn't loop on its own",
        "Map the Scene/Camera/Renderer concepts back onto the WebGL pipeline stages from Track 1",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "geometries-and-buffergeometry",
    trackId: "threejs",
    moduleId: "threejs-01-scene-fundamentals",
    order: 2,
    title: {
      vi: "Geometry & BufferGeometry",
      en: "Geometries & BufferGeometry",
    },
    summary: {
      vi: "Mọi geometry built-in của Three.js (BoxGeometry, SphereGeometry...) chỉ là BufferGeometry được điền sẵn attribute — dựng BufferGeometry tay để hiểu chính xác position/normal/uv nằm ở đâu.",
      en: "Every built-in Three.js geometry (BoxGeometry, SphereGeometry...) is just a BufferGeometry pre-filled with attributes — build one by hand to see exactly where position/normal/uv data lives.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["scene-camera-renderer"],
    objectives: {
      vi: [
        "Dùng geometry built-in phổ biến và đọc đúng tham số segment ảnh hưởng đến độ mịn",
        "Tự tạo BufferGeometry từ mảng position/normal/uv thô và gán vào Mesh",
        "Giải thích quan hệ giữa BufferGeometry của Three.js và VBO/attribute đã học ở Track 1",
      ],
      en: [
        "Use common built-in geometries and correctly read how segment parameters affect smoothness",
        "Build a BufferGeometry by hand from raw position/normal/uv arrays and assign it to a Mesh",
        "Explain the relationship between Three.js's BufferGeometry and the VBO/attribute concepts from Track 1",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "materials-from-basic-to-physical",
    trackId: "threejs",
    moduleId: "threejs-01-scene-fundamentals",
    order: 3,
    title: {
      vi: "Material: từ Basic đến Physical",
      en: "Materials: From Basic to Physical",
    },
    summary: {
      vi: "MeshBasicMaterial không quan tâm ánh sáng, MeshLambertMaterial/MeshPhongMaterial dùng mô hình lighting cũ, MeshStandardMaterial/MeshPhysicalMaterial theo chuẩn PBR metalness/roughness — chọn đúng material quyết định 80% độ chân thực trước khi chỉnh sáng.",
      en: "MeshBasicMaterial ignores lighting entirely, MeshLambertMaterial/MeshPhongMaterial use older lighting models, MeshStandardMaterial/MeshPhysicalMaterial follow the PBR metalness/roughness standard — picking the right material decides 80% of realism before any light is touched.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["threejs", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["geometries-and-buffergeometry"],
    objectives: {
      vi: [
        "So sánh Basic/Lambert/Phong/Standard/Physical theo mô hình lighting và chi phí render",
        "Cấu hình metalness/roughness trên MeshStandardMaterial và dự đoán kết quả hình ảnh",
        "Chọn material phù hợp cho một tình huống cụ thể (UI overlay không cần sáng vs vật thể PBR thật)",
      ],
      en: [
        "Compare Basic/Lambert/Phong/Standard/Physical by lighting model and render cost",
        "Configure metalness/roughness on MeshStandardMaterial and predict the visual result",
        "Pick the right material for a concrete case (an unlit UI overlay versus a realistic PBR object)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-primitive-still-life",
    trackId: "threejs",
    moduleId: "threejs-01-scene-fundamentals",
    order: 4,
    title: {
      vi: "Mini-build: Tĩnh vật từ hình khối cơ bản",
      en: "Mini-build: Still Life from Primitives",
    },
    summary: {
      vi: "Một cảnh tĩnh vật dựng từ các geometry built-in với nhiều loại material khác nhau, có ánh sáng cơ bản — tổng hợp scene/camera/geometry/material thành một bố cục hoàn chỉnh.",
      en: "A still-life scene built from built-in geometries across several material types, lit with basic lighting — a synthesis of scene/camera/geometry/material into one complete composition.",
    },
    difficulty: 3,
    estimatedMinutes: 50,
    tags: ["threejs", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["materials-from-basic-to-physical"],
    objectives: {
      vi: [
        "Bố cục một cảnh nhiều object với vị trí/scale/rotation hợp lý và ít nhất 2 loại material",
        "Tự đối chiếu bố cục và ánh sáng với checklist trước khi xem đáp án",
      ],
      en: [
        "Compose a multi-object scene with sensible position/scale/rotation and at least 2 material types",
        "Self-verify composition and lighting against the checklist before checking the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "lights-and-shadow-maps",
    trackId: "threejs",
    moduleId: "threejs-02-light-texture-assets",
    order: 5,
    title: { vi: "Ánh sáng & shadow map", en: "Lights & Shadow Maps" },
    summary: {
      vi: "DirectionalLight/PointLight/SpotLight quyết định vật thể sáng thế nào, còn shadow map là một render pass phụ vẽ depth từ góc nhìn ánh sáng — bias sai là nguyên nhân số 1 của shadow acne và peter-panning.",
      en: "DirectionalLight/PointLight/SpotLight decide how objects are lit, while a shadow map is a secondary render pass that captures depth from the light's point of view — the wrong bias is the #1 cause of shadow acne and peter-panning.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-primitive-still-life"],
    objectives: {
      vi: [
        "Cấu hình DirectionalLight, PointLight và SpotLight và giải thích khác biệt về cách chúng phát sáng",
        "Bật shadow map trên renderer và light, cấu hình shadow.mapSize và shadow camera frustum",
        "Chẩn đoán và sửa shadow acne / peter-panning bằng shadow.bias hoặc normalBias",
      ],
      en: [
        "Configure DirectionalLight, PointLight and SpotLight and explain how they emit light differently",
        "Enable shadow maps on the renderer and light, and configure shadow.mapSize and the shadow camera frustum",
        "Diagnose and fix shadow acne / peter-panning using shadow.bias or normalBias",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "textures-and-compression-ktx2",
    trackId: "threejs",
    moduleId: "threejs-02-light-texture-assets",
    order: 6,
    title: {
      vi: "Texture & nén KTX2",
      en: "Textures & KTX2 Compression",
    },
    summary: {
      vi: "TextureLoader nạp ảnh thô tốn VRAM và băng thông giải nén; KTX2Loader nạp texture đã nén GPU-native (Basis Universal) — giữ chất lượng gần tương đương nhưng giảm mạnh dung lượng VRAM và thời gian tải.",
      en: "TextureLoader loads raw images that cost VRAM and decode bandwidth; KTX2Loader loads GPU-native compressed textures (Basis Universal) — keeping near-equivalent quality while sharply cutting VRAM footprint and load time.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["threejs", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["lights-and-shadow-maps"],
    objectives: {
      vi: [
        "Nạp texture bằng TextureLoader và cấu hình đúng colorSpace cho texture màu (SRGBColorSpace)",
        "Nạp texture nén bằng KTX2Loader và giải thích vì sao nó nhẹ VRAM hơn ảnh thô đã giải nén",
        "Quyết định khi nào cần KTX2 (asset lớn, mobile) và khi nào TextureLoader thường là đủ",
      ],
      en: [
        "Load a texture with TextureLoader and set the correct colorSpace for color textures (SRGBColorSpace)",
        "Load a compressed texture with KTX2Loader and explain why it's lighter on VRAM than a decoded raw image",
        "Decide when KTX2 is worth it (large assets, mobile) versus when TextureLoader alone is enough",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "loading-gltf-draco-meshopt",
    trackId: "threejs",
    moduleId: "threejs-02-light-texture-assets",
    order: 7,
    title: {
      vi: "Load GLTF với Draco & meshopt",
      en: "Loading GLTF with Draco & meshopt",
    },
    summary: {
      vi: "GLTFLoader đọc scene graph, material và animation từ file .gltf/.glb; DRACOLoader và meshopt decoder giải nén geometry đã nén ở bước build, đánh đổi một round-trip decode CPU để giảm mạnh kích thước file tải về.",
      en: "GLTFLoader reads the scene graph, materials and animations from a .gltf/.glb file; the DRACOLoader and meshopt decoder decompress geometry that was compressed at build time, trading a CPU decode round-trip for a much smaller download.",
    },
    difficulty: 2,
    estimatedMinutes: 40,
    tags: ["threejs", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["textures-and-compression-ktx2"],
    objectives: {
      vi: [
        "Nạp một file GLTF hoàn chỉnh và duyệt scene graph kết quả để tìm mesh/material cụ thể",
        "Cấu hình DRACOLoader và giải thích vì sao cần trỏ đúng đường dẫn decoder",
        "So sánh kích thước file và thời gian nạp giữa GLTF nén và không nén",
      ],
      en: [
        "Load a complete GLTF file and traverse the resulting scene graph to find a specific mesh/material",
        "Configure DRACOLoader and explain why pointing it to the correct decoder path matters",
        "Compare file size and load time between compressed and uncompressed GLTF",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-gltf-viewer",
    trackId: "threejs",
    moduleId: "threejs-02-light-texture-assets",
    order: 8,
    title: { vi: "Mini-build: GLTF Viewer", en: "Mini-build: GLTF Viewer" },
    summary: {
      vi: "Một trình xem model GLTF hoàn chỉnh: environment lighting, shadow map, texture nén — tổng hợp toàn bộ module ánh sáng/texture/asset thành một công cụ dùng lại được.",
      en: "A complete GLTF viewer: environment lighting, shadow maps, compressed textures — a synthesis of the lighting/texture/asset module into a reusable tool.",
    },
    difficulty: 3,
    estimatedMinutes: 55,
    tags: ["threejs", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["loading-gltf-draco-meshopt"],
    objectives: {
      vi: [
        "Ghép GLTFLoader, DRACOLoader, shadow map và environment lighting vào một viewer hoàn chỉnh",
        "Tự kiểm tra chất lượng hình ảnh (bóng đổ đúng, texture đúng color space) bằng checklist",
      ],
      en: [
        "Combine GLTFLoader, DRACOLoader, shadow maps and environment lighting into a complete viewer",
        "Self-check visual quality (correct shadows, correct texture color space) against a checklist",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "animation-mixer-and-clips",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 9,
    title: { vi: "AnimationMixer & clip", en: "AnimationMixer & Clips" },
    summary: {
      vi: "AnimationClip mô tả keyframe cho một hoặc nhiều thuộc tính; AnimationMixer là runtime phát clip đó lên object, quản lý AnimationAction, weight và crossfade giữa nhiều animation.",
      en: "An AnimationClip describes keyframes for one or more properties; the AnimationMixer is the runtime that plays that clip on an object, managing AnimationActions, weights and crossfades between animations.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["threejs", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-gltf-viewer"],
    objectives: {
      vi: [
        "Nạp clip từ GLTF, tạo AnimationMixer và phát một AnimationAction",
        "Gọi mixer.update(delta) đúng vị trí trong render loop và giải thích vì sao thiếu bước này animation đứng im",
        "Crossfade mượt giữa 2 animation clip (vd idle → walk) bằng weight",
      ],
      en: [
        "Load a clip from GLTF, create an AnimationMixer and play an AnimationAction",
        "Call mixer.update(delta) in the right place in the render loop and explain why skipping it freezes the animation",
        "Crossfade smoothly between 2 animation clips (e.g. idle → walk) using weights",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "raycasting-and-picking",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 10,
    title: { vi: "Raycasting & picking", en: "Raycasting & Picking" },
    summary: {
      vi: "Raycaster bắn một tia từ camera qua toạ độ chuột đã chuẩn hoá NDC, tìm giao điểm gần nhất với các object trong scene — cơ chế đứng sau mọi click/hover 3D.",
      en: "A Raycaster fires a ray from the camera through the mouse position normalized to NDC, finding the nearest intersection with scene objects — the mechanism behind every 3D click or hover.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["animation-mixer-and-clips"],
    objectives: {
      vi: [
        "Chuyển toạ độ chuột màn hình sang NDC [-1,1] đúng công thức trước khi truyền vào Raycaster",
        "Dùng raycaster.intersectObjects để tìm object bị click/hover và đọc đúng thứ tự kết quả (gần nhất trước)",
        "Tối ưu raycasting khi scene có nhiều object (giới hạn danh sách object cần kiểm tra)",
      ],
      en: [
        "Convert screen mouse coordinates to NDC [-1,1] with the correct formula before passing them to the Raycaster",
        "Use raycaster.intersectObjects to find the clicked/hovered object and read results in the correct order (nearest first)",
        "Optimize raycasting in a scene with many objects (restrict the list of objects actually tested)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "cameras-and-controls",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 11,
    title: { vi: "Camera & controls", en: "Cameras & Controls" },
    summary: {
      vi: "PerspectiveCamera và OrthographicCamera phục vụ hai use case khác hẳn nhau; OrbitControls/TrackballControls quản lý input người dùng và ghi thẳng lên camera.position/quaternion mỗi frame — hiểu rõ để tránh xung đột khi tự điều khiển camera bằng code.",
      en: "PerspectiveCamera and OrthographicCamera serve very different use cases; OrbitControls/TrackballControls manage user input and write directly to camera.position/quaternion every frame — understand this to avoid fighting them when driving the camera programmatically.",
    },
    difficulty: 2,
    estimatedMinutes: 30,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["raycasting-and-picking"],
    objectives: {
      vi: [
        "Chọn Perspective hay Orthographic camera đúng cho một use case cụ thể (game 3D vs blueprint 2.5D)",
        "Cấu hình OrbitControls và giải thích nó cập nhật camera ở đâu trong lifecycle",
        "Tránh xung đột khi vừa dùng OrbitControls vừa animate camera bằng code (damping, target sync)",
      ],
      en: [
        "Choose Perspective versus Orthographic camera correctly for a concrete use case (3D game vs 2.5D blueprint)",
        "Configure OrbitControls and explain where it updates the camera in the lifecycle",
        "Avoid conflicts when both OrbitControls and code-driven animation touch the camera (damping, target sync)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "scene-graph-and-transforms",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 12,
    title: {
      vi: "Scene graph & transform hierarchy",
      en: "Scene Graph & Transform Hierarchy",
    },
    summary: {
      vi: "Mỗi Object3D có transform cục bộ (local) và matrixWorld được tính bằng cách nhân dồn transform của toàn bộ tổ tiên — add một object vào object khác thay đổi hệ quy chiếu của nó ngay lập tức.",
      en: "Every Object3D has a local transform and a matrixWorld computed by chaining the transforms of every ancestor — adding an object as a child of another instantly changes its frame of reference.",
    },
    difficulty: 2,
    estimatedMinutes: 35,
    tags: ["threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["cameras-and-controls"],
    objectives: {
      vi: [
        "Xây dựng một hierarchy cha-con bằng object3D.add() và dự đoán đúng vị trí world của object con",
        "Giải thích quan hệ giữa matrix, matrixWorld và matrixAutoUpdate",
        "Chuyển đổi một điểm giữa local space và world space bằng localToWorld/worldToLocal",
      ],
      en: [
        "Build a parent-child hierarchy with object3D.add() and correctly predict the child's world position",
        "Explain the relationship between matrix, matrixWorld and matrixAutoUpdate",
        "Convert a point between local space and world space using localToWorld/worldToLocal",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "reading-threejs-source",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 13,
    title: {
      vi: "Đọc source Three.js: WebGLRenderer & Object3D",
      en: "Reading Three.js Source: WebGLRenderer & Object3D",
    },
    summary: {
      vi: "Đọc thẳng source WebGLRenderer.render() và Object3D.updateMatrixWorld() để thấy chính xác Three.js gọi WebGL API nào và tính transform ra sao — dừng đoán, bắt đầu biết.",
      en: "Read the actual source of WebGLRenderer.render() and Object3D.updateMatrixWorld() to see precisely which WebGL calls Three.js issues and how it computes transforms — stop guessing, start knowing.",
    },
    difficulty: 3,
    estimatedMinutes: 45,
    tags: ["threejs", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["scene-graph-and-transforms"],
    objectives: {
      vi: [
        "Truy vết render() từ lúc gọi đến lúc gl.drawElements/drawArrays thực sự chạy",
        "Đọc updateMatrixWorld() và chỉ ra đúng thứ tự nhân matrix cha-con",
        "Tìm được vị trí trong source nơi Three.js quản lý state WebGL (chương trình shader, texture unit) để tránh set trùng",
      ],
      en: [
        "Trace render() from the call site down to the actual gl.drawElements/drawArrays call",
        "Read updateMatrixWorld() and identify the correct parent-child matrix multiplication order",
        "Locate where in the source Three.js manages WebGL state (shader programs, texture units) to avoid redundant sets",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-interactive-showroom",
    trackId: "threejs",
    moduleId: "threejs-03-motion-and-interaction",
    order: 14,
    title: {
      vi: "Mini-build: Showroom tương tác",
      en: "Mini-build: Interactive Showroom",
    },
    summary: {
      vi: "Một showroom 3D với model GLTF có animation, click để chọn object bằng raycasting, camera điều khiển bằng OrbitControls — bài tổng kết toàn bộ Track 3 trước khi chuyển sang R3F.",
      en: "A 3D showroom with an animated GLTF model, click-to-select via raycasting, and an OrbitControls-driven camera — the capstone of Track 3 before moving on to R3F.",
    },
    difficulty: 3,
    estimatedMinutes: 60,
    tags: ["threejs", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["reading-threejs-source"],
    objectives: {
      vi: [
        "Kết hợp GLTF, AnimationMixer, raycasting và controls vào một scene tương tác hoàn chỉnh",
        "Đóng track Three.js thuần với một sản phẩm sẽ được dựng lại bằng R3F ở track kế tiếp",
      ],
      en: [
        "Combine GLTF, AnimationMixer, raycasting and controls into one complete interactive scene",
        "Close the vanilla Three.js track with a build that gets rebuilt in R3F in the next track",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
