import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "r3f",
  order: 4,
  title: { vi: "React Three Fiber", en: "React Three Fiber" },
  summary: {
    vi: "Reconciler chứ không phải wrapper: vòng đời, disposal, drei và cách compose cảnh 3D bằng tư duy React.",
    en: "A reconciler, not a wrapper: lifecycle, disposal, drei and composing 3D scenes the React way.",
  },
  moduleIds: [
    "r3f-01-mental-model",
    "r3f-02-lifecycle-and-drei",
    "r3f-03-composition-and-tooling",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "r3f-01-mental-model",
    trackId: "r3f",
    order: 1,
    title: { vi: "Mental model", en: "The Mental Model" },
    lessonSlugs: [
      "why-r3f-reconciler",
      "jsx-to-three-mapping",
      "r3f-core-hooks",
      "checkpoint-scene-rebuild-r3f",
    ],
  },
  {
    id: "r3f-02-lifecycle-and-drei",
    trackId: "r3f",
    order: 2,
    title: { vi: "Vòng đời & drei", en: "Lifecycle & drei" },
    lessonSlugs: [
      "disposal-and-memory-leaks",
      "drei-essentials",
      "memoizing-geometry-and-materials",
      "suspense-and-asset-loading",
      "checkpoint-asset-gallery",
    ],
  },
  {
    id: "r3f-03-composition-and-tooling",
    trackId: "r3f",
    order: 3,
    title: { vi: "Composition & Tooling", en: "Composition & Tooling" },
    lessonSlugs: [
      "portals-views-multi-canvas",
      "leva-debug-ui",
      "r3f-vs-vanilla-three",
      "checkpoint-mini-configurator",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "why-r3f-reconciler",
    trackId: "r3f",
    moduleId: "r3f-01-mental-model",
    order: 1,
    title: {
      vi: "Vì sao R3F tồn tại: reconciler, không phải wrapper",
      en: "Why R3F Exists: A Reconciler, Not a Wrapper",
    },
    summary: {
      vi: "React Three Fiber không bọc API Three.js bằng hàm JS — nó là một React reconciler tuỳ biến (giống react-dom nhưng target là scene graph Three.js), nên mọi component JSX thực chất đang tạo và gắn object Three.js thật.",
      en: "React Three Fiber doesn't wrap the Three.js API in JS functions — it's a custom React reconciler (like react-dom, but targeting the Three.js scene graph), so every JSX component is actually creating and attaching a real Three.js object.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-interactive-showroom"],
    objectives: {
      vi: [
        "Giải thích khác biệt giữa 'wrapper' (gọi hàm hộ) và 'reconciler' (quản lý cây object thật) bằng ví dụ cụ thể",
        "Chỉ ra tên custom element trong JSX của R3F ánh xạ 1-1 sang class Three.js nào",
        "Dự đoán R3F sẽ tạo/huỷ object Three.js nào khi một component mount/unmount",
      ],
      en: [
        "Explain the difference between a 'wrapper' (calling functions on your behalf) and a 'reconciler' (managing a real object tree) with a concrete example",
        "Show how an R3F JSX element name maps 1-to-1 to a Three.js class",
        "Predict which Three.js objects R3F creates or destroys when a component mounts or unmounts",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "jsx-to-three-mapping",
    trackId: "r3f",
    moduleId: "r3f-01-mental-model",
    order: 2,
    title: { vi: "JSX ↔ Three.js mapping", en: "JSX ↔ Three.js Mapping" },
    summary: {
      vi: "`<mesh>`, `<boxGeometry>`, `<meshStandardMaterial>` là tên class Three.js viết thường; prop trên JSX ánh xạ trực tiếp vào constructor argument hoặc property gán sau khi khởi tạo — không có khái niệm prop 'ảo' nào khác.",
      en: "<mesh>, <boxGeometry>, <meshStandardMaterial> are Three.js class names lowercased; JSX props map directly to constructor arguments or properties assigned after instantiation — there's no separate 'virtual prop' concept.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["why-r3f-reconciler"],
    objectives: {
      vi: [
        "Ánh xạ đúng tên JSX element về class Three.js tương ứng (mesh → THREE.Mesh, boxGeometry → THREE.BoxGeometry)",
        "Phân biệt prop truyền vào constructor (args) với prop gán sau bằng property assignment",
        "Dùng cú pháp dấu chấm (vd position-x) để gán sâu vào một property con",
      ],
      en: [
        "Map JSX element names to the correct Three.js class (mesh → THREE.Mesh, boxGeometry → THREE.BoxGeometry)",
        "Distinguish props passed as constructor args from props assigned afterward as properties",
        "Use dot-notation props (e.g. position-x) to assign deep into a nested property",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "r3f-core-hooks",
    trackId: "r3f",
    moduleId: "r3f-01-mental-model",
    order: 3,
    title: {
      vi: "Hook cốt lõi: useFrame, useThree, useLoader",
      en: "Core Hooks: useFrame, useThree, useLoader",
    },
    summary: {
      vi: "useFrame đăng ký một callback chạy mỗi frame trong render loop nội bộ của R3F, useThree đọc state của canvas (camera, gl, scene), useLoader nạp asset và tự cache kết quả theo URL — ba hook thay thế toàn bộ boilerplate render loop/loader viết tay ở Track 3.",
      en: "useFrame registers a callback that runs every frame inside R3F's internal render loop, useThree reads canvas state (camera, gl, scene), and useLoader loads assets while automatically caching results by URL — three hooks replacing all the render-loop and loader boilerplate hand-written in Track 3.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["r3f"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["jsx-to-three-mapping"],
    objectives: {
      vi: [
        "Dùng useFrame để animate một mesh và giải thích tham số delta nhận được",
        "Đọc camera/gl/scene hiện tại bằng useThree thay vì truyền prop thủ công",
        "Nạp một asset (texture hoặc GLTF) bằng useLoader và giải thích cơ chế cache theo URL",
      ],
      en: [
        "Use useFrame to animate a mesh and explain the delta parameter it receives",
        "Read the current camera/gl/scene with useThree instead of manually threading props",
        "Load an asset (texture or GLTF) with useLoader and explain its URL-based caching mechanism",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-scene-rebuild-r3f",
    trackId: "r3f",
    moduleId: "r3f-01-mental-model",
    order: 4,
    title: {
      vi: "Mini-build: Dựng lại showroom bằng R3F",
      en: "Mini-build: Rebuilding the Showroom in R3F",
    },
    summary: {
      vi: "Dựng lại chính xác showroom tương tác của Track 3 nhưng bằng JSX và hook của R3F — cách tốt nhất để thấy R3F tiết kiệm bao nhiêu boilerplate so với Three.js thuần.",
      en: "Rebuild the exact interactive showroom from Track 3, but with R3F's JSX and hooks — the best way to see just how much boilerplate R3F removes compared to vanilla Three.js.",
    },
    difficulty: 3,
    estimatedMinutes: 50,
    tags: ["r3f", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["r3f-core-hooks"],
    objectives: {
      vi: [
        "Chuyển đổi scene/camera/model/controls từ imperative Three.js sang JSX declarative của R3F",
        "Đối chiếu kết quả với showroom Track 3 để xác nhận hành vi giống hệt",
      ],
      en: [
        "Port scene/camera/model/controls from imperative Three.js to R3F's declarative JSX",
        "Compare the result against the Track 3 showroom to confirm identical behavior",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "disposal-and-memory-leaks",
    trackId: "r3f",
    moduleId: "r3f-02-lifecycle-and-drei",
    order: 5,
    title: { vi: "Disposal & memory leak", en: "Disposal & Memory Leaks" },
    summary: {
      vi: "R3F tự dispose geometry/material khi component unmount trong đa số trường hợp, nhưng texture nạp thủ công, event listener và object tạo ngoài JSX vẫn phải tự giải phóng — dùng chung hook `useDisposable` của nền tảng này để không quên.",
      en: "R3F auto-disposes geometries/materials on unmount in most cases, but manually loaded textures, event listeners and objects created outside JSX still need explicit cleanup — this platform's shared useDisposable hook exists so you never forget.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["r3f", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-scene-rebuild-r3f"],
    objectives: {
      vi: [
        "Xác định trường hợp nào R3F tự dispose và trường hợp nào bạn phải tự gọi .dispose()",
        "Dùng hook `useDisposable` để đăng ký cleanup tự động khi component unmount",
        "Phát hiện memory leak bằng cách theo dõi performance.memory sau khi mount/unmount lặp lại nhiều lần",
      ],
      en: [
        "Identify which cases R3F auto-disposes and which require calling .dispose() yourself",
        "Use the useDisposable hook to register automatic cleanup on unmount",
        "Detect a memory leak by watching performance.memory across repeated mount/unmount cycles",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "drei-essentials",
    trackId: "r3f",
    moduleId: "r3f-02-lifecycle-and-drei",
    order: 6,
    title: { vi: "drei essentials", en: "drei Essentials" },
    summary: {
      vi: "drei là bộ helper component cho R3F: OrbitControls, Environment, useTexture, Html, shaderMaterial — mỗi cái thay thế hàng chục dòng boilerplate, nhưng cần biết chúng làm gì bên dưới để không dùng sai.",
      en: "drei is R3F's helper component library: OrbitControls, Environment, useTexture, Html, shaderMaterial — each one replaces dozens of lines of boilerplate, but knowing what happens underneath prevents misuse.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["disposal-and-memory-leaks"],
    objectives: {
      vi: [
        "Dùng OrbitControls, Environment và useTexture từ drei thay cho code Three.js thuần",
        "Nhúng DOM thật vào scene 3D bằng component Html và giải thích cơ chế positioning của nó",
        "Đọc source một helper drei đơn giản để biết nó thực sự bọc quanh API Three.js nào",
      ],
      en: [
        "Use OrbitControls, Environment and useTexture from drei instead of hand-written Three.js code",
        "Embed real DOM into a 3D scene with the Html component and explain its positioning mechanism",
        "Read the source of a simple drei helper to see which Three.js API it actually wraps",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "memoizing-geometry-and-materials",
    trackId: "r3f",
    moduleId: "r3f-02-lifecycle-and-drei",
    order: 7,
    title: {
      vi: "Memoize geometry & material",
      en: "Memoizing Geometry & Materials",
    },
    summary: {
      vi: "Khai báo `<boxGeometry />` trực tiếp trong JSX tạo lại object mới ở mỗi re-render nếu không cẩn thận — useMemo giữ geometry/material ổn định qua các lần render, tránh GC churn và mất animation state.",
      en: "Declaring <boxGeometry /> directly in JSX can recreate a new object on every re-render if you're not careful — useMemo keeps geometry/material stable across renders, avoiding GC churn and lost animation state.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["drei-essentials"],
    objectives: {
      vi: [
        "Nhận diện tình huống JSX tạo lại geometry/material không cần thiết mỗi lần cha re-render",
        "Dùng useMemo để memo hoá geometry/material với dependency array đúng",
        "Đo tác động hiệu năng của việc thiếu memo hoá trên một scene có nhiều object",
      ],
      en: [
        "Recognize when JSX unnecessarily recreates a geometry/material on every parent re-render",
        "Use useMemo to memoize geometry/material with the correct dependency array",
        "Measure the performance impact of missing memoization in a scene with many objects",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "suspense-and-asset-loading",
    trackId: "r3f",
    moduleId: "r3f-02-lifecycle-and-drei",
    order: 8,
    title: { vi: "Suspense & load asset", en: "Suspense & Asset Loading" },
    summary: {
      vi: "useLoader/useTexture của R3F throw một Promise để tích hợp với React Suspense — bọc scene trong `<Suspense fallback>` cho phép hiện loading state chuẩn React thay vì tự quản lý biến isLoading.",
      en: "R3F's useLoader/useTexture throw a Promise to integrate with React Suspense — wrapping a scene in <Suspense fallback> gives you a standard React loading state instead of hand-rolling an isLoading variable.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["memoizing-geometry-and-materials"],
    objectives: {
      vi: [
        "Giải thích cơ chế Suspense hoạt động qua throw Promise và vì sao useLoader tận dụng được nó",
        "Bọc scene 3D trong Suspense với fallback hợp lý (skeleton hoặc placeholder)",
        "Xử lý lỗi load asset bằng Error Boundary kết hợp với Suspense",
      ],
      en: [
        "Explain how Suspense works via a thrown Promise and why useLoader can leverage it",
        "Wrap a 3D scene in Suspense with a sensible fallback (skeleton or placeholder)",
        "Handle asset loading errors with an Error Boundary paired with Suspense",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-asset-gallery",
    trackId: "r3f",
    moduleId: "r3f-02-lifecycle-and-drei",
    order: 9,
    title: { vi: "Mini-build: Asset gallery", en: "Mini-build: Asset Gallery" },
    summary: {
      vi: "Một gallery load nhiều model GLTF khác nhau qua Suspense, dispose đúng khi chuyển giữa các model — tổng hợp lifecycle, drei và memoization thành một trải nghiệm mượt không leak.",
      en: "A gallery loading several different GLTF models through Suspense, disposing correctly when switching between them — a synthesis of lifecycle, drei and memoization into a smooth, leak-free experience.",
    },
    difficulty: 3,
    estimatedMinutes: 55,
    tags: ["r3f", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["suspense-and-asset-loading"],
    objectives: {
      vi: [
        "Kết hợp Suspense, useDisposable và drei helper vào một luồng chuyển đổi asset mượt mà",
        "Xác nhận không leak bằng cách theo dõi performance.memory khi chuyển qua lại nhiều model",
      ],
      en: [
        "Combine Suspense, useDisposable and drei helpers into a smooth asset-switching flow",
        "Confirm there's no leak by watching performance.memory while switching between models repeatedly",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "portals-views-multi-canvas",
    trackId: "r3f",
    moduleId: "r3f-03-composition-and-tooling",
    order: 10,
    title: {
      vi: "Portal, View & multi-canvas",
      en: "Portals, Views & Multi-Canvas",
    },
    summary: {
      vi: "createPortal cho phép một phần scene render vào target khác trong cùng canvas; component View của drei còn đi xa hơn — nhiều 'khung nhìn' HTML dùng chung một canvas WebGL duy nhất, giảm chi phí GPU context.",
      en: "createPortal lets part of a scene render into a different target within the same canvas; drei's View component goes further — multiple HTML 'viewports' sharing a single underlying WebGL canvas, cutting GPU context overhead.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["r3f", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-asset-gallery"],
    objectives: {
      vi: [
        "Dùng createPortal để render một phần scene vào một scene target khác",
        "Cấu hình View của drei để nhiều vùng trên trang chia sẻ một canvas WebGL duy nhất",
        "Giải thích vì sao dùng nhiều `<Canvas>` riêng biệt tốn tài nguyên hơn multi-view trên một canvas",
      ],
      en: [
        "Use createPortal to render part of a scene into a different target scene",
        "Configure drei's View so multiple regions of a page share a single WebGL canvas",
        "Explain why multiple separate <Canvas> elements cost more resources than multi-view on one canvas",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "leva-debug-ui",
    trackId: "r3f",
    moduleId: "r3f-03-composition-and-tooling",
    order: 11,
    title: { vi: "Leva debug UI", en: "Leva Debug UI" },
    summary: {
      vi: "Leva sinh panel điều khiển tham số real-time từ một object config khai báo — thay cho việc gõ lại giá trị trong code mỗi lần muốn tinh chỉnh một uniform hay vị trí ánh sáng.",
      en: "Leva generates a real-time parameter control panel from a declarative config object — no more editing code every time you want to tweak a uniform or a light position.",
    },
    difficulty: 3,
    estimatedMinutes: 25,
    tags: ["r3f", "tooling"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["portals-views-multi-canvas"],
    objectives: {
      vi: [
        "Khai báo control bằng useControls và bind kết quả vào prop của component 3D",
        "Nhóm control liên quan bằng folder để panel không rối khi scene lớn",
        "Quyết định khi nào nên dùng Leva (dev/tuning) và khi nào không nên ship nó vào production",
      ],
      en: [
        "Declare controls with useControls and bind the results to a 3D component's props",
        "Group related controls into folders so the panel stays organized as a scene grows",
        "Decide when Leva earns its keep (dev/tuning) and when it shouldn't ship to production",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "r3f-vs-vanilla-three",
    trackId: "r3f",
    moduleId: "r3f-03-composition-and-tooling",
    order: 12,
    title: {
      vi: "R3F vs Three.js thuần: khi nào dùng cái nào",
      en: "R3F vs Vanilla Three.js: When to Use Which",
    },
    summary: {
      vi: "R3F thắng ở khả năng compose theo tư duy React và tích hợp state/UI, nhưng trả giá bằng một lớp reconciliation phía trên Three.js — với scene cực lớn hoặc cần kiểm soát render loop tuyệt đối, Three.js thuần vẫn là lựa chọn đúng.",
      en: "R3F wins on React-style composability and UI/state integration, but pays for it with a reconciliation layer on top of Three.js — for very large scenes or when you need absolute control over the render loop, vanilla Three.js is still the right call.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["r3f", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["portals-views-multi-canvas"],
    objectives: {
      vi: [
        "Liệt kê chi phí thực sự của reconciliation layer R3F thêm vào so với Three.js thuần",
        "Chỉ ra 2 tình huống cụ thể nên chọn Three.js thuần thay vì R3F",
        "Đánh giá trade-off cho chính dự án của bản thân dựa trên các tiêu chí đã học",
      ],
      en: [
        "List the real cost R3F's reconciliation layer adds compared to vanilla Three.js",
        "Identify 2 concrete situations where vanilla Three.js beats R3F",
        "Evaluate the trade-off for your own project using the criteria covered here",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-mini-configurator",
    trackId: "r3f",
    moduleId: "r3f-03-composition-and-tooling",
    order: 13,
    title: {
      vi: "Mini-build: Product configurator nhỏ",
      en: "Mini-build: Mini Product Configurator",
    },
    summary: {
      vi: "Một configurator sản phẩm nhỏ: state React điều khiển màu/vật liệu từng bộ phận, turntable, giá hiển thị theo lựa chọn — bài tổng kết đóng track R3F bằng một sản phẩm gần với thực tế production.",
      en: "A small product configurator: React state drives per-part colors/materials, a turntable, and a live price readout — the R3F track's capstone, close to a real production build.",
    },
    difficulty: 3,
    estimatedMinutes: 60,
    tags: ["r3f", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["r3f-vs-vanilla-three"],
    objectives: {
      vi: [
        "Dùng state React điều khiển scene: màu/finish từng bộ phận, turntable và giá theo lựa chọn",
        "Áp dụng memoization (geometry dùng chung), OrbitControls có clamp, shadows và disposal sạch",
        "Đóng track R3F với một configurator có thể mở rộng thành dự án thực tế",
      ],
      en: [
        "Drive the scene from React state: per-part colors/finish, a turntable and an options-based price",
        "Apply memoization (shared geometry), clamped OrbitControls, shadows and clean disposal",
        "Close the R3F track with a configurator that could grow into a real project",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
