import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "gsap",
  order: 5,
  title: { vi: "GSAP & Animation Nâng cao", en: "GSAP & Advanced Animation" },
  summary: {
    vi: "Timeline, ScrollTrigger và nguyên tắc animation — cộng bài học ai cũng làm sai: đồng bộ GSAP với render loop của R3F.",
    en: "Timelines, ScrollTrigger and animation principles — plus the lesson everyone gets wrong: syncing GSAP with R3F's render loop.",
  },
  moduleIds: [
    "gsap-01-core-animation",
    "gsap-02-scroll-and-gesture",
    "gsap-03-animation-craft",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "gsap-01-core-animation",
    trackId: "gsap",
    order: 1,
    title: { vi: "Animation lõi", en: "Core Animation" },
    lessonSlugs: [
      "tweens-timelines-stagger",
      "easing-in-depth",
      "checkpoint-hero-intro-sequence",
    ],
  },
  {
    id: "gsap-02-scroll-and-gesture",
    trackId: "gsap",
    order: 2,
    title: { vi: "Scroll & Cử chỉ", en: "Scroll & Gesture" },
    lessonSlugs: [
      "scrolltrigger-fundamentals",
      "scrolltrigger-plus-r3f-single-loop",
      "observer-and-draggable",
      "flip-layout-transitions",
      "splittext-typography",
      "checkpoint-scroll-section",
    ],
  },
  {
    id: "gsap-03-animation-craft",
    trackId: "gsap",
    order: 3,
    title: { vi: "Nghề animation", en: "The Craft of Animation" },
    lessonSlugs: [
      "choosing-your-animation-tool",
      "animation-principles-for-ui",
      "compositor-friendly-animation",
      "checkpoint-scrollytelling-page",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "tweens-timelines-stagger",
    trackId: "gsap",
    moduleId: "gsap-01-core-animation",
    order: 1,
    title: { vi: "Tween, Timeline & Stagger", en: "Tweens, Timelines & Stagger" },
    summary: {
      vi: "Đơn vị nhỏ nhất của GSAP là tween; timeline sắp xếp nhiều tween theo thời gian tương đối; stagger nhân bản độ trễ trên một tập phần tử.",
      en: "GSAP's smallest unit is the tween; a timeline sequences many tweens on relative time; stagger fans out delay across a set of elements.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["gsap", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-mini-configurator"],
    objectives: {
      vi: [
        "Viết tween với duration/ease/delay và điều khiển play/pause/reverse",
        "Xây timeline dùng position parameter thay vì delay cộng dồn thủ công",
        "Dùng stagger (số, object, hàm) để tạo hiệu ứng theo thứ tự trên nhiều phần tử",
      ],
      en: [
        "Write tweens with duration/ease/delay and control play/pause/reverse",
        "Build a timeline using position parameters instead of manually stacked delays",
        "Use stagger (number, object, function) to sequence effects across many elements",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "easing-in-depth",
    trackId: "gsap",
    moduleId: "gsap-01-core-animation",
    order: 2,
    title: { vi: "Easing chuyên sâu", en: "Easing in Depth" },
    summary: {
      vi: "Ease không phải trang trí — nó là cảm giác chuyển động. Đọc đường cong bezier, viết custom ease, và chọn ease theo ý đồ chứ không theo thói quen.",
      en: "Easing isn't decoration — it is the feel of motion. Read bezier curves, write custom eases, and pick one by intent rather than habit.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["tweens-timelines-stagger"],
    objectives: {
      vi: [
        "Đọc đồ thị ease (power, elastic, back, bounce) và dự đoán cảm giác chuyển động",
        "Viết custom ease bằng CustomEase từ điểm bezier",
        "Chọn ease phù hợp cho từng ngữ cảnh UI (entrance, exit, feedback)",
      ],
      en: [
        "Read ease graphs (power, elastic, back, bounce) and predict how the motion feels",
        "Write a custom ease with CustomEase from bezier points",
        "Pick the right ease for a given UI context (entrance, exit, feedback)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-hero-intro-sequence",
    trackId: "gsap",
    moduleId: "gsap-01-core-animation",
    order: 3,
    title: {
      vi: "Mini-build: Chuỗi intro hero",
      en: "Mini-build: Hero Intro Sequence",
    },
    summary: {
      vi: "Dàn dựng một timeline intro nhiều phần tử cho hero section: thứ tự, độ trễ và ease phối hợp nhau như một đạo diễn thật sự làm.",
      en: "Choreograph a multi-element intro timeline for a hero section: sequencing, delay and ease working together like a real director's cut.",
    },
    difficulty: 3,
    estimatedMinutes: 50,
    tags: ["gsap", "animation", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["easing-in-depth"],
    objectives: {
      vi: [
        "Kết hợp timeline, stagger và ease tuỳ biến trong một chuỗi animation hoàn chỉnh",
        "Tự đối chiếu nhịp độ animation với checklist trước khi xem đáp án",
      ],
      en: [
        "Combine timelines, stagger and custom easing into one complete animation sequence",
        "Self-verify animation pacing against the checklist before reaching for the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "scrolltrigger-fundamentals",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 4,
    title: { vi: "ScrollTrigger cơ bản", en: "ScrollTrigger Fundamentals" },
    summary: {
      vi: "scrub, pin và snap là ba trục điều khiển ScrollTrigger — hiểu chúng tách biệt trước khi kết hợp thành hiệu ứng phức tạp.",
      en: "scrub, pin and snap are ScrollTrigger's three control axes — understand them separately before combining into complex effects.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["gsap", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-hero-intro-sequence"],
    objectives: {
      vi: [
        "Cấu hình start/end/scrub và đọc marker debug để chỉnh trigger point",
        "Ghim (pin) một section và giải thích cách ScrollTrigger tạo khoảng trống layout",
        "Dùng snap để chuyển đoạn cuộn thành các bước rời rạc",
      ],
      en: [
        "Configure start/end/scrub and read debug markers to tune trigger points",
        "Pin a section and explain how ScrollTrigger creates layout spacing for it",
        "Use snap to turn a scroll range into discrete steps",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "scrolltrigger-plus-r3f-single-loop",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 5,
    title: {
      vi: "ScrollTrigger + R3F: một render loop duy nhất",
      en: "ScrollTrigger + R3F: One Render Loop",
    },
    summary: {
      vi: "Điểm ai cũng làm sai: để GSAP và useFrame tự chạy loop riêng gây giật hình. Quy tắc đúng — một loop duy nhất điều khiển, loop kia chỉ đọc giá trị.",
      en: "The lesson everyone gets wrong: letting GSAP and useFrame each drive their own loop causes visual stutter. The rule — one loop drives, the other only reads values.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["gsap", "r3f", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["scrolltrigger-fundamentals"],
    objectives: {
      vi: [
        "Giải thích vì sao hai render loop độc lập (RAF của GSAP và của R3F) đánh nhau",
        "Đăng ký gsap.ticker để GSAP điều khiển loop, hoặc để useFrame đọc giá trị đã tween",
        "Đồng bộ progress của ScrollTrigger vào state đọc được trong useFrame mà không tạo loop thứ hai",
      ],
      en: [
        "Explain why two independent render loops (GSAP's RAF and R3F's) fight each other",
        "Register gsap.ticker so GSAP drives the loop, or let useFrame read already-tweened values",
        "Sync ScrollTrigger progress into state readable inside useFrame without spawning a second loop",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "observer-and-draggable",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 6,
    title: { vi: "Observer & Draggable", en: "Observer & Draggable" },
    summary: {
      vi: "Observer chuẩn hoá wheel/touch/pointer thành sự kiện thống nhất; Draggable biến bất kỳ phần tử nào thành đối tượng kéo-thả có quán tính.",
      en: "Observer normalizes wheel/touch/pointer into one unified event; Draggable turns any element into a drag target with inertia.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["scrolltrigger-plus-r3f-single-loop"],
    objectives: {
      vi: [
        "Dùng Observer để bắt sự kiện wheel/touch/pointer thống nhất cho custom scroll",
        "Cấu hình Draggable với bounds, inertia và snap",
        "Chọn Observer/Draggable so với xử lý event thủ công khi nào phù hợp",
      ],
      en: [
        "Use Observer to capture unified wheel/touch/pointer events for custom scroll",
        "Configure Draggable with bounds, inertia and snap",
        "Decide when Observer/Draggable beats hand-rolled event handling",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "flip-layout-transitions",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 7,
    title: { vi: "FLIP cho chuyển layout", en: "FLIP Layout Transitions" },
    summary: {
      vi: "Plugin Flip ghi trạng thái trước/sau của layout rồi nội suy ngược lại — cách animate thay đổi DOM mà không cần biết trước toạ độ đích.",
      en: "The Flip plugin records layout state before/after and interpolates backward — how to animate DOM changes without knowing the destination coordinates in advance.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["gsap", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["observer-and-draggable"],
    objectives: {
      vi: [
        "Giải thích nguyên lý First-Last-Invert-Play của Flip",
        "Dùng Flip.getState/Flip.from để animate một phần tử đổi vị trí trong DOM",
        "Nhận diện tình huống Flip phù hợp hơn tween thủ công (reorder, resize, reparent)",
      ],
      en: [
        "Explain the First-Last-Invert-Play principle behind Flip",
        "Use Flip.getState/Flip.from to animate an element that changes position in the DOM",
        "Recognize when Flip beats a manual tween (reorder, resize, reparent)",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "splittext-typography",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 8,
    title: { vi: "SplitText cho Typography", en: "SplitText for Typography" },
    summary: {
      vi: "Tách văn bản thành char/word/line để animate từng đơn vị riêng — kèm cạm bẫy về accessibility và reflow khi resize.",
      en: "Splitting text into chars/words/lines to animate each unit independently — with the accessibility and resize-reflow traps that come with it.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap", "animation"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["flip-layout-transitions"],
    objectives: {
      vi: [
        "Tách text bằng SplitText và stagger animation theo char/word/line",
        "Xử lý lại split khi resize hoặc đổi font để tránh vỡ layout",
        "Giữ nội dung dễ tiếp cận cho screen reader khi text bị tách nhỏ",
      ],
      en: [
        "Split text with SplitText and stagger animation by char/word/line",
        "Re-split on resize or font changes to avoid broken layout",
        "Keep content screen-reader accessible when text is fragmented",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-scroll-section",
    trackId: "gsap",
    moduleId: "gsap-02-scroll-and-gesture",
    order: 9,
    title: {
      vi: "Mini-build: Section cuộn ghim có 3D",
      en: "Mini-build: Pinned Scroll Section with 3D",
    },
    summary: {
      vi: "Một section ghim, scrub theo cuộn, điều khiển camera/object 3D qua đúng một render loop — áp dụng toàn bộ module này vào một cảnh thật.",
      en: "A pinned, scroll-scrubbed section driving a 3D camera/object through exactly one render loop — applying this whole module to a real scene.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["gsap", "r3f", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["flip-layout-transitions"],
    objectives: {
      vi: [
        "Kết hợp ScrollTrigger scrub/pin với scene R3F qua một render loop duy nhất",
        "Chứng minh không có hai loop cạnh tranh gây giật hình",
      ],
      en: [
        "Combine ScrollTrigger scrub/pin with an R3F scene through a single render loop",
        "Prove there are no two competing loops causing stutter",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "choosing-your-animation-tool",
    trackId: "gsap",
    moduleId: "gsap-03-animation-craft",
    order: 10,
    title: {
      vi: "Chọn công cụ animation",
      en: "Choosing Your Animation Tool",
    },
    summary: {
      vi: "GSAP, Framer Motion và CSS animation giải quyết những vấn đề chồng lấn nhưng không giống nhau — chọn theo bài toán, không theo thói quen.",
      en: "GSAP, Framer Motion and CSS animation solve overlapping but distinct problems — choose by the problem, not by habit.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap", "animation", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-scroll-section"],
    objectives: {
      vi: [
        "So sánh mô hình lập trình của GSAP, Framer Motion và CSS animation",
        "Xác định điểm mạnh của từng công cụ: timeline phức tạp, gesture React, hiệu năng thuần CSS",
        "Chọn công cụ đúng cho một yêu cầu animation cụ thể và giải thích lý do",
      ],
      en: [
        "Compare the programming models of GSAP, Framer Motion and CSS animation",
        "Identify each tool's strength: complex timelines, React-native gestures, pure-CSS performance",
        "Pick the right tool for a concrete animation requirement and justify it",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "animation-principles-for-ui",
    trackId: "gsap",
    moduleId: "gsap-03-animation-craft",
    order: 11,
    title: {
      vi: "Nguyên tắc animation cho UI",
      en: "Animation Principles for UI",
    },
    summary: {
      vi: "Anticipation, follow-through và secondary motion đến từ hoạt hình cổ điển — chuyển thể chúng vào micro-interaction để UI có cảm giác sống.",
      en: "Anticipation, follow-through and secondary motion come from classical animation — translated into micro-interactions that make UI feel alive.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["choosing-your-animation-tool"],
    objectives: {
      vi: [
        "Giải thích anticipation, follow-through và secondary motion bằng ví dụ UI cụ thể",
        "Áp dụng overshoot/settle cho một nút bấm hoặc modal để tăng cảm giác vật lý",
        "Nhận biết khi nào thêm chuyển động là thừa và gây khó chịu",
      ],
      en: [
        "Explain anticipation, follow-through and secondary motion with concrete UI examples",
        "Apply overshoot/settle to a button or modal to add a sense of physicality",
        "Recognize when extra motion is excessive and annoying instead of helpful",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "compositor-friendly-animation",
    trackId: "gsap",
    moduleId: "gsap-03-animation-craft",
    order: 12,
    title: {
      vi: "Animation thân thiện compositor",
      en: "Compositor-Friendly Animation",
    },
    summary: {
      vi: "Chỉ transform và opacity chạy trên compositor thread mà không kích hoạt layout/paint — quy tắc hiệu năng nền tảng của mọi animation trên web.",
      en: "Only transform and opacity run on the compositor thread without triggering layout/paint — the foundational performance rule for every web animation.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["gsap", "perf", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["animation-principles-for-ui"],
    objectives: {
      vi: [
        "Giải thích vì sao animate transform/opacity rẻ hơn animate width/top/left",
        "Nhận diện thuộc tính CSS nào kích hoạt layout, paint hay chỉ composite",
        "Dùng DevTools Performance/Layers panel để xác nhận một animation chạy trên compositor",
      ],
      en: [
        "Explain why animating transform/opacity is cheaper than width/top/left",
        "Identify which CSS properties trigger layout, paint, or composite-only",
        "Use the DevTools Performance/Layers panel to confirm an animation runs on the compositor",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-scrollytelling-page",
    trackId: "gsap",
    moduleId: "gsap-03-animation-craft",
    order: 13,
    title: {
      vi: "Mini-build: Trang scrollytelling",
      en: "Mini-build: Scrollytelling Page",
    },
    summary: {
      vi: "Một trang kể chuyện qua cuộn trang: nhiều section pin/scrub, transition FLIP, và animation chỉ dùng transform/opacity đúng chuẩn hiệu năng.",
      en: "A scroll-driven storytelling page: multiple pinned/scrubbed sections, FLIP transitions, and animation restricted to performant transform/opacity.",
    },
    difficulty: 4,
    estimatedMinutes: 60,
    tags: ["gsap", "animation", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["compositor-friendly-animation"],
    objectives: {
      vi: [
        "Tổng hợp toàn bộ track: timeline, ScrollTrigger, FLIP và nguyên tắc animation vào một trang hoàn chỉnh",
        "Đóng track GSAP với một sản phẩm chạy mượt và đúng nguyên tắc compositor",
      ],
      en: [
        "Synthesize the whole track — timelines, ScrollTrigger, FLIP and animation principles — into one complete page",
        "Close the GSAP track with something that runs smoothly and respects compositor principles",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
