import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "procedural",
  order: 7,
  title: { vi: "Procedural & Noise", en: "Procedural & Noise" },
  summary: {
    vi: "Hash, Perlin, FBM, domain warping — bộ công cụ tạo mây, nước, địa hình và mọi thứ hữu cơ từ công thức.",
    en: "Hash, Perlin, FBM, domain warping — the toolkit for clouds, water, terrain and everything organic, from formulas.",
  },
  moduleIds: [
    "procedural-01-noise-foundations",
    "procedural-02-advanced-fields",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "procedural-01-noise-foundations",
    trackId: "procedural",
    order: 1,
    title: { vi: "Nền tảng noise", en: "Noise Foundations" },
    lessonSlugs: [
      "hash-functions-on-gpu",
      "value-and-gradient-noise",
      "perlin-and-simplex-noise",
      "fbm-fractal-brownian-motion",
      "checkpoint-procedural-clouds",
    ],
  },
  {
    id: "procedural-02-advanced-fields",
    trackId: "procedural",
    order: 2,
    title: { vi: "Trường nâng cao", en: "Advanced Fields" },
    lessonSlugs: [
      "domain-warping",
      "voronoi-and-worley",
      "curl-noise-flow-fields",
      "noise-in-3d-4d-time",
      "checkpoint-animated-terrain-material",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "hash-functions-on-gpu",
    trackId: "procedural",
    moduleId: "procedural-01-noise-foundations",
    order: 1,
    title: {
      vi: "Hash function trên GPU",
      en: "Hash Functions on the GPU",
    },
    summary: {
      vi: "GPU không có random() thật — mọi thứ ngẫu nhiên bắt đầu từ một hash function xác định biến toạ độ thành số giả-ngẫu-nhiên ổn định.",
      en: "The GPU has no true random() — everything random starts from a deterministic hash function turning coordinates into a stable pseudo-random number.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-enhanced-standard-material"],
    objectives: {
      vi: [
        "Giải thích vì sao GPU chỉ có hash xác định, không có random thật",
        "Viết một hash function 2D→1D bằng sin/fract và nhận biết artefact của nó",
        "Dùng seed để tạo nhiều giá trị giả-ngẫu-nhiên độc lập từ cùng một toạ độ",
      ],
      en: [
        "Explain why the GPU only has deterministic hashing, not true randomness",
        "Write a 2D→1D hash function with sin/fract and recognize its artifacts",
        "Use a seed to derive multiple independent pseudo-random values from the same coordinate",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "value-and-gradient-noise",
    trackId: "procedural",
    moduleId: "procedural-01-noise-foundations",
    order: 2,
    title: {
      vi: "Value noise & Gradient noise",
      en: "Value Noise & Gradient Noise",
    },
    summary: {
      vi: "Value noise nội suy giá trị ngẫu nhiên tại các điểm lưới; gradient noise nội suy hướng — cùng ý tưởng lưới nhưng cho kết cấu khác hẳn nhau.",
      en: "Value noise interpolates random values at grid points; gradient noise interpolates directions — same grid idea, very different resulting texture.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["hash-functions-on-gpu"],
    objectives: {
      vi: [
        "Dựng value noise từ hash + nội suy song tuyến tính (bilinear)",
        "Dựng gradient noise từ vector gradient ngẫu nhiên tại mỗi góc ô lưới",
        "So sánh trực quan hai loại noise và giải thích khác biệt về độ mượt",
      ],
      en: [
        "Build value noise from a hash plus bilinear interpolation",
        "Build gradient noise from random gradient vectors at each grid corner",
        "Compare the two noise types visually and explain the smoothness difference",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "perlin-and-simplex-noise",
    trackId: "procedural",
    moduleId: "procedural-01-noise-foundations",
    order: 3,
    title: { vi: "Perlin & Simplex noise", en: "Perlin & Simplex Noise" },
    summary: {
      vi: "Perlin noise chuẩn hoá gradient noise trên lưới vuông; Simplex thay lưới vuông bằng lưới tam giác để giảm chi phí tính toán khi lên chiều cao hơn.",
      en: "Perlin noise standardizes gradient noise on a square grid; Simplex replaces the square grid with a triangular one to cut cost as dimensions grow.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["value-and-gradient-noise"],
    objectives: {
      vi: [
        "Cài đặt Perlin noise 2D theo đúng thuật toán gốc (fade, gradient, lerp)",
        "Giải thích vì sao Simplex scale tốt hơn ở chiều cao (3D, 4D)",
        "Chọn Perlin hay Simplex tuỳ theo yêu cầu hiệu năng và số chiều",
      ],
      en: [
        "Implement 2D Perlin noise following the original algorithm (fade, gradient, lerp)",
        "Explain why Simplex scales better into higher dimensions (3D, 4D)",
        "Choose Perlin vs Simplex based on performance needs and dimensionality",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "fbm-fractal-brownian-motion",
    trackId: "procedural",
    moduleId: "procedural-01-noise-foundations",
    order: 4,
    title: {
      vi: "FBM — Fractal Brownian Motion",
      en: "FBM — Fractal Brownian Motion",
    },
    summary: {
      vi: "Chồng nhiều octave noise với tần số tăng dần và biên độ giảm dần để có kết cấu chi tiết nhiều tầng — nền tảng của mây, núi và vân đá thật.",
      en: "Stacking multiple noise octaves with rising frequency and falling amplitude to get multi-scale detail — the foundation of realistic clouds, mountains and rock texture.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["perlin-and-simplex-noise"],
    objectives: {
      vi: [
        "Cài đặt vòng lặp FBM với tham số octaves, lacunarity, gain",
        "Giải thích ảnh hưởng của từng tham số lên độ chi tiết và độ gồ ghề của kết quả",
        "Điều chỉnh FBM để mô phỏng mây, địa hình hoặc vân bề mặt",
      ],
      en: [
        "Implement an FBM loop with octaves, lacunarity and gain parameters",
        "Explain how each parameter affects the result's detail and roughness",
        "Tune FBM to approximate clouds, terrain or surface texture",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "checkpoint-procedural-clouds",
    trackId: "procedural",
    moduleId: "procedural-01-noise-foundations",
    order: 5,
    title: { vi: "Mini-build: Mây thủ tục", en: "Mini-build: Procedural Clouds" },
    summary: {
      vi: "Một fragment shader vẽ mây bằng FBM chuyển động theo thời gian — tổng hợp hash, gradient noise và FBM thành một cảnh nhìn được.",
      en: "A fragment shader rendering clouds with time-animated FBM — synthesizing hashing, gradient noise and FBM into one visible scene.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["noise", "shader", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["fbm-fractal-brownian-motion"],
    objectives: {
      vi: [
        "Kết hợp hash, gradient noise và FBM trong một shader mây hoàn chỉnh",
        "Tự đối chiếu kết quả với checklist trước khi xem đáp án",
      ],
      en: [
        "Combine hashing, gradient noise and FBM into one complete cloud shader",
        "Self-verify the result against the checklist before reaching for the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "domain-warping",
    trackId: "procedural",
    moduleId: "procedural-02-advanced-fields",
    order: 6,
    title: { vi: "Domain warping", en: "Domain Warping" },
    summary: {
      vi: "Kỹ thuật của Inigo Quilez: dùng noise để làm méo chính toạ độ đưa vào noise — biến kết cấu đều đặn thành hình xoáy hữu cơ.",
      en: "Inigo Quilez's technique: use noise to distort the very coordinates fed into noise — turning regular texture into organic swirling shapes.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-procedural-clouds"],
    objectives: {
      vi: [
        "Cài đặt domain warping một tầng: q = noise(p), rồi noise(p + q)",
        "Lồng nhiều tầng warp để tạo kết cấu marble/lửa/khói phức tạp hơn",
        "Điều chỉnh cường độ warp và giải thích ảnh hưởng lên hình dạng kết quả",
      ],
      en: [
        "Implement single-layer domain warping: q = noise(p), then noise(p + q)",
        "Nest multiple warp layers for more complex marble/fire/smoke textures",
        "Tune warp strength and explain its effect on the resulting shape",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "voronoi-and-worley",
    trackId: "procedural",
    moduleId: "procedural-02-advanced-fields",
    order: 7,
    title: { vi: "Voronoi & Worley noise", en: "Voronoi & Worley Noise" },
    summary: {
      vi: "Chia mặt phẳng thành các vùng quanh điểm gần nhất — nền tảng cho vân đá, da rắn, tế bào sinh học và pattern lát gạch hữu cơ.",
      en: "Partitioning the plane by nearest-point regions — the foundation for stone veins, reptile skin, cell patterns and organic tiling.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["domain-warping"],
    objectives: {
      vi: [
        "Cài đặt Voronoi/Worley bằng cách quét ô lân cận và tìm điểm gần nhất",
        "Trích xuất khoảng cách F1/F2 để tạo hiệu ứng đường viền tế bào",
        "Ứng dụng Voronoi cho vân đá, da hoặc pattern lát gạch hữu cơ",
      ],
      en: [
        "Implement Voronoi/Worley by scanning neighboring cells for the nearest point",
        "Extract F1/F2 distances to create cell-border effects",
        "Apply Voronoi to stone veins, skin, or organic tiling patterns",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "curl-noise-flow-fields",
    trackId: "procedural",
    moduleId: "procedural-02-advanced-fields",
    order: 8,
    title: {
      vi: "Curl noise & flow field",
      en: "Curl Noise & Flow Fields",
    },
    summary: {
      vi: "Lấy curl (xoáy) của một trường gradient noise cho ra một trường vector không phân kỳ — chuyển động trông tự nhiên như khói hoặc dòng chảy.",
      en: "Taking the curl of a gradient noise field yields a divergence-free vector field — motion that looks as natural as smoke or fluid flow.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["noise", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["voronoi-and-worley"],
    objectives: {
      vi: [
        "Giải thích vì sao curl của một trường tiềm năng cho vector field không phân kỳ",
        "Cài đặt curl noise 2D/3D bằng đạo hàm số của gradient noise",
        "Dùng curl noise làm flow field điều khiển chuyển động hạt/khói",
      ],
      en: [
        "Explain why the curl of a potential field yields a divergence-free vector field",
        "Implement 2D/3D curl noise via numerical derivatives of gradient noise",
        "Use curl noise as a flow field driving particle/smoke motion",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "noise-in-3d-4d-time",
    trackId: "procedural",
    moduleId: "procedural-02-advanced-fields",
    order: 9,
    title: {
      vi: "Noise 3D/4D theo thời gian",
      en: "Noise in 3D/4D over Time",
    },
    summary: {
      vi: "Dùng chiều thứ ba hoặc thứ tư của noise làm trục thời gian để animate mà không bao giờ lặp lại rõ ràng — khác hẳn việc dịch chuyển noise 2D.",
      en: "Using noise's third or fourth dimension as a time axis to animate without an obvious loop — very different from just scrolling 2D noise.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["noise", "animation"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["curl-noise-flow-fields"],
    objectives: {
      vi: [
        "Giải thích vì sao dịch chuyển noise 2D theo thời gian tạo cảm giác trôi giả tạo",
        "Dùng noise 3D/4D với trục thời gian để animate mượt và không lặp rõ",
        "Đánh đổi chi phí tính toán giữa noise 2D+scroll và noise 3D/4D thật",
      ],
      en: [
        "Explain why scrolling 2D noise over time reads as an artificial drift",
        "Use 3D/4D noise with a time axis for smooth, non-obviously-looping animation",
        "Weigh the compute cost tradeoff between 2D+scroll noise and true 3D/4D noise",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "checkpoint-animated-terrain-material",
    trackId: "procedural",
    moduleId: "procedural-02-advanced-fields",
    order: 10,
    title: {
      vi: "Mini-build: Vật liệu địa hình động",
      en: "Mini-build: Animated Terrain Material",
    },
    summary: {
      vi: "Một material study kết hợp domain warping, Voronoi và noise theo thời gian — chọn địa hình, marble hoặc vân gỗ và làm nó chuyển động sống.",
      en: "A material study combining domain warping, Voronoi and time-animated noise — pick terrain, marble or wood grain and bring it alive.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["noise", "shader", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["noise-in-3d-4d-time"],
    objectives: {
      vi: [
        "Kết hợp domain warping, Voronoi/FBM và noise theo thời gian trong một material hoàn chỉnh",
        "Đóng module Trường nâng cao với một vật liệu thủ tục chuyển động thuyết phục",
      ],
      en: [
        "Combine domain warping, Voronoi/FBM and time-animated noise into one complete material",
        "Close the Advanced Fields module with a convincingly animated procedural material",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
