import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "raymarching",
  order: 8,
  title: { vi: "Raymarching & SDF", en: "Raymarching & SDFs" },
  summary: {
    vi: "Dựng cả thế giới trong một fragment shader: sphere tracing, SDF, bóng mềm và không gian lặp vô hạn.",
    en: "Whole worlds in one fragment shader: sphere tracing, SDFs, soft shadows and infinitely repeating space.",
  },
  moduleIds: [
    "raymarching-01-sphere-tracing",
    "raymarching-02-shading-the-field",
    "raymarching-03-atmosphere-and-integration",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "raymarching-01-sphere-tracing",
    trackId: "raymarching",
    order: 1,
    title: { vi: "Sphere tracing", en: "Sphere Tracing" },
    lessonSlugs: [
      "sphere-tracing-principle",
      "sdf-primitives",
      "sdf-boolean-ops-smooth-min",
      "checkpoint-sdf-sculpture",
    ],
  },
  {
    id: "raymarching-02-shading-the-field",
    trackId: "raymarching",
    order: 2,
    title: {
      vi: "Shading trường khoảng cách",
      en: "Shading the Field",
    },
    lessonSlugs: [
      "sdf-normals-from-gradient",
      "raymarched-shadows-and-ao",
      "domain-repetition",
      "checkpoint-infinite-grid-world",
    ],
  },
  {
    id: "raymarching-03-atmosphere-and-integration",
    trackId: "raymarching",
    order: 3,
    title: {
      vi: "Khí quyển & Tích hợp",
      en: "Atmosphere & Integration",
    },
    lessonSlugs: [
      "fog-and-atmospheric-scattering",
      "volumetric-rendering-basics",
      "raymarching-optimization",
      "raymarch-raster-depth-integration",
      "checkpoint-raymarched-vista",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "sphere-tracing-principle",
    trackId: "raymarching",
    moduleId: "raymarching-01-sphere-tracing",
    order: 1,
    title: { vi: "Nguyên lý sphere tracing", en: "The Sphere Tracing Principle" },
    summary: {
      vi: "Thay vì giao điểm chính xác, raymarching bước theo tia một khoảng an toàn tối đa mỗi lần — dựng cả cảnh chỉ từ một hàm khoảng cách.",
      en: "Instead of exact intersection, raymarching steps along a ray by the maximum safe distance each time — rendering a whole scene from just a distance function.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["sdf", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-animated-terrain-material"],
    objectives: {
      vi: [
        "Giải thích vòng lặp sphere tracing: march theo tia bằng khoảng cách SDF trả về",
        "Cài đặt vòng lặp raymarch cơ bản với giới hạn số bước và ngưỡng dừng",
        "Nhận diện các tham số ảnh hưởng đến chất lượng/hiệu năng: max steps, epsilon, max distance",
      ],
      en: [
        "Explain the sphere tracing loop: march along the ray by the SDF's returned distance",
        "Implement a basic raymarch loop with a step limit and stopping threshold",
        "Identify parameters affecting quality/performance: max steps, epsilon, max distance",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "sdf-primitives",
    trackId: "raymarching",
    moduleId: "raymarching-01-sphere-tracing",
    order: 2,
    title: { vi: "SDF nguyên thuỷ", en: "SDF Primitives" },
    summary: {
      vi: "sphere, box, torus, capsule — bốn hàm khoảng cách nền tảng mà mọi cảnh raymarch phức tạp đều lắp ráp từ đó.",
      en: "sphere, box, torus, capsule — four foundational distance functions that every complex raymarched scene is assembled from.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["sdf", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["sphere-tracing-principle"],
    objectives: {
      vi: [
        "Viết công thức SDF cho sphere, box, torus, capsule",
        "Kiểm chứng một SDF đúng bằng cách quan sát contour tại giá trị 0",
        "Biến đổi vị trí/tỉ lệ một primitive bằng cách biến đổi điểm truy vấn trước khi gọi SDF",
      ],
      en: [
        "Write the SDF formula for sphere, box, torus, capsule",
        "Verify a correct SDF by observing its zero-level contour",
        "Move/scale a primitive by transforming the query point before calling the SDF",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "sdf-boolean-ops-smooth-min",
    trackId: "raymarching",
    moduleId: "raymarching-01-sphere-tracing",
    order: 3,
    title: {
      vi: "Phép boolean SDF & smooth min",
      en: "SDF Boolean Ops & Smooth Min",
    },
    summary: {
      vi: "union, subtraction, intersection ghép các SDF lại bằng min/max — và smooth min làm chúng hoà vào nhau như đất sét thay vì cắt góc cứng.",
      en: "union, subtraction, intersection combine SDFs with min/max — and smooth min blends them like clay instead of a hard-edged cut.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["sdf", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["sdf-primitives"],
    objectives: {
      vi: [
        "Cài đặt union/subtraction/intersection từ min/max trên hai SDF",
        "Cài đặt smooth min (polynomial hoặc exponential) và điều chỉnh độ mượt",
        "Kết hợp nhiều primitive và phép boolean để tạo hình phức tạp",
      ],
      en: [
        "Implement union/subtraction/intersection from min/max on two SDFs",
        "Implement smooth min (polynomial or exponential) and tune the blend amount",
        "Combine multiple primitives and boolean ops into a more complex shape",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "checkpoint-sdf-sculpture",
    trackId: "raymarching",
    moduleId: "raymarching-01-sphere-tracing",
    order: 4,
    title: { vi: "Mini-build: Điêu khắc SDF", en: "Mini-build: SDF Sculpture" },
    summary: {
      vi: "Dựng một hình điêu khắc từ nhiều primitive SDF ghép bằng union/subtraction/smooth min trong một fragment shader raymarch hoàn chỉnh.",
      en: "Sculpt a shape from multiple SDF primitives combined with union/subtraction/smooth min in one complete raymarching fragment shader.",
    },
    difficulty: 4,
    estimatedMinutes: 50,
    tags: ["sdf", "shader", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["sdf-boolean-ops-smooth-min"],
    objectives: {
      vi: [
        "Kết hợp sphere tracing, SDF primitive và phép boolean trong một cảnh hoàn chỉnh",
        "Tự đối chiếu kết quả với checklist trước khi xem đáp án",
      ],
      en: [
        "Combine sphere tracing, SDF primitives and boolean ops in one complete scene",
        "Self-verify the result against the checklist before reaching for the solution",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "sdf-normals-from-gradient",
    trackId: "raymarching",
    moduleId: "raymarching-02-shading-the-field",
    order: 5,
    title: {
      vi: "Tính normal từ gradient SDF",
      en: "SDF Normals from the Gradient",
    },
    summary: {
      vi: "Không có mesh, không có vertex normal — pháp tuyến của một điểm bề mặt SDF được ước lượng bằng gradient số của chính hàm khoảng cách.",
      en: "No mesh, no vertex normals — a surface normal at an SDF point is estimated from the numerical gradient of the distance function itself.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["sdf", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-sdf-sculpture"],
    objectives: {
      vi: [
        "Ước lượng normal bằng kỹ thuật tetrahedron hoặc central-difference trên SDF",
        "Dùng normal để tính lighting Lambert/Blinn-Phong cơ bản trên bề mặt raymarch",
        "Đánh đổi giữa số lần gọi SDF thêm và độ chính xác normal",
      ],
      en: [
        "Estimate normals using the tetrahedron or central-difference technique on an SDF",
        "Use the normal for basic Lambert/Blinn-Phong lighting on a raymarched surface",
        "Trade off extra SDF calls against normal accuracy",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "raymarched-shadows-and-ao",
    trackId: "raymarching",
    moduleId: "raymarching-02-shading-the-field",
    order: 6,
    title: {
      vi: "Bóng mềm & AO trong raymarch",
      en: "Raymarched Soft Shadows & AO",
    },
    summary: {
      vi: "Soft shadow đo khoảng cách gần nhất tới vật cản dọc tia sáng; ambient occlusion lấy mẫu SDF quanh điểm — cả hai đều rẻ hơn shadow map truyền thống.",
      en: "Soft shadows measure the closest approach to an occluder along the light ray; ambient occlusion samples the SDF around a point — both cheaper than traditional shadow maps.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["sdf", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["sdf-normals-from-gradient"],
    objectives: {
      vi: [
        "Cài đặt soft shadow bằng kỹ thuật penumbra ratio dọc theo tia bóng",
        "Cài đặt ambient occlusion bằng cách lấy mẫu SDF dọc theo normal",
        "Điều chỉnh tham số độ mềm bóng và cường độ AO cho từng cảnh",
      ],
      en: [
        "Implement soft shadows using the penumbra-ratio technique along the shadow ray",
        "Implement ambient occlusion by sampling the SDF along the normal",
        "Tune shadow softness and AO strength for a given scene",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "domain-repetition",
    trackId: "raymarching",
    moduleId: "raymarching-02-shading-the-field",
    order: 7,
    title: { vi: "Lặp không gian (domain repetition)", en: "Domain Repetition" },
    summary: {
      vi: "Lấy modulo toạ độ truy vấn trước khi gọi SDF để một object lặp lại vô hạn trong không gian mà chỉ tốn bộ nhớ O(1).",
      en: "Taking the modulo of the query coordinate before calling the SDF repeats one object infinitely across space at O(1) memory cost.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["sdf", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["raymarched-shadows-and-ao"],
    objectives: {
      vi: [
        "Cài đặt domain repetition bằng mod() trên toạ độ truy vấn",
        "Giải thích vì sao kỹ thuật này cho không gian vô hạn với bộ nhớ hằng số",
        "Giới hạn vùng lặp (finite repetition) để tránh artefact ở biên",
      ],
      en: [
        "Implement domain repetition using mod() on the query coordinate",
        "Explain why this technique yields infinite space at constant memory cost",
        "Bound the repeated region (finite repetition) to avoid edge artifacts",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "checkpoint-infinite-grid-world",
    trackId: "raymarching",
    moduleId: "raymarching-02-shading-the-field",
    order: 8,
    title: {
      vi: "Mini-build: Thế giới lưới vô hạn",
      en: "Mini-build: Infinite Grid World",
    },
    summary: {
      vi: "Một cảnh raymarch với object lặp vô hạn qua domain repetition, có normal, bóng mềm và AO đầy đủ — shading hoàn chỉnh cho trường khoảng cách.",
      en: "A raymarched scene with an infinitely repeating object via domain repetition, complete with normals, soft shadows and AO — full shading for a distance field.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["sdf", "shader", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["domain-repetition"],
    objectives: {
      vi: [
        "Kết hợp normal, bóng mềm, AO và domain repetition trong một cảnh hoàn chỉnh",
        "Đóng module Shading với một thế giới trông có chiều sâu thật",
      ],
      en: [
        "Combine normals, soft shadows, AO and domain repetition in one complete scene",
        "Close the Shading module with a world that reads with real depth",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "fog-and-atmospheric-scattering",
    trackId: "raymarching",
    moduleId: "raymarching-03-atmosphere-and-integration",
    order: 9,
    title: {
      vi: "Fog & tán xạ khí quyển",
      en: "Fog & Atmospheric Scattering",
    },
    summary: {
      vi: "Trộn màu bề mặt với màu khí quyển theo hàm mũ của khoảng cách — cách rẻ nhất để một cảnh raymarch có chiều sâu và không khí.",
      en: "Blending surface color with atmosphere color by an exponential function of distance — the cheapest way to give a raymarched scene depth and air.",
    },
    difficulty: 4,
    estimatedMinutes: 30,
    tags: ["sdf", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-infinite-grid-world"],
    objectives: {
      vi: [
        "Cài đặt exponential fog dựa trên khoảng cách marching",
        "Mô phỏng tán xạ khí quyển đơn giản phụ thuộc góc nhìn mặt trời",
        "Điều chỉnh mật độ fog để tạo chiều sâu mà không làm mất chi tiết gần",
      ],
      en: [
        "Implement exponential fog based on the marched distance",
        "Approximate simple atmospheric scattering that depends on sun view angle",
        "Tune fog density for depth without losing near-field detail",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "volumetric-rendering-basics",
    trackId: "raymarching",
    moduleId: "raymarching-03-atmosphere-and-integration",
    order: 10,
    title: {
      vi: "Cơ bản render thể tích",
      en: "Volumetric Rendering Basics",
    },
    summary: {
      vi: "Thay vì dừng ở bề mặt, tích luỹ mật độ và màu dọc theo tia qua một thể tích — nguyên lý đứng sau mây, khói và ánh sáng xuyên vật liệu mờ.",
      en: "Instead of stopping at a surface, accumulate density and color along a ray through a volume — the principle behind clouds, smoke and light through translucent media.",
    },
    difficulty: 5,
    estimatedMinutes: 45,
    tags: ["sdf", "shader"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["fog-and-atmospheric-scattering"],
    objectives: {
      vi: [
        "Giải thích vòng lặp tích luỹ mật độ/màu (ray marching qua thể tích) khác raymarch bề mặt thế nào",
        "Cài đặt một volumetric march đơn giản với density field từ noise",
        "Nhận diện chi phí hiệu năng của volumetric rendering và lý do cần giới hạn chất lượng",
      ],
      en: [
        "Explain how density/color accumulation (marching through a volume) differs from surface raymarching",
        "Implement a simple volumetric march with a noise-based density field",
        "Identify volumetric rendering's performance cost and why quality must be bounded",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "raymarching-optimization",
    trackId: "raymarching",
    moduleId: "raymarching-03-atmosphere-and-integration",
    order: 11,
    title: {
      vi: "Tối ưu raymarching",
      en: "Raymarching Optimization",
    },
    summary: {
      vi: "Bounding volume cắt sớm những tia không thể chạm cảnh, adaptive step nới bước ở vùng trống, và early exit dừng ngay khi đủ chính xác.",
      en: "Bounding volumes early-reject rays that can't hit the scene, adaptive steps widen in empty space, and early exit stops as soon as accuracy is enough.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["sdf", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["fog-and-atmospheric-scattering"],
    objectives: {
      vi: [
        "Bọc cảnh bằng bounding volume để bỏ qua sớm những tia chắc chắn trượt",
        "Cài đặt adaptive step size dựa trên khoảng cách hiện tại đến bề mặt",
        "Thiết lập early exit và giới hạn số bước hợp lý theo ngân sách hiệu năng",
      ],
      en: [
        "Wrap a scene in a bounding volume to early-reject rays guaranteed to miss",
        "Implement adaptive step sizing based on the current distance to the surface",
        "Set early exit and a sane step-count cap within a performance budget",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "raymarch-raster-depth-integration",
    trackId: "raymarching",
    moduleId: "raymarching-03-atmosphere-and-integration",
    order: 12,
    title: {
      vi: "Tích hợp raymarch với depth rasterized",
      en: "Raymarch + Rasterized Depth Integration",
    },
    summary: {
      vi: "Ghi lại depth buffer của scene rasterized rồi dùng nó làm giới hạn dừng cho raymarch — để một cảnh SDF và một cảnh mesh cùng che khuất nhau đúng.",
      en: "Reading the rasterized scene's depth buffer and using it as a stopping bound for raymarching — so an SDF scene and a mesh scene occlude each other correctly.",
    },
    difficulty: 5,
    estimatedMinutes: 45,
    tags: ["sdf", "threejs"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["raymarching-optimization"],
    objectives: {
      vi: [
        "Đọc depth buffer của scene rasterized và chuyển nó về khoảng cách trong không gian view",
        "Dùng depth đó làm giới hạn max distance cho vòng lặp raymarch",
        "Kết hợp một object raymarch với một scene Three.js thường sao cho occlusion đúng cả hai chiều",
      ],
      en: [
        "Read a rasterized scene's depth buffer and convert it to view-space distance",
        "Use that depth as the max-distance bound for the raymarch loop",
        "Combine a raymarched object with a regular Three.js scene with correct two-way occlusion",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "checkpoint-raymarched-vista",
    trackId: "raymarching",
    moduleId: "raymarching-03-atmosphere-and-integration",
    order: 13,
    title: {
      vi: "Mini-build: Toàn cảnh raymarch",
      en: "Mini-build: Raymarched Vista",
    },
    summary: {
      vi: "Một cảnh phong cảnh đầy đủ: SDF terrain, fog khí quyển và tối ưu hoá bước march — track raymarching khép lại bằng một vista chạy mượt.",
      en: "A full landscape scene: SDF terrain, atmospheric fog and marching-step optimization — the raymarching track closes with a smoothly running vista.",
    },
    difficulty: 5,
    estimatedMinutes: 60,
    tags: ["sdf", "shader", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["raymarching-optimization"],
    objectives: {
      vi: [
        "Kết hợp SDF, fog khí quyển và kỹ thuật tối ưu trong một cảnh hoàn chỉnh chạy thời gian thực",
        "Đóng track Raymarching với một vista giữ được khung hình ổn định",
      ],
      en: [
        "Combine SDFs, atmospheric fog and optimization techniques in one complete real-time scene",
        "Close the Raymarching track with a vista that holds a stable frame rate",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
