import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "gpgpu",
  order: 9,
  title: { vi: "GPGPU, Particles & Simulation", en: "GPGPU, Particles & Simulation" },
  summary: {
    vi: "Lưu trạng thái vào texture, ping-pong FBO và instancing — chạy hàng triệu particle mà CPU không đổ mồ hôi.",
    en: "State in textures, ping-pong FBOs and instancing — millions of particles without the CPU breaking a sweat.",
  },
  moduleIds: [
    "gpgpu-01-state-on-the-gpu",
    "gpgpu-02-behaviors-at-scale",
    "gpgpu-03-simulation",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "gpgpu-01-state-on-the-gpu",
    trackId: "gpgpu",
    order: 1,
    title: { vi: "Trạng thái trên GPU", en: "State on the GPU" },
    lessonSlugs: [
      "why-particles-live-on-gpu",
      "pingpong-fbo-state-textures",
      "gpucomputationrenderer",
      "transform-feedback",
      "checkpoint-100k-particle-grid",
    ],
  },
  {
    id: "gpgpu-02-behaviors-at-scale",
    trackId: "gpgpu",
    order: 2,
    title: { vi: "Hành vi ở quy mô lớn", en: "Behaviors at Scale" },
    lessonSlugs: [
      "flow-field-particles",
      "boids-flocking-on-gpu",
      "instancing-a-million-objects",
      "checkpoint-interactive-particle-field",
    ],
  },
  {
    id: "gpgpu-03-simulation",
    trackId: "gpgpu",
    order: 3,
    title: { vi: "Mô phỏng", en: "Simulation" },
    lessonSlugs: [
      "cloth-simulation-basics",
      "fluid-simulation-intro",
      "checkpoint-cloth-flag",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "why-particles-live-on-gpu",
    trackId: "gpgpu",
    moduleId: "gpgpu-01-state-on-the-gpu",
    order: 1,
    title: {
      vi: "Vì sao particle phải sống trên GPU",
      en: "Why Particles Live on the GPU",
    },
    summary: {
      vi: "Cập nhật hàng trăm nghìn particle mỗi frame trên CPU nghẽn ở băng thông JS↔GPU — lời giải là giữ toàn bộ trạng thái và cập nhật nó ngay trên GPU.",
      en: "Updating hundreds of thousands of particles per frame on the CPU chokes on JS↔GPU bandwidth — the fix is keeping all state on the GPU and updating it there.",
    },
    difficulty: 4,
    estimatedMinutes: 30,
    tags: ["gpgpu", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-raymarched-vista"],
    objectives: {
      vi: [
        "Giải thích nút thắt cổ chai khi cập nhật particle bằng CPU rồi upload lại buffer mỗi frame",
        "Mô tả ý tưởng cốt lõi của GPGPU: dùng texture làm bộ nhớ trạng thái, shader làm hàm cập nhật",
        "Ước lượng khi nào một hệ particle đủ lớn để đáng chuyển sang GPU",
      ],
      en: [
        "Explain the bottleneck of updating particles on the CPU and re-uploading buffers every frame",
        "Describe GPGPU's core idea: textures as state memory, shaders as the update function",
        "Estimate when a particle system is large enough to be worth moving to the GPU",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "pingpong-fbo-state-textures",
    trackId: "gpgpu",
    moduleId: "gpgpu-01-state-on-the-gpu",
    order: 2,
    title: {
      vi: "Ping-pong FBO & texture trạng thái",
      en: "Ping-Pong FBO & State Textures",
    },
    summary: {
      vi: "Đọc từ một framebuffer trong khi ghi vào cái kia rồi hoán đổi mỗi frame — kỹ thuật ping-pong cho phép GPU tự cập nhật trạng thái của chính nó, với position/velocity mã hoá vào kênh RGBA.",
      en: "Reading from one framebuffer while writing to the other, then swapping each frame — the ping-pong technique lets the GPU update its own state, with position/velocity encoded into RGBA channels.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["gpgpu", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["why-particles-live-on-gpu"],
    objectives: {
      vi: [
        "Dựng hai render target và hoán đổi vai trò đọc/ghi giữa chúng mỗi frame",
        "Mã hoá position và velocity của particle vào các kênh màu của một texture trạng thái",
        "Viết một fragment shader đọc trạng thái frame trước và ghi trạng thái frame sau",
      ],
      en: [
        "Set up two render targets and swap their read/write roles each frame",
        "Encode particle position and velocity into a state texture's color channels",
        "Write a fragment shader that reads the previous frame's state and writes the next",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "gpucomputationrenderer",
    trackId: "gpgpu",
    moduleId: "gpgpu-01-state-on-the-gpu",
    order: 3,
    title: { vi: "GPUComputationRenderer", en: "GPUComputationRenderer" },
    summary: {
      vi: "Tiện ích chính thức của Three.js đóng gói ping-pong FBO thành API variable/compute — bớt boilerplate cho cùng kỹ thuật đã học ở bài trước.",
      en: "Three.js's official utility wraps ping-pong FBOs into a variable/compute API — less boilerplate for the same technique from the previous lesson.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["gpgpu", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["pingpong-fbo-state-textures"],
    objectives: {
      vi: [
        "Khai báo compute variable và shader cập nhật bằng GPUComputationRenderer",
        "Đọc texture kết quả compute và dùng nó làm position source cho particle mesh",
        "Đối chiếu API này với ping-pong FBO thủ công để thấy nó tự động hoá phần nào",
      ],
      en: [
        "Declare a compute variable and its update shader with GPUComputationRenderer",
        "Read the resulting compute texture and use it as the position source for a particle mesh",
        "Compare this API to manual ping-pong FBOs to see what it automates",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "transform-feedback",
    trackId: "gpgpu",
    moduleId: "gpgpu-01-state-on-the-gpu",
    order: 4,
    title: { vi: "Transform feedback (WebGL2)", en: "Transform Feedback (WebGL2)" },
    summary: {
      vi: "Thay vì mã hoá trạng thái vào pixel của texture, WebGL2 cho phép vertex shader ghi thẳng ra buffer — một hướng thay thế cho ping-pong FBO.",
      en: "Instead of encoding state into texture pixels, WebGL2 lets a vertex shader write straight to a buffer — an alternative path to ping-pong FBOs.",
    },
    difficulty: 5,
    estimatedMinutes: 40,
    tags: ["gpgpu"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["gpucomputationrenderer"],
    objectives: {
      vi: [
        "Giải thích cơ chế transform feedback: vertex shader ghi output ra buffer thay vì rasterize",
        "Cài đặt một vòng cập nhật particle đơn giản bằng transform feedback trong WebGL2",
        "So sánh transform feedback với texture ping-pong: khi nào mỗi cách phù hợp hơn",
      ],
      en: [
        "Explain transform feedback: a vertex shader writing output to a buffer instead of rasterizing",
        "Implement a simple particle update loop using WebGL2 transform feedback",
        "Compare transform feedback to texture ping-pong and when each fits better",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-100k-particle-grid",
    trackId: "gpgpu",
    moduleId: "gpgpu-01-state-on-the-gpu",
    order: 5,
    title: {
      vi: "Mini-build: Lưới 100k particle",
      en: "Mini-build: 100k Particle Grid",
    },
    summary: {
      vi: "100.000 particle với vị trí và vận tốc cập nhật hoàn toàn trên GPU qua ping-pong FBO hoặc GPUComputationRenderer — không một dòng cập nhật nào chạy trên CPU.",
      en: "100,000 particles with position and velocity updated entirely on the GPU via ping-pong FBOs or GPUComputationRenderer — not a single update line runs on the CPU.",
    },
    difficulty: 5,
    estimatedMinutes: 55,
    tags: ["gpgpu", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["gpucomputationrenderer"],
    objectives: {
      vi: [
        "Kết hợp texture trạng thái, compute shader và render particle vào một pipeline hoàn chỉnh",
        "Chứng minh hệ thống giữ khung hình ổn định ở quy mô 100k particle",
      ],
      en: [
        "Combine state textures, a compute shader and particle rendering into one full pipeline",
        "Prove the system holds a stable frame rate at 100k-particle scale",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "flow-field-particles",
    trackId: "gpgpu",
    moduleId: "gpgpu-02-behaviors-at-scale",
    order: 6,
    title: { vi: "Particle theo flow field", en: "Flow Field Particles" },
    summary: {
      vi: "Đọc một trường vector (curl noise, texture vẽ tay) trong compute shader để lái vận tốc particle — hành vi hữu cơ trên quy mô lớn, vẫn hoàn toàn trên GPU.",
      en: "Sampling a vector field (curl noise, hand-painted texture) inside the compute shader to steer particle velocity — organic behavior at scale, still entirely on the GPU.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["gpgpu", "noise"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-100k-particle-grid"],
    objectives: {
      vi: [
        "Lấy mẫu một flow field (curl noise hoặc texture) trong compute shader để cập nhật vận tốc",
        "Kết hợp lực flow field với damping để particle không phát tán vô hạn",
        "Điều chỉnh scale/cường độ flow field để đổi cảm giác chuyển động",
      ],
      en: [
        "Sample a flow field (curl noise or texture) in the compute shader to update velocity",
        "Combine flow-field force with damping so particles don't spread out indefinitely",
        "Tune the flow field's scale/strength to change the motion's feel",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "boids-flocking-on-gpu",
    trackId: "gpgpu",
    moduleId: "gpgpu-02-behaviors-at-scale",
    order: 7,
    title: { vi: "Boids flocking trên GPU", en: "Boids Flocking on the GPU" },
    summary: {
      vi: "Ba quy tắc cổ điển của Reynolds — separation, alignment, cohesion — chuyển thành một compute shader lấy mẫu hàng xóm qua texture trạng thái.",
      en: "Reynolds's three classic rules — separation, alignment, cohesion — translated into a compute shader that samples neighbors via the state texture.",
    },
    difficulty: 5,
    estimatedMinutes: 45,
    tags: ["gpgpu"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["flow-field-particles"],
    objectives: {
      vi: [
        "Cài đặt separation, alignment, cohesion bằng cách lấy mẫu một vùng hàng xóm trong texture trạng thái",
        "Cân bằng trọng số ba quy tắc để có hành vi bầy đàn thuyết phục",
        "Giải thích giới hạn số hàng xóm lấy mẫu được để giữ hiệu năng ở quy mô lớn",
      ],
      en: [
        "Implement separation, alignment, cohesion by sampling a neighborhood in the state texture",
        "Balance the three rules' weights for convincing flocking behavior",
        "Explain the sampled-neighbor limit needed to keep performance at scale",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "instancing-a-million-objects",
    trackId: "gpgpu",
    moduleId: "gpgpu-02-behaviors-at-scale",
    order: 8,
    title: {
      vi: "Instancing hàng triệu object",
      en: "Instancing a Million Objects",
    },
    summary: {
      vi: "Đọc texture trạng thái GPGPU trực tiếp trong vertex shader của một InstancedMesh — nối compute và render thành một pipeline một triệu object không qua CPU.",
      en: "Reading the GPGPU state texture directly in an InstancedMesh's vertex shader — chaining compute and render into a million-object pipeline that never touches the CPU.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["gpgpu", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["flow-field-particles"],
    objectives: {
      vi: [
        "Đọc texture trạng thái compute trong vertex shader của InstancedMesh để đặt vị trí từng instance",
        "Tránh việc đọc lại vị trí về CPU — giữ toàn bộ pipeline compute→render trên GPU",
        "Đo và so sánh hiệu năng giữa cách tiếp cận này với cập nhật instanceMatrix bằng CPU",
      ],
      en: [
        "Read the compute state texture in an InstancedMesh vertex shader to position each instance",
        "Avoid reading positions back to the CPU — keep the whole compute→render pipeline on the GPU",
        "Measure and compare performance against updating instanceMatrix from the CPU",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-interactive-particle-field",
    trackId: "gpgpu",
    moduleId: "gpgpu-02-behaviors-at-scale",
    order: 9,
    title: {
      vi: "Mini-build: Trường particle tương tác",
      en: "Mini-build: Interactive Particle Field",
    },
    summary: {
      vi: "Một trường particle phản ứng theo chuột qua flow field điều khiển bởi vị trí con trỏ, render bằng instancing — hạt giống cho capstone 3 (GPU particle system tương tác).",
      en: "A particle field reacting to the mouse via a cursor-driven flow field, rendered with instancing — the seed for capstone 3 (interactive GPU particle system).",
    },
    difficulty: 5,
    estimatedMinutes: 55,
    tags: ["gpgpu", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["instancing-a-million-objects"],
    objectives: {
      vi: [
        "Kết hợp flow field, tương tác chuột và instancing trong một hệ particle hoàn chỉnh",
        "Đóng module Hành vi ở quy mô lớn với một trải nghiệm tương tác chạy mượt",
      ],
      en: [
        "Combine a flow field, mouse interaction and instancing into one complete particle system",
        "Close the Behaviors at Scale module with a smoothly running interactive experience",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "cloth-simulation-basics",
    trackId: "gpgpu",
    moduleId: "gpgpu-03-simulation",
    order: 10,
    title: { vi: "Cơ bản mô phỏng vải", en: "Cloth Simulation Basics" },
    summary: {
      vi: "Mô hình mass-spring: mỗi đỉnh vải là một khối lượng nối bằng lò xo với hàng xóm — verlet integration cập nhật cả lưới ổn định trên GPU.",
      en: "The mass-spring model: each cloth vertex is a mass linked by springs to its neighbors — verlet integration updates the whole grid stably on the GPU.",
    },
    difficulty: 5,
    estimatedMinutes: 45,
    tags: ["gpgpu"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["checkpoint-interactive-particle-field"],
    objectives: {
      vi: [
        "Giải thích mô hình mass-spring và vì sao verlet integration ổn định hơn Euler cho mô phỏng vải",
        "Cài đặt một lưới constraint khoảng cách cập nhật trên texture trạng thái GPU",
        "Thêm lực trọng trường và gió, xử lý điểm ghim (pin) trên lưới vải",
      ],
      en: [
        "Explain the mass-spring model and why verlet integration is more stable than Euler for cloth",
        "Implement a grid of distance constraints updated on a GPU state texture",
        "Add gravity and wind forces, and handle pinned points on the cloth grid",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "fluid-simulation-intro",
    trackId: "gpgpu",
    moduleId: "gpgpu-03-simulation",
    order: 11,
    title: {
      vi: "Giới thiệu mô phỏng chất lỏng",
      en: "Fluid Simulation Intro",
    },
    summary: {
      vi: "Tổng quan ba hướng tiếp cận chất lỏng thời gian thực — SPH hạt-dựa, PBF ràng buộc-dựa, và stable fluids lưới-dựa của Stam — không đi sâu cài đặt đầy đủ.",
      en: "An overview of three real-time fluid approaches — particle-based SPH, constraint-based PBF, and Stam's grid-based stable fluids — without a full implementation.",
    },
    difficulty: 5,
    estimatedMinutes: 35,
    tags: ["gpgpu"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["checkpoint-interactive-particle-field"],
    objectives: {
      vi: [
        "Phân biệt cách tiếp cận hạt (SPH, PBF) và cách tiếp cận lưới (stable fluids) cho chất lỏng",
        "Giải thích ý tưởng cốt lõi của Stable Fluids: advect, diffuse, project để giữ vận tốc không phân kỳ",
        "Đánh giá độ phức tạp/chi phí của từng hướng để chọn cho một demo thực tế",
      ],
      en: [
        "Distinguish particle-based (SPH, PBF) from grid-based (stable fluids) approaches to fluids",
        "Explain Stable Fluids' core idea: advect, diffuse, project to keep velocity divergence-free",
        "Assess each approach's complexity/cost to choose one for a real demo",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-cloth-flag",
    trackId: "gpgpu",
    moduleId: "gpgpu-03-simulation",
    order: 12,
    title: { vi: "Mini-build: Lá cờ vải mô phỏng", en: "Mini-build: Cloth Flag" },
    summary: {
      vi: "Một lá cờ mô phỏng bằng mass-spring chạy trên GPU, phản ứng với gió và trọng lực — khép lại track GPGPU bằng một mô phỏng vật lý thấy được.",
      en: "A flag simulated with a GPU-driven mass-spring system reacting to wind and gravity — closing the GPGPU track with a visible physics simulation.",
    },
    difficulty: 5,
    estimatedMinutes: 60,
    tags: ["gpgpu", "build"],
    tier: "elective",
    kind: "checkpoint",
    prerequisites: ["checkpoint-interactive-particle-field"],
    objectives: {
      vi: [
        "Kết hợp constraint mass-spring, lực gió/trọng lực và cập nhật trạng thái GPU trong một mô phỏng hoàn chỉnh",
        "Đóng track GPGPU với một mô phỏng vật lý chạy ổn định thời gian thực",
      ],
      en: [
        "Combine mass-spring constraints, wind/gravity forces and GPU state updates into one complete simulation",
        "Close the GPGPU track with a physics simulation that runs stably in real time",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
