import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "postprocessing",
  order: 10,
  title: { vi: "Post-processing", en: "Post-processing" },
  summary: {
    vi: "EffectComposer, bloom, DOF, color grading — lớp hoàn thiện điện ảnh, và cái giá fillrate của từng pass.",
    en: "EffectComposer, bloom, DOF, color grading — the cinematic finishing layer, and each pass's fillrate price.",
  },
  moduleIds: [
    "postprocessing-01-composer-and-effects",
    "postprocessing-02-grading-and-custom",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "postprocessing-01-composer-and-effects",
    trackId: "postprocessing",
    order: 1,
    title: { vi: "Composer & Hiệu ứng lõi", en: "Composer & Core Effects" },
    lessonSlugs: [
      "effectcomposer-and-passes",
      "bloom-done-right",
      "depth-of-field-and-motion-blur",
      "ssao",
      "checkpoint-cinematic-scene",
    ],
  },
  {
    id: "postprocessing-02-grading-and-custom",
    trackId: "postprocessing",
    order: 2,
    title: { vi: "Grading & Pass tự viết", en: "Grading & Custom Passes" },
    lessonSlugs: [
      "stylistic-effects-grain-vignette",
      "color-grading-lut-tonemapping",
      "writing-custom-passes",
      "pass-order-and-fillrate",
      "checkpoint-signature-effect-stack",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "effectcomposer-and-passes",
    trackId: "postprocessing",
    moduleId: "postprocessing-01-composer-and-effects",
    order: 1,
    title: { vi: "EffectComposer & Render Pass", en: "EffectComposer & Render Passes" },
    summary: {
      vi: "Kiến trúc pipeline hậu kỳ của Three.js: render target, RenderPass, và cách composer nối chuỗi các pass lại thành một ảnh cuối.",
      en: "The architecture behind Three.js post-processing: render targets, RenderPass, and how the composer chains passes into one final image.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["postfx", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-interactive-particle-field"],
    objectives: {
      vi: [
        "Dựng EffectComposer với RenderPass và ShaderPass cơ bản",
        "Giải thích render target ping-pong hoạt động thế nào giữa các pass",
        "Đo chi phí thêm một pass vào pipeline bằng frame time",
      ],
      en: [
        "Set up an EffectComposer with a RenderPass and a basic ShaderPass",
        "Explain how render targets ping-pong between passes",
        "Measure the frame-time cost of adding a pass to the pipeline",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "bloom-done-right",
    trackId: "postprocessing",
    moduleId: "postprocessing-01-composer-and-effects",
    order: 2,
    title: { vi: "Bloom làm đúng cách", en: "Bloom Done Right" },
    summary: {
      vi: "Vì sao bloom mặc định trông giả và rẻ tiền: threshold sai, thiếu luminance mask, và UnrealBloomPass thực sự làm gì phía sau.",
      en: "Why default bloom looks cheap and fake: wrong thresholds, missing luminance masks, and what UnrealBloomPass actually does under the hood.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["postfx"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["effectcomposer-and-passes"],
    objectives: {
      vi: [
        "Cấu hình threshold, strength, radius của UnrealBloomPass có chủ đích thay vì đoán mò",
        "Giải thích vì sao bloom cần chạy trên buffer HDR để không bị clip",
        "Nhận diện bloom bị lạm dụng và sửa bằng selective bloom hoặc luminance mask",
      ],
      en: [
        "Tune UnrealBloomPass threshold, strength and radius with intent instead of guessing",
        "Explain why bloom needs an HDR buffer to avoid clipping",
        "Spot overused bloom and fix it with selective bloom or a luminance mask",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "depth-of-field-and-motion-blur",
    trackId: "postprocessing",
    moduleId: "postprocessing-01-composer-and-effects",
    order: 3,
    title: { vi: "Depth of Field & Motion Blur", en: "Depth of Field & Motion Blur" },
    summary: {
      vi: "Làm mờ theo độ sâu và theo chuyển động: bokeh dựa trên circle-of-confusion, và motion blur dựa trên velocity buffer thay vì blur giả.",
      en: "Blurring by depth and by motion: bokeh driven by circle-of-confusion, and motion blur driven by a velocity buffer instead of fake blur.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["postfx"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["bloom-done-right"],
    objectives: {
      vi: [
        "Cấu hình DOF pass với focus distance, aperture và tính circle-of-confusion",
        "Giải thích vì sao motion blur đúng cần velocity buffer chứ không chỉ blend frame trước",
        "Đánh giá đánh đổi chất lượng/hiệu năng giữa các kỹ thuật DOF",
      ],
      en: [
        "Configure a DOF pass with focus distance, aperture, and circle-of-confusion",
        "Explain why correct motion blur needs a velocity buffer, not just blending the previous frame",
        "Weigh quality/performance tradeoffs across DOF techniques",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "ssao",
    trackId: "postprocessing",
    moduleId: "postprocessing-01-composer-and-effects",
    order: 4,
    title: { vi: "SSAO — Ambient Occlusion không gian màn hình", en: "SSAO — Screen-Space Ambient Occlusion" },
    summary: {
      vi: "Ước lượng bóng đổ tiếp xúc chỉ từ depth/normal buffer: kernel sampling, bias, và vì sao SSAO luôn có artifact ở rìa màn hình.",
      en: "Approximating contact shadows from just the depth/normal buffer: kernel sampling, bias, and why SSAO always artifacts at screen edges.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["postfx"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["depth-of-field-and-motion-blur"],
    objectives: {
      vi: [
        "Giải thích SSAO lấy mẫu quanh mỗi pixel trong không gian view thế nào",
        "Điều chỉnh radius/bias để giảm banding và halo artifact",
        "Nhận biết giới hạn screen-space: occlusion từ vật ngoài khung hình bị bỏ sót",
      ],
      en: [
        "Explain how SSAO samples a kernel around each pixel in view space",
        "Tune radius/bias to reduce banding and halo artifacts",
        "Recognize screen-space limits: occlusion from off-screen geometry gets missed",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-cinematic-scene",
    trackId: "postprocessing",
    moduleId: "postprocessing-01-composer-and-effects",
    order: 5,
    title: { vi: "Mini-build: Cảnh điện ảnh", en: "Mini-build: Cinematic Scene" },
    summary: {
      vi: "Ghép bloom, DOF và SSAO vào một cảnh Three.js có sẵn để tạo cảm giác điện ảnh — mà vẫn giữ frame time trong ngân sách.",
      en: "Stack bloom, DOF and SSAO onto an existing Three.js scene for a cinematic feel — while keeping frame time in budget.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["postfx", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["ssao"],
    objectives: {
      vi: [
        "Kết hợp nhiều pass mà không làm cảnh trông 'quá tay'",
        "Đo frame time trước/sau và giải trình chi phí từng pass",
      ],
      en: [
        "Combine multiple passes without making the scene look overdone",
        "Measure before/after frame time and account for each pass's cost",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "stylistic-effects-grain-vignette",
    trackId: "postprocessing",
    moduleId: "postprocessing-02-grading-and-custom",
    order: 6,
    title: {
      vi: "Hiệu ứng phong cách: Grain, Vignette, Chromatic Aberration",
      en: "Stylistic Effects: Grain, Vignette, Chromatic Aberration",
    },
    summary: {
      vi: "Ba hiệu ứng rẻ về chi phí nhưng đổi hoàn toàn cảm giác của cảnh: film grain, vignette và chromatic aberration — và liều lượng hợp lý.",
      en: "Three cheap effects that completely change a scene's mood: film grain, vignette and chromatic aberration — and how much is too much.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["postfx", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-cinematic-scene"],
    objectives: {
      vi: [
        "Viết film grain bằng noise theo thời gian, không lặp pattern",
        "Cấu hình vignette và chromatic aberration bằng shader đơn giản",
        "Nhận biết ranh giới giữa 'phong cách' và 'lạm dụng hiệu ứng'",
      ],
      en: [
        "Write time-varying film grain from noise so the pattern never repeats",
        "Configure vignette and chromatic aberration with a simple shader",
        "Tell the line between 'stylistic' and 'overused effect'",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "color-grading-lut-tonemapping",
    trackId: "postprocessing",
    moduleId: "postprocessing-02-grading-and-custom",
    order: 7,
    title: { vi: "Color Grading, LUT & Tone Mapping", en: "Color Grading, LUTs & Tone Mapping" },
    summary: {
      vi: "LUT 3D và tone mapping (ACES, Reinhard) nhìn dưới cùng một mô hình: một phép biến đổi màu áp lên toàn cảnh, tính trong linear rồi mới ra sRGB.",
      en: "3D LUTs and tone mapping (ACES, Reinhard) seen as one mental model: a single color transform applied to the whole scene, computed in linear before sRGB output.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["postfx", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["stylistic-effects-grain-vignette"],
    objectives: {
      vi: [
        "Áp một 3D LUT lên ảnh render bằng texture lookup",
        "So sánh ACES và Reinhard tone mapping trên cùng một cảnh HDR",
        "Giải thích vì sao grading phải xảy ra sau tone mapping, không phải trước",
      ],
      en: [
        "Apply a 3D LUT to a rendered image via texture lookup",
        "Compare ACES and Reinhard tone mapping on the same HDR scene",
        "Explain why grading must happen after tone mapping, not before",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "writing-custom-passes",
    trackId: "postprocessing",
    moduleId: "postprocessing-02-grading-and-custom",
    order: 8,
    title: { vi: "Tự viết Custom Pass", en: "Writing Custom Passes" },
    summary: {
      vi: "Cấu trúc tối thiểu của một Pass trong postprocessing: uniforms, fragment shader, và cách nó đọc/ghi render target đúng chuẩn composer.",
      en: "The minimal anatomy of a Pass: uniforms, a fragment shader, and how it reads/writes render targets to fit the composer's contract.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["postfx", "shader", "glsl"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["color-grading-lut-tonemapping"],
    objectives: {
      vi: [
        "Viết một Pass tuỳ chỉnh kế thừa từ lớp Pass cơ sở",
        "Quản lý uniform và render target đúng vòng đời render",
        "Test pass tự viết độc lập trước khi ghép vào chuỗi composer",
      ],
      en: [
        "Write a custom Pass subclassing the base Pass class",
        "Manage uniforms and render targets correctly across the render lifecycle",
        "Test a custom pass in isolation before chaining it into the composer",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "pass-order-and-fillrate",
    trackId: "postprocessing",
    moduleId: "postprocessing-02-grading-and-custom",
    order: 9,
    title: { vi: "Thứ tự Pass & Chi phí Fillrate", en: "Pass Order & Fillrate Cost" },
    summary: {
      vi: "Đổi thứ tự hai pass có thể đổi cả kết quả lẫn tốc độ: nguyên tắc sắp xếp pass đúng và cách tính chi phí fillrate tích luỹ.",
      en: "Swapping two passes can change both the result and the speed: rules for correct pass ordering and how to reason about cumulative fillrate cost.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["postfx", "perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["writing-custom-passes"],
    objectives: {
      vi: [
        "Sắp xếp thứ tự pass hợp lý (ví dụ bloom trước hay sau tone mapping)",
        "Tính fillrate cost gần đúng cho một chuỗi pass ở một độ phân giải cho trước",
        "Gộp hoặc loại bỏ pass dư thừa để giảm số lần sample toàn màn hình",
      ],
      en: [
        "Order passes correctly (e.g. bloom before or after tone mapping)",
        "Estimate fillrate cost for a pass chain at a given resolution",
        "Merge or cut redundant passes to reduce full-screen sample counts",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-signature-effect-stack",
    trackId: "postprocessing",
    moduleId: "postprocessing-02-grading-and-custom",
    order: 10,
    title: { vi: "Mini-build: Bộ hiệu ứng chữ ký", en: "Mini-build: Signature Effect Stack" },
    summary: {
      vi: "Thiết kế một chuỗi post-processing mang phong cách riêng cho một cảnh, tối ưu thứ tự pass và giữ frame time trong ngân sách 60fps.",
      en: "Design a post-processing chain with a distinct visual signature for one scene, order the passes deliberately and keep frame time inside a 60fps budget.",
    },
    difficulty: 4,
    estimatedMinutes: 60,
    tags: ["postfx", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["pass-order-and-fillrate"],
    objectives: {
      vi: [
        "Tự chọn và sắp xếp một tổ hợp pass thể hiện phong cách riêng",
        "Viết ít nhất một custom pass trong chuỗi đó",
        "Chứng minh bằng số đo rằng chuỗi vẫn chạy trong ngân sách frame time",
      ],
      en: [
        "Choose and order a pass combination with a distinct visual signature",
        "Include at least one custom pass in that chain",
        "Prove with measurements that the chain stays inside the frame-time budget",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
