import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "pbr",
  order: 11,
  title: { vi: "PBR & Lighting Theory", en: "PBR & Lighting Theory" },
  summary: {
    vi: "Rendering equation, BRDF, IBL — hiểu vật liệu và ánh sáng đủ sâu để biết vì sao asset của bạn trông 'nhựa'.",
    en: "The rendering equation, BRDFs, IBL — understanding materials and light deeply enough to know why your assets look plastic.",
  },
  moduleIds: ["pbr-01-brdf-theory", "pbr-02-image-based-lighting"],
};

export const modules: ModuleDef[] = [
  {
    id: "pbr-01-brdf-theory",
    trackId: "pbr",
    order: 1,
    title: { vi: "Lý thuyết BRDF", en: "BRDF Theory" },
    lessonSlugs: [
      "rendering-equation-intuition",
      "brdf-and-microfacets",
      "fresnel-and-schlick",
      "metalness-roughness-workflow",
      "checkpoint-material-study",
    ],
  },
  {
    id: "pbr-02-image-based-lighting",
    trackId: "pbr",
    order: 2,
    title: { vi: "Ánh sáng từ ảnh", en: "Image-Based Lighting" },
    lessonSlugs: [
      "ibl-irradiance-and-prefilter",
      "hdri-exposure-tonemapping",
      "shadow-techniques-pcf-vsm-csm",
      "area-lights-and-probes",
      "why-assets-look-like-plastic",
      "checkpoint-studio-lighting-setup",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "rendering-equation-intuition",
    trackId: "pbr",
    moduleId: "pbr-01-brdf-theory",
    order: 1,
    title: { vi: "Trực giác về Rendering Equation", en: "Rendering Equation Intuition" },
    summary: {
      vi: "Phương trình duy nhất mà mọi model ánh sáng cố gắng xấp xỉ: ánh sáng ra = phát xạ + tích phân ánh sáng vào nhân với BRDF — hiểu ý nghĩa từng số hạng, không cần giải nó.",
      en: "The one equation every lighting model approximates: outgoing light = emission + the integral of incoming light times the BRDF — understand each term's meaning, not how to solve it.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["pbr"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-signature-effect-stack"],
    objectives: {
      vi: [
        "Đọc công thức rendering equation và chỉ ra ý nghĩa từng số hạng (Lo, Le, BRDF, Li, cosθ)",
        "Giải thích vì sao real-time rendering luôn là xấp xỉ, không phải giải chính xác",
        "Liên hệ rendering equation với các model quen thuộc (Lambert, Phong) như trường hợp riêng",
      ],
      en: [
        "Read the rendering equation and state each term's meaning (Lo, Le, BRDF, Li, cosθ)",
        "Explain why real-time rendering is always an approximation, never an exact solve",
        "Connect the rendering equation to familiar models (Lambert, Phong) as special cases",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "brdf-and-microfacets",
    trackId: "pbr",
    moduleId: "pbr-01-brdf-theory",
    order: 2,
    title: { vi: "BRDF & Mô hình Microfacet", en: "BRDFs & the Microfacet Model" },
    summary: {
      vi: "Bề mặt thô ráp ở góc nhìn vĩ mô nhưng là hàng triệu gương nhỏ hoàn hảo ở góc nhìn vi mô — Cook-Torrance và ba thành phần D, G, F.",
      en: "A rough surface at macro scale is millions of tiny perfect mirrors at micro scale — Cook-Torrance and its three terms D, G, F.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["pbr", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["rendering-equation-intuition"],
    objectives: {
      vi: [
        "Giải thích trực giác microfacet: roughness là phân bố hướng pháp tuyến vi mô",
        "Nêu vai trò của D (phân bố), G (che khuất) và F (Fresnel) trong Cook-Torrance",
        "Cài đặt công thức Cook-Torrance cơ bản trong fragment shader",
      ],
      en: [
        "Explain the microfacet intuition: roughness is a distribution of micro-normal directions",
        "State the role of D (distribution), G (shadowing/masking) and F (Fresnel) in Cook-Torrance",
        "Implement a basic Cook-Torrance formula in a fragment shader",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "fresnel-and-schlick",
    trackId: "pbr",
    moduleId: "pbr-01-brdf-theory",
    order: 3,
    title: { vi: "Fresnel & Xấp xỉ Schlick", en: "Fresnel & the Schlick Approximation" },
    summary: {
      vi: "Vì sao mọi bề mặt phản chiếu gắt hơn ở góc nhìn xiên — hiệu ứng Fresnel và công thức xấp xỉ Schlick rẻ tiền mà mọi PBR shader đều dùng.",
      en: "Why every surface reflects harder at a grazing angle — the Fresnel effect and the cheap Schlick approximation every PBR shader relies on.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["pbr", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["brdf-and-microfacets"],
    objectives: {
      vi: [
        "Giải thích hiệu ứng Fresnel bằng ví dụ quan sát được (mặt nước, bể cá)",
        "Viết công thức Schlick approximation và áp dụng cho dielectric lẫn kim loại",
        "Tính F0 cho vật liệu phi kim và kim loại khác nhau",
      ],
      en: [
        "Explain the Fresnel effect with observable examples (a water surface, a fish tank)",
        "Write the Schlick approximation and apply it to both dielectrics and metals",
        "Compute F0 for different dielectric and metallic materials",
      ],
    },
    hasDemo: true,
    hasPlayground: true,
  },
  {
    slug: "metalness-roughness-workflow",
    trackId: "pbr",
    moduleId: "pbr-01-brdf-theory",
    order: 4,
    title: { vi: "Metalness/Roughness Workflow", en: "The Metalness/Roughness Workflow" },
    summary: {
      vi: "Chuẩn công nghiệp để mô tả vật liệu bằng hai kênh: metalness quyết định F0 từ đâu ra, roughness quyết định BRDF nhọn hay tù.",
      en: "The industry-standard way to describe materials with two channels: metalness decides where F0 comes from, roughness decides how sharp or blurred the BRDF is.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["pbr", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["fresnel-and-schlick"],
    objectives: {
      vi: [
        "Phân biệt workflow metalness/roughness với specular/glossiness",
        "Đọc bộ texture map (albedo, metalness, roughness, normal, AO) và ánh xạ vào MeshStandardMaterial",
        "Giải thích vì sao metalness gần như luôn là 0 hoặc 1, hiếm khi ở giữa",
      ],
      en: [
        "Distinguish the metalness/roughness workflow from specular/glossiness",
        "Read a texture map set (albedo, metalness, roughness, normal, AO) into MeshStandardMaterial",
        "Explain why metalness is almost always 0 or 1, rarely in between",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-material-study",
    trackId: "pbr",
    moduleId: "pbr-01-brdf-theory",
    order: 5,
    title: { vi: "Mini-build: Nghiên cứu vật liệu", en: "Mini-build: Material Study" },
    summary: {
      vi: "Dựng một dãy quả cầu thể hiện toàn bộ dải metalness × roughness và đối chiếu bằng mắt với lý thuyết BRDF vừa học.",
      en: "Build a grid of spheres sweeping the full metalness × roughness range and visually verify it against the BRDF theory just covered.",
    },
    difficulty: 4,
    estimatedMinutes: 50,
    tags: ["pbr", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["metalness-roughness-workflow"],
    objectives: {
      vi: [
        "Tạo material sweep thể hiện đúng ảnh hưởng của từng tham số",
        "Đối chiếu kết quả quan sát với dự đoán từ lý thuyết Fresnel/microfacet",
      ],
      en: [
        "Build a material sweep that correctly demonstrates each parameter's effect",
        "Cross-check the observed result against Fresnel/microfacet theory predictions",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "ibl-irradiance-and-prefilter",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 6,
    title: { vi: "IBL: Irradiance Map & Prefiltered Environment", en: "IBL: Irradiance Maps & Prefiltered Environments" },
    summary: {
      vi: "Ánh sáng môi trường thực tế thay vì vài đèn điểm: convolve HDRI thành irradiance map cho diffuse và prefiltered mipmap cho specular, cộng BRDF LUT để ghép lại đúng.",
      en: "Real environment lighting instead of a handful of point lights: convolve an HDRI into an irradiance map for diffuse and a prefiltered mip chain for specular, plus a BRDF LUT to recombine them correctly.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["pbr", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-material-study"],
    objectives: {
      vi: [
        "Giải thích vì sao IBL cần tách riêng thành phần diffuse (irradiance) và specular (prefiltered)",
        "Đọc split-sum approximation và vai trò của BRDF LUT",
        "Cấu hình PMREMGenerator của Three.js cho một HDRI",
      ],
      en: [
        "Explain why IBL splits diffuse (irradiance) from specular (prefiltered) contributions",
        "Read the split-sum approximation and the BRDF LUT's role in it",
        "Configure Three.js's PMREMGenerator for an HDRI",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "hdri-exposure-tonemapping",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 7,
    title: { vi: "HDRI, Exposure & Tone Mapping", en: "HDRI, Exposure & Tone Mapping" },
    summary: {
      vi: "HDRI mang dải sáng vượt xa màn hình hiển thị được — exposure và tone mapping là hai nút vặn quyết định cảnh sáng đẹp hay cháy sáng.",
      en: "HDRIs carry a dynamic range far beyond what a display can show — exposure and tone mapping are the two dials that decide whether a scene looks lit or blown out.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["pbr", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["ibl-irradiance-and-prefilter"],
    objectives: {
      vi: [
        "Chọn và load HDRI phù hợp cho một cảnh cụ thể",
        "Điều chỉnh toneMappingExposure và giải thích ảnh hưởng lên toàn cảnh",
        "Phân biệt exposure (trước tone mapping) với brightness chỉnh sau hậu kỳ",
      ],
      en: [
        "Choose and load an HDRI appropriate for a given scene",
        "Adjust toneMappingExposure and explain its effect on the whole scene",
        "Distinguish exposure (pre-tone-mapping) from post-hoc brightness adjustment",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "shadow-techniques-pcf-vsm-csm",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 8,
    title: { vi: "Kỹ thuật đổ bóng: PCF, VSM, CSM", en: "Shadow Techniques: PCF, VSM, CSM" },
    summary: {
      vi: "Shadow map thô luôn răng cưa — PCF làm mềm bằng sampling, VSM làm mềm bằng thống kê, và CSM giải bài toán bóng đổ xa trong cảnh ngoài trời rộng.",
      en: "A raw shadow map is always jagged — PCF softens it by sampling, VSM softens it statistically, and CSM solves long-range shadows in wide outdoor scenes.",
    },
    difficulty: 4,
    estimatedMinutes: 45,
    tags: ["pbr", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["hdri-exposure-tonemapping"],
    objectives: {
      vi: [
        "Giải thích nguyên lý shadow mapping cơ bản và vì sao nó bị răng cưa/peter-panning",
        "So sánh PCF và VSM về chất lượng, chi phí và artifact",
        "Giải thích cascaded shadow maps giải quyết vấn đề khoảng cách camera thế nào",
      ],
      en: [
        "Explain basic shadow mapping and why it aliases or peter-pans",
        "Compare PCF and VSM on quality, cost and artifacts",
        "Explain how cascaded shadow maps solve the camera-distance problem",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "area-lights-and-probes",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 9,
    title: { vi: "Area Light & Light Probe", en: "Area Lights & Light Probes" },
    summary: {
      vi: "Đèn điểm là một điểm toán học, nhưng đèn thật có diện tích: RectAreaLight dùng LTC để xấp xỉ, và light probe nội suy ánh sáng gián tiếp giữa các vùng.",
      en: "A point light is a mathematical point, but real lights have area: RectAreaLight approximates with LTC, and light probes interpolate indirect lighting across regions.",
    },
    difficulty: 4,
    estimatedMinutes: 30,
    tags: ["pbr", "threejs"],
    tier: "elective",
    kind: "lesson",
    prerequisites: ["shadow-techniques-pcf-vsm-csm"],
    objectives: {
      vi: [
        "Cấu hình RectAreaLight và giải thích LTC (linearly transformed cosines) ở mức trực giác",
        "Đặt light probe để nội suy ánh sáng gián tiếp trong một cảnh tĩnh",
      ],
      en: [
        "Configure RectAreaLight and explain LTC (linearly transformed cosines) at an intuitive level",
        "Place light probes to interpolate indirect lighting in a static scene",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "why-assets-look-like-plastic",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 10,
    title: { vi: "Vì sao Asset của bạn trông như Nhựa", en: "Why Your Assets Look Like Plastic" },
    summary: {
      vi: "Bài chẩn đoán tổng hợp: roughness quá thấp, thiếu variation, IBL sai exposure, hoặc thiếu AO — danh sách nguyên nhân thường gặp khiến PBR nhìn giả.",
      en: "A diagnostic lesson: roughness set too low, no variation, wrong IBL exposure, or missing AO — the usual list of reasons PBR renders end up looking fake.",
    },
    difficulty: 4,
    estimatedMinutes: 30,
    tags: ["pbr", "color"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["shadow-techniques-pcf-vsm-csm"],
    objectives: {
      vi: [
        "Chẩn đoán một cảnh 'nhựa' bằng cách kiểm tra từng nguyên nhân theo danh sách",
        "Sửa ít nhất ba lỗi PBR phổ biến trên cùng một cảnh mẫu",
      ],
      en: [
        "Diagnose a 'plastic-looking' scene by checking each cause on a list",
        "Fix at least three common PBR mistakes on the same sample scene",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-studio-lighting-setup",
    trackId: "pbr",
    moduleId: "pbr-02-image-based-lighting",
    order: 11,
    title: { vi: "Mini-build: Dựng Studio Lighting", en: "Mini-build: Studio Lighting Setup" },
    summary: {
      vi: "Dựng một bối cảnh studio ba điểm sáng kết hợp IBL cho một vật thể trưng bày, đạt chất lượng trình bày sản phẩm thật.",
      en: "Build a three-point studio lighting setup combined with IBL for a showcased object, reaching real product-presentation quality.",
    },
    difficulty: 4,
    estimatedMinutes: 60,
    tags: ["pbr", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["why-assets-look-like-plastic"],
    objectives: {
      vi: [
        "Kết hợp IBL, area light và shadow technique phù hợp trong một cảnh",
        "Tinh chỉnh exposure và tone mapping để đạt chất lượng trình bày sản phẩm",
      ],
      en: [
        "Combine IBL, area lights and an appropriate shadow technique in one scene",
        "Tune exposure and tone mapping to reach product-presentation quality",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
