import type { LessonMeta, ModuleDef, TrackDef } from "../types";

export const track: TrackDef = {
  id: "performance",
  order: 12,
  title: { vi: "Performance & Production", en: "Performance & Production" },
  summary: {
    vi: "Đo trước khi tối ưu: draw call, culling, asset pipeline, mobile GPU và cách ship cảnh 3D chạy mượt thật sự.",
    en: "Measure before optimizing: draw calls, culling, asset pipelines, mobile GPUs and shipping 3D that actually runs smooth.",
  },
  moduleIds: [
    "performance-01-measure-first",
    "performance-02-scale-the-scene",
    "performance-03-ship-to-production",
  ],
};

export const modules: ModuleDef[] = [
  {
    id: "performance-01-measure-first",
    trackId: "performance",
    order: 1,
    title: { vi: "Đo trước đã", en: "Measure First" },
    lessonSlugs: [
      "profiling-webgl-tools",
      "draw-calls-batching-instancing",
      "checkpoint-profile-and-fix",
    ],
  },
  {
    id: "performance-02-scale-the-scene",
    trackId: "performance",
    order: 2,
    title: { vi: "Scale cảnh", en: "Scaling the Scene" },
    lessonSlugs: [
      "culling-and-lod",
      "texture-memory-budget",
      "shader-compilation-stalls",
      "asset-pipeline-draco-ktx2",
      "checkpoint-asset-diet",
    ],
  },
  {
    id: "performance-03-ship-to-production",
    trackId: "performance",
    order: 3,
    title: { vi: "Ship ra production", en: "Shipping to Production" },
    lessonSlugs: [
      "mobile-tile-gpus-and-overdraw",
      "adaptive-quality-tiers",
      "dispose-and-leak-hunting",
      "nextjs-ssr-hydration-canvas",
      "checkpoint-mobile-ready-scene",
    ],
  },
];

export const lessons: LessonMeta[] = [
  {
    slug: "profiling-webgl-tools",
    trackId: "performance",
    moduleId: "performance-01-measure-first",
    order: 1,
    title: { vi: "Công cụ Profiling cho WebGL", en: "WebGL Profiling Tools" },
    summary: {
      vi: "Trước khi tối ưu bất cứ thứ gì, đo nó: Spector.js để soi từng draw call, Chrome DevTools Performance tab, stats.js cho FPS thời gian thực, và RenderDoc khi cần soi sâu GPU.",
      en: "Before optimizing anything, measure it: Spector.js to inspect every draw call, Chrome DevTools' Performance tab, stats.js for real-time FPS, and RenderDoc when you need to dig into the GPU.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["perf", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-studio-lighting-setup"],
    objectives: {
      vi: [
        "Bắt một frame bằng Spector.js và đọc được danh sách draw call/state change",
        "Dùng Chrome DevTools Performance để phân biệt bottleneck CPU và GPU",
        "Gắn stats.js vào một app R3F/Three.js để theo dõi FPS liên tục",
      ],
      en: [
        "Capture a frame with Spector.js and read its draw call/state change list",
        "Use Chrome DevTools Performance to tell CPU bottlenecks from GPU ones",
        "Wire stats.js into an R3F/Three.js app for continuous FPS monitoring",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "draw-calls-batching-instancing",
    trackId: "performance",
    moduleId: "performance-01-measure-first",
    order: 2,
    title: { vi: "Draw Call, Batching & Instancing", en: "Draw Calls, Batching & Instancing" },
    summary: {
      vi: "Mỗi draw call có phí cố định trên CPU — gộp geometry tĩnh bằng batching, và nhân bản hàng nghìn object giống nhau bằng một draw call duy nhất với instancing.",
      en: "Every draw call has a fixed CPU cost — merge static geometry with batching, and render thousands of identical objects in a single draw call with instancing.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["perf", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["profiling-webgl-tools"],
    objectives: {
      vi: [
        "Đo số draw call của một cảnh và xác định draw call nào có thể gộp",
        "Gộp geometry tĩnh bằng BufferGeometryUtils.mergeGeometries",
        "Chuyển một vòng lặp Mesh sang InstancedMesh và đo cải thiện",
      ],
      en: [
        "Count a scene's draw calls and identify which ones can be merged",
        "Merge static geometry with BufferGeometryUtils.mergeGeometries",
        "Convert a Mesh loop to InstancedMesh and measure the improvement",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-profile-and-fix",
    trackId: "performance",
    moduleId: "performance-01-measure-first",
    order: 3,
    title: { vi: "Mini-build: Profile & Sửa cảnh chậm", en: "Mini-build: Profile & Fix a Slow Scene" },
    summary: {
      vi: "Nhận một cảnh cố tình dựng chậm, dùng đúng công cụ để tìm bottleneck thật, rồi sửa và chứng minh bằng số đo trước/sau.",
      en: "Given a deliberately slow scene, use the right tools to find the real bottleneck, fix it, and prove the improvement with before/after numbers.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["perf", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["draw-calls-batching-instancing"],
    objectives: {
      vi: [
        "Tìm đúng bottleneck bằng profiler thay vì đoán",
        "Áp dụng ít nhất hai kỹ thuật tối ưu đã học để sửa cảnh",
        "Trình bày số đo before/after chứng minh cải thiện",
      ],
      en: [
        "Find the real bottleneck with a profiler instead of guessing",
        "Apply at least two optimization techniques learned so far to fix the scene",
        "Present before/after numbers proving the improvement",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "culling-and-lod",
    trackId: "performance",
    moduleId: "performance-02-scale-the-scene",
    order: 4,
    title: { vi: "Culling & LOD", en: "Culling & LOD" },
    summary: {
      vi: "Đừng render cái không cần thấy: frustum culling loại vật ngoài khung hình, occlusion culling loại vật bị che, và LOD giảm chi tiết theo khoảng cách.",
      en: "Don't render what isn't seen: frustum culling drops off-screen objects, occlusion culling drops hidden ones, and LOD reduces detail with distance.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["perf", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-profile-and-fix"],
    objectives: {
      vi: [
        "Giải thích frustum culling hoạt động tự động thế nào trong Three.js và khi nào nó thất bại",
        "Cài đặt occlusion culling thủ công cho trường hợp Three.js không tự lo được",
        "Dựng một chuỗi LOD chuyển mức chi tiết theo khoảng cách camera",
      ],
      en: [
        "Explain how Three.js's automatic frustum culling works and when it fails",
        "Implement manual occlusion culling for cases Three.js doesn't handle",
        "Build an LOD chain that swaps detail levels by camera distance",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "texture-memory-budget",
    trackId: "performance",
    moduleId: "performance-02-scale-the-scene",
    order: 5,
    title: { vi: "Ngân sách Bộ nhớ Texture", en: "Texture Memory Budget" },
    summary: {
      vi: "Texture chiếm phần lớn VRAM một cách âm thầm — tính kích thước thật của một texture trên GPU và lập ngân sách bộ nhớ cho cả cảnh.",
      en: "Textures silently eat most of a scene's VRAM — compute a texture's real GPU footprint and set a memory budget for the whole scene.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["culling-and-lod"],
    objectives: {
      vi: [
        "Tính dung lượng GPU thực của một texture từ kích thước, format và mipmap",
        "Lập ngân sách bộ nhớ texture cho một thiết bị mục tiêu cụ thể",
        "Áp dụng compressed texture format để giảm dung lượng mà không giảm resolution",
      ],
      en: [
        "Compute a texture's real GPU footprint from dimensions, format and mipmaps",
        "Set a texture memory budget for a specific target device",
        "Apply compressed texture formats to shrink footprint without cutting resolution",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "shader-compilation-stalls",
    trackId: "performance",
    moduleId: "performance-02-scale-the-scene",
    order: 6,
    title: { vi: "Đứng hình do Compile Shader", en: "Shader Compilation Stalls" },
    summary: {
      vi: "Shader compile lazy lần đầu dùng gây giật hình giữa cảnh — pre-warm bằng cách compile trước và giữ số lượng shader variant trong tầm kiểm soát.",
      en: "Lazy first-use shader compilation causes mid-scene stutter — pre-warm by compiling ahead of time and keep the number of shader variants under control.",
    },
    difficulty: 3,
    estimatedMinutes: 30,
    tags: ["perf", "shader"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["texture-memory-budget"],
    objectives: {
      vi: [
        "Giải thích vì sao WebGL compile shader lười biếng theo yêu cầu đầu tiên",
        "Pre-warm shader bằng renderer.compile() trước khi cảnh hiển thị",
        "Giảm số lượng shader variant sinh ra từ material defines",
      ],
      en: [
        "Explain why WebGL lazily compiles shaders on first use",
        "Pre-warm shaders with renderer.compile() before the scene is shown",
        "Reduce the number of shader variants generated from material defines",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "asset-pipeline-draco-ktx2",
    trackId: "performance",
    moduleId: "performance-02-scale-the-scene",
    order: 7,
    title: { vi: "Asset Pipeline: Draco & KTX2", en: "Asset Pipeline: Draco & KTX2" },
    summary: {
      vi: "Nén geometry với Draco và nén texture GPU-native với KTX2/Basis — dùng gltf-transform để tự động hoá cả pipeline thay vì làm tay từng file.",
      en: "Compress geometry with Draco and GPU-native texture compression with KTX2/Basis — automate the whole pipeline with gltf-transform instead of hand-processing every file.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["perf", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["shader-compilation-stalls"],
    objectives: {
      vi: [
        "Nén một file GLTF bằng Draco và đo tỉ lệ giảm dung lượng",
        "Chuyển texture sang KTX2/Basis và load đúng bằng KTX2Loader",
        "Viết một script gltf-transform xử lý hàng loạt asset",
      ],
      en: [
        "Compress a GLTF file with Draco and measure the size reduction",
        "Convert textures to KTX2/Basis and load them correctly with KTX2Loader",
        "Write a gltf-transform script to batch-process assets",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-asset-diet",
    trackId: "performance",
    moduleId: "performance-02-scale-the-scene",
    order: 8,
    title: { vi: "Mini-build: Asset Diet", en: "Mini-build: Asset Diet" },
    summary: {
      vi: "Nhận một cảnh có asset quá nặng, áp toàn bộ kỹ thuật nén/culling/LOD đã học để giảm dung lượng tải và VRAM một cách đo được.",
      en: "Given a scene with bloated assets, apply every compression/culling/LOD technique learned so far to measurably shrink load size and VRAM.",
    },
    difficulty: 4,
    estimatedMinutes: 55,
    tags: ["perf", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["asset-pipeline-draco-ktx2"],
    objectives: {
      vi: [
        "Giảm dung lượng tải của một cảnh ít nhất 50% mà chất lượng nhìn không giảm rõ rệt",
        "Trình bày bảng đo trước/sau: dung lượng file, VRAM, draw call",
      ],
      en: [
        "Cut a scene's load size by at least 50% without visibly hurting quality",
        "Present a before/after table: file size, VRAM, draw calls",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
  {
    slug: "mobile-tile-gpus-and-overdraw",
    trackId: "performance",
    moduleId: "performance-03-ship-to-production",
    order: 9,
    title: { vi: "GPU Mobile dạng Tile & Overdraw", en: "Mobile Tile-Based GPUs & Overdraw" },
    summary: {
      vi: "GPU mobile render theo tile chứ không phải immediate mode như desktop — overdraw là kẻ giết hiệu năng số một, và vì sao nó tệ hơn nhiều trên mobile.",
      en: "Mobile GPUs render tile-by-tile, not immediate-mode like desktop — overdraw is public enemy number one, and it's far worse on mobile than desktop.",
    },
    difficulty: 4,
    estimatedMinutes: 35,
    tags: ["perf"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["checkpoint-asset-diet"],
    objectives: {
      vi: [
        "Giải thích kiến trúc tile-based rendering khác gì so với desktop GPU",
        "Đo overdraw của một cảnh và xác định nguyên nhân (transparency, layer chồng)",
        "Giảm overdraw bằng cách sắp thứ tự render và cắt bớt transparency thừa",
      ],
      en: [
        "Explain how tile-based rendering architecture differs from desktop GPUs",
        "Measure a scene's overdraw and identify its causes (transparency, stacked layers)",
        "Reduce overdraw by reordering rendering and trimming unnecessary transparency",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "adaptive-quality-tiers",
    trackId: "performance",
    moduleId: "performance-03-ship-to-production",
    order: 10,
    title: { vi: "Adaptive Quality Tier", en: "Adaptive Quality Tiers" },
    summary: {
      vi: "Không phải mọi thiết bị đều xứng đáng cùng một cảnh: phát hiện GPU/thiết bị và tự động giảm resolution, effect hoặc số particle theo tầng chất lượng.",
      en: "Not every device deserves the same scene: detect the GPU/device and automatically scale resolution, effects or particle count across quality tiers.",
    },
    difficulty: 4,
    estimatedMinutes: 40,
    tags: ["perf", "threejs"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["mobile-tile-gpus-and-overdraw"],
    objectives: {
      vi: [
        "Phát hiện tier thiết bị bằng benchmark ngắn hoặc heuristics (GPU string, deviceMemory)",
        "Thiết kế 2-3 tầng chất lượng với tham số resolution/effect/particle khác nhau",
        "Chuyển tier động khi frame time tụt dưới ngưỡng trong lúc chạy",
      ],
      en: [
        "Detect device tier via a short benchmark or heuristics (GPU string, deviceMemory)",
        "Design 2-3 quality tiers with different resolution/effect/particle parameters",
        "Switch tiers dynamically when frame time drops below a threshold at runtime",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "dispose-and-leak-hunting",
    trackId: "performance",
    moduleId: "performance-03-ship-to-production",
    order: 11,
    title: { vi: "Dispose & Săn Memory Leak", en: "Dispose & Leak Hunting" },
    summary: {
      vi: "Three.js không tự dọn GPU memory khi component unmount — dispose() phải gọi đúng chỗ, và cách săn leak bằng heap snapshot thay vì đoán.",
      en: "Three.js doesn't auto-clean GPU memory on unmount — dispose() has to be called in the right place, and leaks get hunted with heap snapshots, not guesses.",
    },
    difficulty: 3,
    estimatedMinutes: 35,
    tags: ["perf", "r3f"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["adaptive-quality-tiers"],
    objectives: {
      vi: [
        "Liệt kê những gì cần dispose thủ công (geometry, material, texture, render target)",
        "Bắt heap snapshot trong Chrome DevTools và so sánh hai lần chụp để tìm leak",
        "Viết một custom hook dispose tái sử dụng được cho R3F",
      ],
      en: [
        "List what must be manually disposed (geometry, material, texture, render target)",
        "Capture Chrome DevTools heap snapshots and diff two captures to find a leak",
        "Write a reusable custom dispose hook for R3F",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "nextjs-ssr-hydration-canvas",
    trackId: "performance",
    moduleId: "performance-03-ship-to-production",
    order: 12,
    title: { vi: "Next.js SSR, Hydration & Canvas", en: "Next.js SSR, Hydration & Canvas" },
    summary: {
      vi: "Canvas WebGL không tồn tại trên server — chiến lược đúng để tránh hydration mismatch và giữ First Contentful Paint nhanh khi có cảnh 3D.",
      en: "A WebGL canvas doesn't exist on the server — the right strategy to avoid hydration mismatches and keep First Contentful Paint fast when a 3D scene is involved.",
    },
    difficulty: 3,
    estimatedMinutes: 40,
    tags: ["perf", "tooling"],
    tier: "core",
    kind: "lesson",
    prerequisites: ["dispose-and-leak-hunting"],
    objectives: {
      vi: [
        "Giải thích vì sao render canvas trực tiếp trên server gây hydration mismatch",
        "Dùng dynamic import với ssr: false đúng chỗ, đúng lý do",
        "Giữ FCP nhanh bằng cách tách canvas khỏi critical rendering path",
      ],
      en: [
        "Explain why rendering a canvas directly on the server causes a hydration mismatch",
        "Use dynamic import with ssr: false in the right place, for the right reason",
        "Keep FCP fast by separating the canvas from the critical rendering path",
      ],
    },
    hasDemo: true,
    hasPlayground: false,
  },
  {
    slug: "checkpoint-mobile-ready-scene",
    trackId: "performance",
    moduleId: "performance-03-ship-to-production",
    order: 13,
    title: { vi: "Mini-build: Cảnh sẵn sàng cho Mobile", en: "Mini-build: Mobile-Ready Scene" },
    summary: {
      vi: "Đưa một cảnh desktop-only về chạy mượt trên thiết bị tầm trung: áp dụng adaptive tier, dispose đúng, và kiểm chứng bằng thiết bị hoặc throttle thật.",
      en: "Take a desktop-only scene and make it run smoothly on a mid-range device: apply adaptive tiers, correct disposal, and verify with a real device or throttling.",
    },
    difficulty: 4,
    estimatedMinutes: 60,
    tags: ["perf", "build"],
    tier: "core",
    kind: "checkpoint",
    prerequisites: ["nextjs-ssr-hydration-canvas"],
    objectives: {
      vi: [
        "Áp dụng adaptive quality tier cho một cảnh có sẵn",
        "Xác nhận không leak sau nhiều lần mount/unmount",
        "Đo và chứng minh FPS ổn định trên profile thiết bị tầm trung (throttled)",
      ],
      en: [
        "Apply adaptive quality tiers to an existing scene",
        "Confirm no leaks after repeated mount/unmount cycles",
        "Measure and prove stable FPS on a mid-range device profile (throttled)",
      ],
    },
    hasDemo: false,
    hasPlayground: false,
  },
];
